### ISSUE TITLE
Wrong date on export data to file, Strava and Runanalyze

### ISSUE THREAD

**Issue by pes4murai** [jonasoreland/runnerup#1000]
Good afternoon,
at the end of the training when I import the file (.tcx) it has a wrong data.
The Yesterday's file has the date 02.June.2001 and is attached.
[RunnerUp_2021-01-16-15-34-59_Running.zip](https://github.com/jonasoreland/runnerup/files/5826268/RunnerUp_2021-01-16-15-34-59_Running.zip)

I've made also the auto import to Strava and Runanalyze with the same problem.
Phone is a Moto G 2014 with Android 7.2

**Comment by gerhardol** [comment]
The log has 2001 dates.
RU uses the GPS time when recording starts, it seems like this was the time reported by then. Maybe you did not have a good lock when starting?
GPS time should be more precise than system time normally, it is hard to find when the time is completely off like this...

**Comment by pes4murai** [comment]
Perfect, I totally understand the situation.
I'm closing this issue, thank you for your kind and  prompt reply.

Regards

**Comment by gerhardol** [comment]
I have considered to change the handling to use the system time instead, this is another "vote" for that.
This will decrease the precision slightly though.
So thanks for the issue.
