### ISSUE TITLE
Question: Testing / Unit Tests

### ISSUE THREAD

**Issue by winder** [jonasoreland/runnerup#1032]
I'm adding a silly feature to uploading workouts to a blockchain and was hoping to add some unit tests. I'm having trouble with manual testing to be honest.

Part of this feature involves writing a new "Summary" export format, which is basically something that could be written to twitter.

Some additional context: I'm an experienced developer and managed to pretty much implement my feature, but have not worked with Android before and am having trouble with some (probably basic) testing things.

So my questions...
1) When I configure android studio to load RunnerUp on my phone, there is no data. How can I test an upload with no data?
2) For a unit test I exported a db with one workout and added it as a test resource. I was unable to open the SQLiteDatabase, calls to `SQLiteDatabase.openDatabase` fail because there is no mock and I couldn't find a way to use a real SQLite DB.

**Comment by gerhardol** [comment]
RU do not have many unittesets, this has not been priotized...

>     1. When I configure android studio to load RunnerUp on my phone, there is no data. How can I test an upload with no data?

1. Use emulated GPS
  a. just move the emulator pint around
  b. Import any .gpx and play it in the emulator
  c. Use Mock GPS app like Lockito and play a .gpx track
2. Import an existing RU database Settings/Maintenance

>     2. For a unit test I exported a db with one workout and added it as a test resource. I was unable to open the SQLiteDatabase, calls to `SQLiteDatabase.openDatabase` fail because there is no mock and I couldn't find a way to use a real SQLite DB.

Not sure if that is possible to use a real SQLite db in unit test scenario. I would say that is an integration test, but that is just semantics
Mocking the db should be possible, I have not looked in to that.
Worst case, it is possible to add a wrapper interface to be able to mock, even if that is not my favorite.

**Comment by winder** [comment]
@gerhardol thanks for the quick response! I've never found satisfying way to "unit test" a SQL query that doesn't involve a real database... this may not be perfect but it is automated. For proper mocking / unit tests I suppose there would need to be a DB wrapper around the SQLiteDatabase objects.

Either way, I managed to write a test:
```
@RunWith(RobolectricTestRunner.class)
public class SummaryTest {
    SQLiteDatabase db;
    Formatter formatter;
    Summary sum;

    @Before
    public void setup() {
        File f = new File(getClass().getResource("/runnerup.db").getFile());
        db = SQLiteDatabase.openDatabase(f.getPath(), null, 0);
        formatter = new Formatter(ApplicationProvider.getApplicationContext());
        sum = new Summary(db, null, formatter);
    }

    @After
    public void teardown() {
        db.close();
    }

    @Test
    public void TestSummary() throws IOException {
        String str = sum.Summary(5);
        assertEquals("RUNNING: 2.29mi at Sun, 8 Aug 2021 05:02 PM EDT for 25m8s. 11:00/mi", str);
        str = sum.Summary(6);
        assertEquals("RUNNING: 2.33mi at Tue, 10 Aug 2021 01:43 PM EDT for 25m51s. 11:07/mi", str);
    }
}
```
