### ISSUE TITLE
program dies silently after a few kilometers with no data recorded at all.

### ISSUE THREAD

**Issue by sp4rkie** [jonasoreland/runnerup#1037]
smartphone: Sony G8441
Android version: 9
RunnerUp version: 2.3.6.0 
battery optimizations: excepted (i.e. off) for this app

no special settings, just using Audio cue standard (default) and Target 'None'
there were no GPS issues at the time of failure. osmand+ was running in parallel with no problems.

is there any additional info I can provide?
do eventually exist workarounds?
could I install a debug version of runnerup?

the issue occurs in about  1 of 10 cases

**Comment by gerhardol** [comment]
The normal problem in situations like this is that a taskkiller stops it.
https://dontkillmyapp.com/
I have a Sony myself (5ii w Android 11) and have not seen this. Maybe something in Android 9 for Sony?

You can install a Debug build in parallel to the Play version. There are no built versions, you can build yourself.
There are no changes in master related to this, a few updated libraries and Android 12 preparations, not likely to affect this.

The logcat when the problem occurred is probably needed, that is hard to provide during a run...
The logcat size can be increased.

**Comment by sp4rkie** [comment]
thanks for the answer, there is nothing special in Android 9 for Sony regarding task killer. No other of my used app has such problem either. I'll try to install a Debug build if time permits...

**Comment by sp4rkie** [comment]
I now accidentally discovered something very odd. What has happened?

- I yesterday started to run and record with RunnerUp at 08:43
- after about 14km the app crashed or died (as reported)
- looking again at the history today there actually is *some* activity recorded saying: activity start yesterday at 08:43 and distance of run 2.3km?!
- I then started to play around with RunnerUp and got to the 'Recompute activity' menu item
- I recomputed and - you won't believe it - a 28km distance recording (my complete running distance yesterday) shows up with all data in it (including many hours after the run)

conclusion:
some background process still worked after the app crash without notice. So you will not discover this until selecting 'Recompute activity'

**Comment by sp4rkie** [comment]
As far as possible I've now checked the other crashes for the symptoms above. It's always the same. 

The app-frontend crashes/disappears but recording in the background continues for hours/ sometimes days. I always wondered why the 'location' symbol in the notification bar sometimes was on even when  no abvious app was active at that time. 
Now I know some parts of the RunnerUp process framework still survived the crash...

**Comment by gerhardol** [comment]
I believe the intention is to continue recording or at least _restore_ automatically.
I thought the intention in Android was to stop the background services when the main app is stopped.
There are no crashes reported to Google Play about this.

If it occurs often maybe starting a debug session could capture the problem. (You may need an app like Lockito to provide GPS.)

The settings and sensors may give some hints too.

**Comment by sp4rkie** [comment]
for the time being I close this now. I can't reproduce the problem after reinstall+reconfiguration nor can I provide better material for diagnosis. cheers.

**Comment by sp4rkie** [comment]
I now accidentally got to know how to reproduce the problem:

1. start a recording
2. select the home button
3. select the app switcher button
4. select 'clear all' or selectively remove RU from the app switcher list

this makes the RU GUI disappear. I.e. you now even can start a new recording. But in most cases the GPS data recording process in the background continues to operate (without GUI). So you mostly won't loose data. 
You even can reproduce the problem multiple times. The recording background process mostly keeps running. Finally you have to kill the app manually to stop all of these.

To recover recorded data you must go to 'history' an select the desired entry. Mostly you only find the start time but no pace or recorded track length there. Then select 'recompute activity'. This recovers all track data recorded so far. Be aware the background process is still running. If you recover again after some time the displayed pace or track length will add up  accordingly. Until you kill RU manually.

**Comment by gerhardol** [comment]
I got the problem with the empty UI once on my new phone, but it started to work before I could troubleshoot.
This is the core problem to me.

Swiping the app away should finish the existing activity automatically, it works OK in the emulator but I see the same problem on a phone. Should not be a major problem if you know how to recreate.

**Comment by sp4rkie** [comment]
sure. That's why I closed the issue. Thanks for all your excellent work.
