### ISSUE TITLE
weirdos recording the first 400m: runnerup vs. osmand+

### ISSUE THREAD

**Issue by sp4rkie** [jonasoreland/runnerup#1039]
first of all: in the meantime I use runnerup each run. I like the flexible cue settings a lot. For navigation I run osmand+ in parallel. Nonetheless I had strange effects yesterday :-)

Please have a look at the attached picts. The blue track is recorded by osmand+. The red track  is recorded by runnerup the same time on the same smartphone device. The first few 100m runnerup jumps around like crazy and gives me an outstanding running  pace :-) After about 400m the phenomenon is over though. Both applications then show approximately the same track. The lower screenshot enlarges the track section where the issue fades out (i.e. the error disappears).

How can that be? Exist different data sources for GPS data on the same device?

![sshot_000](https://user-images.githubusercontent.com/3232165/131682913-cc2616e3-b4bc-47d5-9b40-3e42975c7110.jpg)
![sshot_001](https://user-images.githubusercontent.com/3232165/131682917-b7e00ed3-650d-4d6e-98c7-48f648ca75fe.jpg)

**Comment by gerhardol** [comment]
If you wait for the GPS to be stable before starting, this will improve (you may use the more info to see sats/accuracy/elevation to bcomee stable).
RU uses the data as reported from the GPS, no other filter than time/distance. This is why limiting updates can improve the experience.
It seems like that OsmAnd has a filter applied to the recorded GPS points. Is this live or is the track smoothed afterwards? (the pace can be smoothed separately too.) RU can use a simplification filter to do something similar, but that is only affecting the track after, not while running.

A live filter will affect how quickly pace is smoothed too (for instance when stopping), not just a benefit adding it.

**Comment by sp4rkie** [comment]
thanks for answering. I always start osmand+ several minutes prior to starting the run and pressing record on RU. Please have a look at the attached image of the live recording shortly before I start . Again the blue track is recorded by osmand+. Of course the track floats around when still at home (blue 'mesh'). In this screenshot I removed the parts of the track regarding the return. I use JOSM for displaying *.gpx data.

RU gets started when I'm already running and satellites are safely synced since minutes. This normally works like a charm.

I'm not aware of any filters/smoothers in effect. Except there is 'Kalman filter' selected in osmand+.

Logging interval is set to 1s in both applications.

![sshot_000](https://user-images.githubusercontent.com/3232165/131692626-9fcac11f-3ae0-40d4-8fa6-8a92ce15ecb7.jpg)

**Comment by gerhardol** [comment]
> thanks for answering. I always start osmand+ several minutes prior to starting the run and pressing record on RU. Please have a look at the attached image of the live recording shortly before I start . Again the blue track is recorded by osmand+. Of course the track floats around when still at home (blue 'mesh'). In this screenshot I removed the parts of the track regarding the return. I use JOSM for displaying *.gpx data.
> 
> RU gets started when I'm already running and satellites are safely synced since minutes. This normally works like a charm.

Yes, that should be enough to have a stable GPS, if GPS is stable , it is for all apps.

> I'm not aware of any filters/smoothers in effect. Except there is 'Kalman filter' selected in osmand+.

Kalman is the most common GPS smoother.
How is the correlation to map paths?
Should be visible in OsmAnd too, load the RU .gpx.

OsmAnd+ may also use Google fused locations (commercial API).
I guess the source is available to review.

What device, version and type of terrain is this in?

**Comment by sp4rkie** [comment]
> How is the correlation to map paths?

not bad so far. To see the difference I now will deactivate 'Kalman filter' in osmand+. Then no filters should be active nowhere. I hope...

> Should be visible in OsmAnd too, load the RU .gpx.

I loaded the jumpy RU track in osmand+. Looks exactly as in JOSM.  No smoothing of the track takes place. It is shown as is. It appears 'kalman' in osmand+ is applied directly to live data only.


> What device, version and type of terrain is this in?
> Same as #1037 ?

correct.

**Comment by sp4rkie** [comment]
probably a filter/ GPS accuracy  issue. For the time being I close this...

**Comment by gerhardol** [comment]
I recorded with OsmAnd and RU today and OsmAnd had a number of incorrect deviations, so it is not always better. But Fused location could be an option in RU (I thought there was billing though...)

I assume this is due Fused location in OsmAnd. I do not see a difference for OsmAnd+ vs OsmAnd, if I interpret the source code.

Fused location is an option in RU too, but this requires an update of GooglePlay services (GMS) (the API page notes that a relative new version of GMS is recommended due to bugs). RU only uses GMS for WearOS but the version is very old and some APIs need to be replaced. Someone with a WearOS device will have to rewrite this first.

**Comment by sp4rkie** [comment]
I today run with all filters off (as far as possible from GUI perspective). Red ist RU, blue is osmand+

It appears RU reacts more quickly in curves. osmand+ mostly lags a little.

Would be interesting to know what happens if GPS provides 'jumpy' data as encountered in the initial post


![sshot_000](https://user-images.githubusercontent.com/3232165/131841500-c0005988-1905-4b93-b4f6-c8f28acdd439.jpg)
![sshot_001](https://user-images.githubusercontent.com/3232165/131841505-951b0d19-9126-4e35-bda2-127f54aae4d1.jpg)
![sshot_002](https://user-images.githubusercontent.com/3232165/131841506-c8395203-1f4f-4779-956b-af038fa047fb.jpg)
![sshot_003](https://user-images.githubusercontent.com/3232165/131841509-c3f3d339-20c6-4d88-8124-86a79d7c33c5.jpg)

**Comment by gerhardol** [comment]
> I today run with all filters off (as far as possible from GUI perspective). Red ist RU, blue is osmand+

I believe the Kalman filter is only for smoothing the compass, not for the GPS points.
(The only usage I see in the code at least).

> It appears RU reacts more quickly in curves. osmand+ mostly lags a little.

Expected, Fusion is also a type of filter, it will smooth the data.
