### ISSUE TITLE
HR diagram in sensor settings is behaving weird 

### ISSUE THREAD

**Issue by Uatschitchun** [jonasoreland/runnerup#1041]
Attached you'll find 3 screenshots from HR setup screen.. The graph that's showing when connected to a sensor is completely off.
There's a 0m marker line (sometimes) and I guess here's where the actual plotting takes place? So left of the marker line is future and right off is the past?
The scale on the x axis is wrong. Is it probably seconds?
The graph updates quite irregular only and never corresponda to what's actually measured!? 
![Screenshot_20210924_141933_org runnerup](https://user-images.githubusercontent.com/25088926/134679504-02ee1bf0-5a1c-4438-b544-f3c38c92c10e.jpg)
![Screenshot_20210924_142411_org runnerup](https://user-images.githubusercontent.com/25088926/134679515-f81c008c-0ad1-4d88-a89f-b3e84f1f259f.jpg)
![Screenshot_20210924_144458_org runnerup](https://user-images.githubusercontent.com/25088926/134679527-8edc0b85-af13-409f-9da2-0af98fdda550.jpg)

**Comment by gerhardol** [comment]
> 
> 
> There's a 0m marker line (sometimes) and I guess here's where the actual plotting takes place? So left of the marker line is future and right off is the past?
> The scale on the x axis is wrong. Is it probably seconds?

Yes (actually presented as distance...)

> The graph updates quite irregular only and never corresponda to what's actually measured!?

The graphView to display the data behaved a little irratic. But it seem possible to force the viewed area to improve that the graph is updated.
Just took my entire Friday evening...

To be fixed in next update.

**Comment by Uatschitchun** [comment]
Thx, I'll report back
