### ISSUE TITLE
Nordic Semiconductor Heartsensor?

### ISSUE THREAD

**Issue by sdebaerd** [jonasoreland/runnerup#1066]
Hi

Would it be possible to support Nordic Semiconductor Heartrate sensor?
It's a BLE sensor (NRF), with a public service and method for reading the heartrate.

Service:
UUID: 0x180D

Method:
UUID: 0x2A37
Properties NOTIFY

This would provide a huge list of cheaper smartware as additional devices and as end result more users.

Thanks in advance
Keep it up!

Kind regards

**Comment by sdebaerd** [comment]
I have it working.
Just as what I was thinking, the Huawei pattern was blocking my device to be appearing in the result.

I have it working with this, however there are a lot more of these devices, I have a list of 10 to 15 devices, so it's a bit strange to hardcode this.

static final Pattern huamiPattern = Pattern.compile("(Amazfit +Bip|Mi +.*Band|FC EXPLORE_LE)");

Was there a reason, there was a filter on huawei only?

Thanks in advance

**Comment by sdebaerd** [comment]
"PACIFIC 2_LE";
"G-Smart Sprint_LE";
"SW36_LE";
"WatchM1S_LE";
"M1_LE";
"R2_LE";
"R2J_LE";
"R2N_LE";
"WP5_LE";
"R2_JAPAN_LE";
"SMA-R2_LE";
"M4A_LE";
"M4S_LE";
"LOK01_LE";
"FIT W1_LE";
"GT04_LE";
"M4_LE";
"TK05_LE";
"TK04_LE";
"FC EXPLORE_LE";
"GarettMulti4_LE";
"M5S_LE";
"M5_LE";
"SMA-M5_LE";
"M6S_LE";
"M6_LE";
"M7S_LE";
"M7_LE";
"OV-Touch 2.6_LE";
"GT01_LE";
"SMA-M4_LE";
"SW302_LE";
"UP! Smart Connect_LE";

**Comment by sdebaerd** [comment]
Final remark: mapbox is a pain in the *beep* to add through gradle

**Comment by sdebaerd** [comment]
Also found out how I can send alert messages to my watch over BLE, so will be looking to that part as well, as I want to be alerted if go in a higher zone than configured in RunnerUp, besides an audio cue. The alert message triggers a vibration on the watch, but allows to continue tracking, so that would be a better user experience.

Other thing I have in mind is to load Fit files and setup the interval, based on that, instead of manually configuring it manually: Yes, I'm lazy.

**Comment by gerhardol** [comment]
> Just as what I was thinking, the Huawei pattern was blocking my device to be appearing in the result.
> Was there a reason, there was a filter on huawei only?

I guess that was what was needed to get the device working...
I did some kind of test myself I believe, cannot test myself right now as my BLE band stopped working.
If you have a fix before Monday I will try to make a release, as Android 11 must be targeted on Monday and that makes it more difficult to set GPS always on.
(But there will be releases soon enough anyway when I get to tune the existing PRs).

> Also found out how I can send alert messages to my watch over BLE, so will be looking to that part as well, as I want to be alerted if go in a higher zone than configured in RunnerUp, besides an audio cue. The alert message triggers a vibration on the watch, but allows to continue tracking, so that would be a better user experience.

If that is general thing, it could be added to sound notifications, that should be notifications including toasts and notifications and allow multiple notifications in one workout.

**Comment by sv2ramanan** [comment]
I wrote the small mod to get the huami(amazfit) watches working when paired. I put in only the watches that I had (Bip and Mi band) as I didnt want to put in others without testing. My apologies, I should have monitored the thread and replied before.

**Comment by sdebaerd** [comment]
No worries, it was fun to debug. It has been a while.

**Comment by sdebaerd** [comment]
About my comment about the alerts. It is indeed better to have a regular android notification, as this can be configured to be pushed towards the watch, which also triggers the vibration, no need to do crazy BLE developments.

**Comment by sdebaerd** [comment]
Created a patch and pull request.

**Comment by gerhardol** [comment]
Changed in #1068
