### ISSUE TITLE
An error interface will appear and disappear immediately when the network fluctuates

### ISSUE THREAD

**Issue by sjl872964789** [jonasoreland/runnerup#1082]
**Describe the bug**
When the network fluctuates, an error interface will appear and disappear immediately

**To Reproduce**
1. Install runnerup and open app
2. Click the third icon in the menu bar below
3. Turn off the network
4. Click "Dropbox"
5. An error interface appears and disappears quickly

**Expected behavior**
Users should be reminded that the network is not very good

**Smartphone (please complete the following information):**
 - Device: HUAWEI nova 5 pro
 - OS: EMUI 9.1.1
 - Version: v2.4.4.0

**Additional context**
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/15941953/145820829-50d1ffc4-874d-4c95-a404-acdfbf691e68.gif)

**Comment by afreakyelf** [comment]
Hi Can you please close the issue since I have fixed it. Need to show as proof for assignment submission.

**Comment by gerhardol** [comment]
Thanks!
Hint is to use "fixes #issue" in the PR, then it closes automatically.
