### ISSUE TITLE
Why is MalinEwerlov called like that ?

### ISSUE THREAD

**Issue by ebanDev** [jonasoreland/runnerup#1087]
Hey ! 
I'm wondering, why is the MalinEwerlov training called like that ? 🤔

**Comment by gerhardol** [comment]
Malin Ewerlöf is a Swedish middle distance runner 
https://en.wikipedia.org/wiki/Malin_Ewerl%C3%B6f-Krepp

I guess she has described this interval, I have not seen references to it though.
It was Jonas that added the workout.

**Comment by ebanDev** [comment]
I asked the question cause I have not seen references, neither 😅. So “Ewerlov” is a typo ? 😅 (btw, thanks for this wonderful app :DD)

**Comment by gerhardol** [comment]
Ending with v or f is just alternatively way to spell. (officially changed 1906, remains in names https://sv.wikipedia.org/wiki/Stavningsreformen_1906).
The umlauts were just dropped.
