### ISSUE TITLE
Suppress "RunnerUp" top banner

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#109]
Hello,

I'm thinking about a lot of small GUI improvement which could improve user experience. 

First I feel like the top banner (with RunnerUp written inside) is not really necessary and waste some space on small screens
I propose to remove it, and if you think that people need an indication of which app there are in, to put the RunnerUp logo above « Start », in place of the running guy logo.

What do you think about that ?

**Comment by jonasoreland** [comment]
i have now removed it...and added the legacy menu button.

agree that it would be nice to find better place for menu, and that along tabs sounds like a good idea.
but i'll close this bug issue regardless, the top banner is now gone...(pending next release)
