### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [jonasoreland/runnerup#1095]
Hi Team

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are
the scan results. I found the following:
- 6 data types  
- 0 SDK.

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄

![image](https://user-images.githubusercontent.com/87804852/157150453-a8695f6d-6f5c-4131-9505-7fe51be3d4dd.png)
![image](https://user-images.githubusercontent.com/87804852/157163197-b70ab5f2-51c6-4871-816b-256d54f02dc6.png)

**Comment by gerhardol** [comment]
Thanks for the tool, it helped me with understanding when filling in the report.
I ended up not using the generated report, as I could not uncheck _Device or other IDs_ from the report.

**Comment by vaibhavantil1** [comment]
Thanks for your feedback and trying out the tool. You can uncheck a data element by marking it False positive, we will incorporate your point as well in UI.
