### ISSUE TITLE
Runkeeper Feed

### ISSUE THREAD

**Issue by ocke** [jonasoreland/runnerup#1120]
When adding a new feed for RunKeeper I get a quick "loading" popup, and then a blank page. I reinstalled the app, but it stays white. Also checked my permissions, but it has all the permissions.

1) In the app select the third option from the bottom menu bar: Feed.
2) Click "Edit accounts".
3) Select "Runkeeper".
4) ...
5) Blank page?!

I think Runkeeper might have changed something on their end. Thanks!

**Comment by gerhardol** [comment]
RunKeeper has removed the download feature.
Actually, they have officially removed support for the open api they provided also for uploading, but not removed access for existing customers yet. 

There are no services that allow download service any more, so this feature in the app will unfortunately be removed.

**Comment by ocke** [comment]
Thanks for letting me know!
