### ISSUE TITLE
Wrong date on Galaxy S6

### ISSUE THREAD

**Issue by Jbb2811** [jonasoreland/runnerup#1121]
Hi,
I am using runnerup on my old Samsung Galaxy S6.
It is really a nice app, but since the beginning of September I have wrong dates in tcx files:
*  file name is correct ( for ex : 13 sept 2022 )
*  track points date are not correct  ( 28 jan 2003 )
The difference between the two dates is 7168 days which is 7*1024 which match with gps week number rollover.
https://en.wikipedia.org/wiki/GPS_week_number_rollover ( despite last rollover occurred in 2019 not sept 2022).
This could be related to:
https://www.androidpolice.com/samsung-s7-edge-s8-update-gps/
but my S6 didn't get any update.

It could be easily fixed in the code.

Thanks, 

![Capture d’écran_2022-09-14_22-20-33](https://user-images.githubusercontent.com/113554312/190254545-fd2b5250-26ba-4bef-adcf-b20202d53000.png)

**Comment by gerhardol** [comment]
> It could be easily fixed in the code.

What did you have in mind?
If time is before 2022, add certain time?
How much exactly?
How to ensure the bad time is not another issue?

**Comment by Jbb2811** [comment]
I thought something like:

1. if (gpstime - systemtime) ~= 7168 days: add 7168 days to gps time
2. if gpstime < 6april2019 :  add 7168 days to gps time ( 6april2019 = last GPS week rollover)
or simplier and safer:
3. add an setting option : "use system time instead of GPS Time (can fix some old GPS issues)"

Anyway, not many of RunnerUp users should still have a Galaxy S6, and I won't keep mine for years.
I may be the only one having this problem. So don't waste to much time on it until others users claim for it.

**Comment by manualbashing** [comment]
I am seeing what I take to be the same issue on my Galaxy S20. Since August all timestamps for my tracked activities are set to January 2003:

![image](https://user-images.githubusercontent.com/5665209/191060609-2f952e32-efd6-46ed-84ca-9e5a60dfa42b.png)

**Comment by gerhardol** [comment]
An S20 with bad firmware too...
With the number of S20 Samsung has produced they should have some quality control...

The solution is probably regardless to use the system time instead of the GPS time, with a setting (maybe default).

**Comment by rivdsl** [comment]
Just want to add that I am also experiencing this with Galaxy S7. A workaround with a feasibility check using system time would be appreciated.

**Comment by gerhardol** [comment]
Plan to chang this in #1114

**Comment by zarandya** [comment]
I'm also impacted by this and I have a modern device, and not a Samsung. It was still correct in last September but since the start of 2023 I'm also getting incorrect timestamps in TCX files. The time difference is the same, 7168 days. 

Also impacts Strava uploads.

**Comment by rivdsl** [comment]
I am still having the same issue in v2.5.2.0. The option "Time from GPS points" is turned off.

**Comment by berdosi** [comment]
I had this issue before, and now I'm having it again - mine is a Fairphone, and the issue is likely with their GPS receiver:
[GPSTest](https://f-droid.org/en/packages/com.android.gpstest.osmdroid/) also shows the date to be off by 7*1024 days.

It seems to be related to how GPS handles transmits time: as the number of the week since 1980, and the number of seconds in the week. However, the number of the week is stored as a 10 bit number, so it has already overflown, twice.
It is probably the task of the OS to apply the correct offset to get the correct date.
https://wheelercat.com/gps-1024-explained/

**Comment by gerhardol** [comment]
If _Time from GPS points_ is not set, the time should be overridden.

While I have no phone with this behavior, I have tried to simulate it. The setting worked for me, but a real life scenario could be different. I do not see any obvious issues in the code.
However, I am currently removing support for Android before 5.0, as this release is no longer available in Play (f-droid version had to update even before). With this some strange workarounds (from before I was involved) can be removed, the logic is cleaner. In best case, this is added as a Play beta (2.6.0 or so) in some days.
If it still does not work with the update, there is something else with the Android versions. (Later.)

**Comment by berdosi** [comment]
> If _Time from GPS points_ is not set, the time should be overridden.

This setting doesn't appear to work for me: I set my phone's clock back by 1 hour, but despite the above being unchecked, the TCX file contains the "correct" time (presumably from GPS).

(Android 12, RunnerUp v2.5.2.0 (F-Droid))

**Comment by gerhardol** [comment]
#1156 has a fix
