### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [jonasoreland/runnerup#1129]
ref: https://github.com/jonasoreland/runnerup/pull/1063

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3737884838#L504

/LE: FYI https://gitlab.com/fdroid/fdroiddata/-/commit/00dd899901edf429bbad04de44451b325a68826e

**Comment by licaon-kter** [comment]
You've bumped versionName but forgot versionCode: https://gitlab.com/fdroid/fdroiddata/-/commit/f8f3e9b623e377447200a0c3f77429f65ab82c85

I've updated the recipe since autoupdate did not picked it up (same version means no new version): https://gitlab.com/fdroid/fdroiddata/-/commit/f8f3e9b623e377447200a0c3f77429f65ab82c85

thanks

**Comment by licaon-kter** [comment]
Can you reopen?


`hrdevice` depends on ANT+ which is [not FOSS](https://github.com/jonasoreland/runnerup/issues/662), right?

I can't just delete its folder
```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportLatestRelease'.
> Could not resolve all task dependencies for configuration ':app:latestReleaseRuntimeClasspath'.
   > Could not resolve project :hrdevice.
     Required by:
         project :app
      > No matching configuration of project :hrdevice was found. The consumer was configured to find a runtime of a component, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'com.android.build.api.attributes.ProductFlavor:all' with value 'latest', attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '7.4.1' but:
          - None of the consumable configurations have attributes.
```

**Comment by gerhardol** [comment]
When building org.runnerup.free ANT+ lib is not used, so deletion should not be necessary.

**Comment by gerhardol** [comment]
> You've bumped versionName but forgot versionCode: https://gitlab.com/fdroid/fdroiddata/-/commit/f8f3e9b623e377447200a0c3f77429f65ab82c85

I did not expect that was needed as the previous code should not have been used.

**Comment by licaon-kter** [comment]
There's no `free` flavor for a while now, only `latest`, not sure what I'm doing wrong :)

**Comment by gerhardol** [comment]
> There's no `free` flavor for a while now, only `latest`, not sure what I'm doing wrong :)

There has never been any "free" flavor. Before 2.0, the application id were the same in Play and F-Droid.
The check for free, F-Droid has always removed wear:
`allowNonFree = !project.hasProperty('org.runnerup.free') && rootProject.file("wear").exists()`
(renaming play-services etc is not needed, I guess it is done for safety)

F-Droid builds had obviously not been tested after fixing ANT+ in Play, some potential to work better now...
Need to setup builds again to replace Travis.

**Comment by gerhardol** [comment]
https://gitlab.com/fdroid/fdroiddata/-/jobs/3785454514

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/commit/6cd4f33d61e7e24a38d14a0041803715887e093b
