### ISSUE TITLE
Stopping cycling because of a pause

### ISSUE THREAD

**Issue by guglovich** [jonasoreland/runnerup#1144]
Cycling stops when you press pause manually. This may also be the case when auto-pausing. Because the first workout ended on its own. 
Noted on the latest version. On the penultimate version I did not start velocycling.

[screen-20230410-212823.webm](https://user-images.githubusercontent.com/54148165/230968679-db40648b-fbb4-4a5c-810b-d0b1819a9937.webm)

**Comment by guglovich** [comment]
The latest version works.

**Comment by gerhardol** [comment]
I failed to understand the description what was the problem....

The latest release fixes a problem with the step sensor for running cadence when disabled, seem to have affected Cycling too.
