### ISSUE TITLE
probably webdav issues

### ISSUE THREAD

**Issue by tempuser779y** [jonasoreland/runnerup#1147]
I'm trying to create a backup account using webdav functionality. If webdav URI includes ".local" zone, when I press OK an account is not added. As I see, in this case it's not trying to resolve a domain name via dns. With another root zone it works normally. In other apps on the same device this webdav URL works normally.

**Comment by tempuser779y** [comment]
probably this is in local infrastructure. I'm not sure yet.

**Comment by gerhardol** [comment]
I do not know how to investigate, not too familiar with the protocal webdav uses.

**Comment by tempuser779y** [comment]
well, I'm not an IT professional at all, but after some searches through the internet, I intuitively suppose the ssl library used by the app does not have access to the manually installed root ca.crt in to android device
