### ISSUE TITLE
feature request: gps disabled mode

### ISSUE THREAD

**Issue by nutpantz** [jonasoreland/runnerup#1150]
During bad weather i workout inside, but would still like to track the workout by time and heart rate (and eventually any other supported tools).
If would be nice is there was a way to disable gps mode and just record the workout..

Maybe i missed the option in the manual.

**Comment by gerhardol** [comment]
GPS is currently required. 
Duplicate of https://github.com/jonasoreland/runnerup/issues/1113 (and more)
See https://github.com/jonasoreland/runnerup/issues/1113#issuecomment-1149964200
