### ISSUE TITLE
Importing GPX Workouts

### ISSUE THREAD

**Issue by snooppr** [jonasoreland/runnerup#1151]
Hi, was looking for a replacement for proprietary sports trackers.  Found RunnerUp.

I could not evaluate its functionality because I could not find the seemingly obvious essence: training.gpx import.  It seems that I have looked through all the settings and help, but I did not find it.  Does such a long-standing development of the application have no gpx import function?

Just in case, a rationale for why imports are needed.  The user writes track.gpx in OsmAnd, or Sports Tracker, or Open Source logger, or TomTom sports watch... how can he upload the recorded track to RunnerUp?!  No way.

Unfortunately, after installing the tracker, I could not even rate the application, I deleted it.  The mass user thinks the same way. 
 Feature Request: Add import/open file.gpx

**Comment by gerhardol** [comment]
RunnerUp is currently primarily a recorder, like the apps you mention. It has quite few features for analyzing data, just as the apps you mention, where most also do not have gpx importers.
Sure, that could be implemented, but I am not an GUI designer and do not use the app in this way (I primarily use a PC program). Map data is limited, with more users there would be a cost.
Contributions are welcome.

But there will always be features missing that commercial apps can offer for training analysis etc.

Also, it is more difficult writing an importer than it is to write an exporter. Just .gpx time and position is fine, but there are no standard for other fitness data like hr, cadence, laps. That must basically be adopted to each exporter (just how RU has adjusted exporters to other bigger apps).
A format like .tcx has standardized such data, but there are multiple ways to interpret the standard...
