### ISSUE TITLE
Cant resume stopped activity

### ISSUE THREAD

**Issue by TheFellowJasper** [jonasoreland/runnerup#1152]
Basically, If I stop activity (for the most part due to missclick) and then click resume on summary screen, app will go to tracking screen only to return to summary second later, and It keeps happening no matter how many times I click resume.

I'm using this app on Realme 8 running Android 12

**Comment by gerhardol** [comment]
It seems like you have autopause activated

**Comment by TheFellowJasper** [comment]
You're right, I do have it enabled, weird that it behaves like that with it enabled but atleast I know how to fix it, thank you
