### ISSUE TITLE
Can't start workout

### ISSUE THREAD

**Issue by dkbarn** [jonasoreland/runnerup#1154]
https://github.com/jonasoreland/runnerup/assets/23280179/7a6f22f3-c772-4ef2-beb1-29246322b50f

I have a Google Pixel 5 with Android 13.

How are you supposed to begin a new activity? All I see is a "Start GPS" button but this always takes me into the app setting to enable background battery usage, which is already enabled. Also all necessary permissions have already been granted. But I cannot bypass this prompt. Am I just not understanding the UI? Is there another way to begin an activity?

Note that I don't actually care about GPS, the only audio cues I have enabled are my current heart rate, I don't need anything that requires location data.

**Comment by dkbarn** [comment]
I've figured it out. I had to go into Permissions > Location, and ensure that it was set to be enabled all the time.

**Comment by gerhardol** [comment]
GPS is the trigger to get dat. Without "always" the collection will be stopped by Android, so the slightly annoying check was added after a number of issues was raised (just information in the popup was not enough).
