### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [jonasoreland/runnerup#1157]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4787591260#L587

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/f9511a27715f24ad6f81ca2dd42da8c8fa6efb9f

**Comment by gerhardol** [comment]
Java17 needed, pr for f-droid-data needed

**Comment by gerhardol** [comment]
Also #1159, https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13488/diffs
