### ISSUE TITLE
Translation: how to become a reviewer?

### ISSUE THREAD

**Issue by rodolforg** [jonasoreland/runnerup#1181]
Official releases of RunnerUp mobile app only uses reviewed translation strings.

Regarding Portuguese (Brazil), there are a lot of not-reviewed strings for years. Many visible strings are untranslated or mistranslated with review pending.

AFAIK, Transifex does not have a way to request to become a reviewer, so I'm asking here to become one for pt_BR locale, as it's my native language and I'm good on it :) Sorry if it isn't the correct way to do it.

**Comment by gerhardol** [comment]
Added you as a reviewer.
I do not know any better way than asking here.
