### ISSUE TITLE
Version 2.7.0.0 Changed the language of the app from English to Dutch

### ISSUE THREAD

**Issue by jadegamesuk** [jonasoreland/runnerup#1187]
Really odd one here. Yesterday I upgraded my Runnerup app in F-Droid from 2.6.0.2 to 2.7.00. The previous setting had the app in English. After the update the language has changed to Dutch (as far as I can tell) I was wondering if this could be investigated. 

![image](https://github.com/jonasoreland/runnerup/assets/39485724/0d8042d5-0f3f-4491-8cc9-ada2e119b8ce)
![image](https://github.com/jonasoreland/runnerup/assets/39485724/39b9ea26-f924-4c1f-8ed5-9b038a99b44b)
![image](https://github.com/jonasoreland/runnerup/assets/39485724/a97ae791-2d29-46e1-85e0-60bfdfffa5a9)
![image](https://github.com/jonasoreland/runnerup/assets/39485724/4415ab44-e51f-4a16-b7c5-2e83b2a70094)

**Comment by gerhardol** [comment]
Will change in #1186. This is something with targeting Android 14 so the weird en-NL locale (added before I was involved) is preferred over the default en-US locale.

and F-droid releases must be changed somehow, not using all labels in GitHub. 2.7.0.0 is a pre release that happen tov trigger a F-Droid release. I am surprised it built at the first attempt, there are normally several iterations needed before F-Droid builds...
