### ISSUE TITLE
Notification action buttons not working on Android 14

### ISSUE THREAD

**Issue by roberi** [jonasoreland/runnerup#1189]
Action buttons in the notifications, like the ones in the picture below, seems not to be working on Android 14.

![image](https://github.com/jonasoreland/runnerup/assets/10847866/00259526-e1ad-4726-985e-6514b8f05815)

At least not for me on my Pixel 6 running Android 14. They work when I test in Android Studio on an AVD running Android 13.

App version 2.7.0.1

**Comment by gerhardol** [comment]
Same for my OnePlus 8T with Android 14. It may have occurred prior to A14 too, or just in the lock screen.
