### ISSUE TITLE
unable to upload missing workouts from file

### ISSUE THREAD

**Issue by sjacobsson** [jonasoreland/runnerup#1195]
I copied some workouts as .gpx and .tcx files from a backup to the RunnerUp directory that my RunnerUp app is connected to, but when I select Upload, it cannot see those workouts. It can however see other workouts that I create in the app.

I checked with ls -l in termux that the files have the exact same owner and permissions. I also tried uninstalling and reinstalling the app but the problem persists. I also tried importing the workouts from strava but had the same problem.

The app is installed via FDroid.

These are my specs:
RunnerUp version 2.7.0.1
Samsung model SM-G960F
Android 13, LineageOS version 20-20240902-microG-starlte

**Comment by sjacobsson** [comment]
For me, the problem is reproduced by
- disconnecting File Upload
- uninstalling app
- reinstalling app
- connecting File Upload

**Comment by gerhardol** [comment]
The activities must be in the database to be known to the app, stored in a .sqlite database. There is no way to import activities 

It is possible to import workouts, by opening the .json files in the app.

**Comment by sjacobsson** [comment]
Oh, I see. Thanks for explaining!
