### ISSUE TITLE
Beta Tester Version 

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#1197]
I'm a Beta Tester in Google Play. I'm apparently up to date on 2.7.0.1
I see 2.8.0.0 is now being released. Will the Beta version update automatically as part of the rollout?
Thanks

**Comment by gerhardol** [comment]
The version will need a review by Google first, may require up to a week. Will promote to release when there are a number of beta downloaded and not knew crashes or negative feedback.
But the .apk on GH is the same.

**Comment by Cagier** [comment]
Ok, that's great. That's for the day reply! Keep up the great work.
