### ISSUE TITLE
app wont turn on gps even though all permissions are allowed

### ISSUE THREAD

**Issue by maxwell-gisborne** [jonasoreland/runnerup#1202]
Apon pressinc the gps button on the main screen, I get a pop up telling me to enable permissions and disable battery optimisation. I do this but the popup remains.

See screenshots attatched 
![Screenshot_20241012-075013](https://github.com/user-attachments/assets/11c4043e-845b-4d1f-a358-8b6df640ee7e)
![Screenshot_20241012-075004](https://github.com/user-attachments/assets/b7ec3f8d-9831-4888-a6cb-198132fff511)
![Screenshot_20241012-074959](https://github.com/user-attachments/assets/e2bfcf92-9257-47da-abcd-0606da512247)

**Comment by gerhardol** [comment]
As the popup suggests, go to location and change location to all the time.
Otherwise the phone may remove gps during an activity.

The popup should probably be split and just warn about this.

**Comment by maxwell-gisborne** [comment]
Okay my bad
