### ISSUE TITLE
[Question] Corners are cut on a tight loop

### ISSUE THREAD

**Issue by GlowingScrewdriver** [jonasoreland/runnerup#1204]
I've been using RunnerUp for a couple of weeks now, and it's a really nice app! Nice change from the bloat of proprietary alternatives.

Sometimes I run a rectangular, 1.2-km loop. Every time I run this loop, the total distance measured is significantly deflated -- for example, most recently it reported a run as 9.2 km instead of 10 km -- verified against both Google Earth and Strava. I can confirm that measurement is much more accurate on another loop with no such tight corners.

GPS accuracy seems fine. On examining the map, I notice that every point of the path is a point I actually crossed, and the path lines up nicely on the straight stretches; however, the path cuts across the corners of the loop.

I did try changing the "Recording distance interval" to "2 m between recorded locations", but it did not help. Is there another setting that could affect this? Or could there an underlying bug (either elsewhere or in RunnerUp itself)?

**Comment by gerhardol** [comment]
The app has time resolution of 1s, most Android phones will deliver updates at a slower rate though. I suggest that you set the min time to 1s, maybe decreasing to 0.5s to really get all updates.
The app has no filter by default, path simplification could be applied though.

In general, the GPS track would be truer if the min time/distance were handled as OR, to filter standstill better. As they are handled as AND, there will be no updates when standing still now.
Corners is a special case that most filters will smooth.

**Comment by GlowingScrewdriver** [comment]
Alright. Thanks!
