### ISSUE TITLE
activity upload deselection

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#130]
When selecting which sites to upload to after an activity, after the last selected item is deselected, all boxes become ticked in the gui, though they do not upload. This is weird behavior that should be fixed.

I'm planning on taking a look at it today or tomorrow.

**Comment by jonasoreland** [comment]
i think it's fixed.
reopen if you disagree

**Comment by dhiltonp** [comment]
confirmed as fixed
