### ISSUE TITLE
Capitalization

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#133]
With translations added we now need to think about capitalizations.
Should we have strings names e.g Time/time for with/without capitalization
or should we do something else ? and what would that be ??

**Comment by bagage** [comment]
Concerning this and my failed PR from Friday, would you prefer:

- one commit per ID change OR
- one big-commit for everything?

**Comment by jonasoreland** [comment]
i actually never saw "anything",

is it lots of changes ?
are they trivial ?

i.e don't know :(

/Jonas

**Comment by bagage** [comment]
They are quite trivial yes. Please look at [this](https://github.com/bagage/runnerup/commit/53f949431db32858b742ef2bc9dda84611ddebb4) for instance, or globally [here](https://github.com/bagage/runnerup/commits/master).

**Comment by jonasoreland** [comment]
one PR is fine i think

**Comment by gerhardol** [comment]
Closing this discussion. RU is not too inconsidtent...
