### ISSUE TITLE
runtastic import errors

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#138]
Some runtastic uploads are not working so well: https://www.dropbox.com/s/o0i01y31ggoscc5/Screenshot%202014-11-26%2010.33.16.png?dl=0

When I click on the error, I get this message:

```
"There are various possibilities why your data import could not be completed:

Your file is missing location or time data and no sport activity can be generated from it.
The data of your file is malformed and does not match the specification for the filetype.
The uploaded file is not a valid TCX or GPX file."
```

I'm going to talk to their support to try to get a better idea of what's going on.

**Comment by gerhardol** [comment]
Runtastic sync will be hidden/disabled in a future release with #590
