### ISSUE TITLE
extended menu ("...") is not available

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#141]
Haven't looked into it, but in the latest build that I uploaded... 2 days ago, I think, activities cannot be edited. The "..." on the right-hand side does not show up.

**Comment by jonasoreland** [comment]
I added it to all activities that have menus.
https://github.com/jonasoreland/runnerup/commit/20b48c4d968f0d1639971ccb0f90330cedcb0b5a

ok to close ?

/Jonas

**Comment by dhiltonp** [comment]
Tested, looks good.

Closing.

**Comment by dhiltonp** [comment]
Apparently this fix doesn't work on 5.0

**Comment by twitwi** [comment]
I can confirm that the extended menu is *not* showing up on my nexus 4, android 5.1.1. (still, what I can see of the app is already amazing :+1 )

**Comment by twitwi** [comment]
I guess the proper issue is #298 (where there is a direction for a solution).

**Comment by jonasoreland** [comment]
fixed in #298
