### ISSUE TITLE
antpluginlib has been updated to 3.3.0-RC1 - this breaks current builds

### ISSUE THREAD

**Issue by shatteringlass** [jonasoreland/runnerup#156]
Editing app/build.gradle like this gives a working build  

```java
[...]
    compile files('libs/antpluginlib_3-3-0-RC1.jar')
[...]
task downloadAntPluginLib(type: DownloadTask) {
    sourceUrl = 'https://github.com/ant-wireless/ANT-Android-SDKs/raw/master/ANT%2B_Android_SDK/API/antpluginlib_3-3-0-RC1.jar'
    target = file('libs/antpluginlib_3-3-0-RC1.jar')
}
```

**Comment by jonasoreland** [comment]
can't you make a PR instead ?

**Comment by shatteringlass** [comment]
Done. But as I say in the PR message, this isn't a fix, it's a workaround.

**Comment by jonasoreland** [comment]
what is your suggested fix ? (that is not a workaround)

/Jonas

**Comment by shatteringlass** [comment]
I am not a developer nor a git expert, but I think regexes could come up useful when trying to get the latest version of antpluginlib_3*.jar. Maybe this could be done with post-commit script hooks, or something more elegant, if worth it. I'm afraid I'm not the most useful guy when it comes to this.

**Comment by jonasoreland** [comment]
how about that submodule thing,
how do you do that ?

/Jonas

**Comment by shatteringlass** [comment]
Actually, I'm clueless. I guess one adds the submodule and then needs a script which updates either build.gradle automatically to point to the latest version of the submodule, or corrects a symlink to point to the latest release, and use the symlink (whose name will never change) in build.gradle (obviously this second way needs a script for symlink renewal too).

**Comment by jonasoreland** [comment]
i made ANT+ into submodule.
i think i got it right.
please test, and close this issue if it works for you.
/Jonas

**Comment by shatteringlass** [comment]
Well done, as expected.

**Comment by dhiltonp** [comment]
So, I cloned the ANT repo (listed in the .gitignore) from the runnerup dir, and now I have stuff in the ANT-Android-SDKs directory, but I'm getting build errors; 

    import com.dsi.ant.plugins.antplus.pcc.AntPlusHeartRatePcc;

dsi is apparently not resolving. How did you resolve this issue (if you saw it)?

**Comment by jonasoreland** [comment]
you should do "git submodule init && git submodule update" to get correct
version of ANT repo...

/Jonas

**Comment by dhiltonp** [comment]
Ah, that did it.
