### ISSUE TITLE
Integration with google fit?

### ISSUE THREAD

**Issue by j-xella** [jonasoreland/runnerup#158]

**Comment by jonasoreland** [comment]
patches accepted!

**Comment by paradix** [comment]
I'll take a look at this one

**Comment by paradix** [comment]
Do you prefer using the REST API or the Fitness API? 
But I think the Fitness API requires that the app is registered and have the API enabled.

**Comment by jonasoreland** [comment]
1) i prefer REST (since all of the other integration is made that way).

2) i think i need to register the app anyway...do you know where the page
is ?

there will most likely be a app id/app secret that one get...
and these i have encrypted/obfuscated for other uploaders
and give them in the constructor...

/Jonas

**Comment by paradix** [comment]
I think you will find all info here https://developers.google.com/fit/android/get-started

**Comment by jonasoreland** [comment]
hmm...enabled fitness api.
what do I need to do more ?


/Jonas

**Comment by paradix** [comment]
Give me some time, I need to figure this out :) and will let you know if it works.

**Comment by jonasoreland** [comment]
what is your private email, and I can mail you oauth2 info...(suitable for
REST)

/Jonas

**Comment by KaptenJansson** [comment]
As a workaround, use a tracker like Runkeeper as a proxy (it has Google fit integration).

**Comment by paradix** [comment]
Hi Jonas,
I already did the part with the refresh token, so authorization works fine.
But I have a problem with creating data sources that are needed for google fit to work.
Somehow the POST request gives me a 400 response and I can't get it to work.
Maybe you could have a look at my branch at commit a01cdead57a5f94dba5719b49338d03bab0d103c

**Comment by paradix** [comment]
seems my json is malformed, don't waste your time for now :)

**Comment by paradix** [comment]
I'm pretty much done with the coding, except one thing.
The HttpURLConnection doesn't  support the PATCH request.
Do you have any idea how this can be done?

**Comment by jonasoreland** [comment]
have you tried

X-HTTP-Method-Override: PATCH

http://stackoverflow.com/questions/19797842/patch-request-android-volley

**Comment by paradix** [comment]
Great this worked, but still getting a bad request on the POST and the response doesn't help much.

**Comment by paradix** [comment]
Could you please email me the "developer project number" just to check if I have the proper one. Because it seams that the number is not being accepted by google api when I try to post the activity.

**Comment by paradix** [comment]
I'm stuck :/
I think that code-wise the google fit uploader to 90% ready/working and can be tested, but.
There is a big BUT. Posting the activity data isn't working and I can't find the cause for this.

Upon the POST of the data points I get a 400 response with the following message 

{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidArgument",
    "message": "DataSourceId in request: derived:com.google.location.sample:<PROJECT_ID>:runnerup_activity_location does not match DataSourceId in Dataset. "
   }
  ],
  "code": 400,
  "message": "DataSourceId in request: derived:com.google.location.sample:<PROJECT_ID>:runnerup_activity_location does not match DataSourceId in Dataset. "
 }
}

I even tried to post the data with googles API-Explorer with the same result --> https://developers.google.com/apis-explorer/#p/fitness/v1/fitness.users.dataSources.datasets.patch

I have been trying different approaches to post the data, but nothing helps.
Maybe someone could review my code, retest it and report back if the same problems occur.

**Comment by paradix** [comment]
Got this one fixed, but next errors are following. I'm on it.

**Comment by jonasoreland** [comment]
released
