### ISSUE TITLE
mile doesn't show fractional components

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#165]
When recording an activity in the imperial system, miles no longer show the fractional component:

3.1 miles = 3 miles
3.9 miles = 3 miles
etc.

This isn't good; I biked 1.6 miles or so, but it was reported as 1 mile (until I stopped the activity, where meters are shown?)

**Comment by paradix** [comment]
Yes, I have noticed this problem too in metric system. Does the cues also miss the fraction?

**Comment by dhiltonp** [comment]
I don't think so, but I'm not sure.

**Comment by paradix** [comment]
I think the Formatter class need fixing in the cueDistance(..) method. 
The double from the round Method is being cast do int and that's why the fraction is missing.

The same happens with the audio cue, where I always get only the amount of kilometres without the fraction.

**Comment by jonasoreland** [comment]
pushed fix
