### ISSUE TITLE
Show heartrate zones distribution based on a setting or always

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#166]
Right now the heart rate zones distribution bar in the DetailActivity view is shown only when the target HRZ in the basic view is set to any value > 0.

Wouldn't it be better to make it visible always or depending on some general user setting and not a current workout activity setting?

**Comment by jonasoreland** [comment]
agree. hadn't noticed.
that is indeed incorrect.

it should be show if HR data is present and HR Zones are set.

patches accepted!

/Jonas

**Comment by paradix** [comment]
Ok. Will gladly do that.

Another feature suggestion regarding the HRZ distribution would be to have an Endomondo-like graph, where each zone is presented as a single bar e.g. horizontal. That way one could show more data like. percentage, time of duration of each zone. What do You think?

**Comment by jonasoreland** [comment]
no real opinion. current bar was a contribution...

if that is something you want (or think others want) go ahead.

/Jonas
