### ISSUE TITLE
Non standard buttons not centered on LG G Watch R

### ISSUE THREAD

**Issue by KaptenJansson** [jonasoreland/runnerup#168]
All non standard buttons on the watch are off center to the right, screenshot below:

https://docs.google.com/file/d/0B71pLQBYIPv-ZF9PdndEdmJWck0/edit?usp=docslist_api

**Comment by KaptenJansson** [comment]
It's still not centered on my watch using the latest 1.40 beta.

**Comment by jonasoreland** [comment]
darn!!

**Comment by jonasoreland** [comment]
update: with latest version of emulator i can finally reproduce this!

**Comment by KaptenJansson** [comment]
Yay! Have you fixed it yet ? ;)

**Comment by jonasoreland** [comment]
no, but maybe during vacation!

/Jonas

**Comment by KaptenJansson** [comment]
That's what vacations are for I guess ;)
