### ISSUE TITLE
unable to register runkeeper credentials

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#171]
I've put in my runkeeper credentials, but after I enter my credentials, the uploader doesn't show up as connected, but runkeeper does say that it has successfully linked with runnerup.

**Comment by jonasoreland** [comment]
Is this a regression? Or

**Comment by dhiltonp** [comment]
Yes, it's a regression, but I haven't done a bisect to find where it was
introduced.

**Comment by jonasoreland** [comment]
Could be them changing their service or you using a different android
version?

**Comment by dhiltonp** [comment]
I'll try to do some further testing.

I suspect that this issue would not affect any current users of the
runkeeper uploaded, but it might affect new users.

This is speculation and needs verification.

**Comment by nebmo** [comment]
I think I had problems with runkeeper 1-2 months ago with a new "user". never figured out why..

**Comment by KaptenJansson** [comment]
I have the same issue, trying to add runkeeper and login in using google sign in results in a blank page.

**Comment by KaptenJansson** [comment]
Using 1.39 beta.

**Comment by paradix** [comment]
There is a NetworkOnMainThreadException thrown while trying to add runkeeper credentials.
I tried changing some code based on this http://www.simpligility.com/2011/01/android-strictmode-for-all-platform-versions/ and the exception stopped.

**Comment by jonasoreland** [comment]
i tested and found this this morning too...
i worked some 5 minutes on a patch (that will not turn off strict mode)
hope to get it ready tonight.

/Jonas

**Comment by paradix** [comment]
Would be probably best to extract some of the code into a AsyncTask to make it work properly.

**Comment by jonasoreland** [comment]
that is what my written but not tested patch does :)

**Comment by paradix** [comment]
Good that I haven't started doing anything more in this matter :)

**Comment by jonasoreland** [comment]
Hi David,

Can you test if my latest changes fixes this problem for you ?

/Jonas

**Comment by dhiltonp** [comment]
It does :)

**Comment by KaptenJansson** [comment]
Works for me too!

**Comment by mwallgren** [comment]
I see this thread is closed, but I have a problem similar to this. 
Trying to connect to RunKeeper using Google-login results in blank page and no connection to RunKeeper:
![screenshot_2015-02-05-09-13-52](https://cloud.githubusercontent.com/assets/10862420/6056933/06a34ee8-ad18-11e4-835a-fe7f4f21b23e.png)

**Comment by mwallgren** [comment]
I run the version available on Play: 1.37. Maybe you're talking about newer versions in this forum? I'm not sure how to get them into my phone...

**Comment by jonasoreland** [comment]
yes, it's a newer beta version.
i.e not released to "public" yet...

you can join https://plus.google.com/u/0/communities/112040124647770742805
to get access these...
but they may include unwanted bugs...

/Jonas
