### ISSUE TITLE
Add support for the SportsTracker v1 HRM

### ISSUE THREAD

**Issue by LenzGr** [jonasoreland/runnerup#174]
Just for tracking purposes (since we already discussed this via email) - it would be nice to have support for the HRM v1 device from SportsTracker. They don't provide any API documentation, but there's a sample application for accessing it here: https://bitbucket.org/ntrp/sports-tracker-hrm-demo

**Comment by vyaslav** [comment]
I have Beurer PM 25. It is a watch(monitor) with analog HR belt which is not designed to sync with phone. Would be nice to add some avg values from watch manually into the runnerUp app.

**Comment by jonasoreland** [comment]
vyaslav please open separate issue for separate issue.
i'll close this one as $SUBJECT is now fixed.
