### ISSUE TITLE
Feature request: Support TrainingPeaks profile

### ISSUE THREAD

**Issue by Mixb** [jonasoreland/runnerup#181]
Is it possible to support TrainingPeaks profile?
1) Supported file formats: http://help.trainingpeaks.com/entries/22525655-Compatible-Device-Files
2) How do uploads files: http://help.trainingpeaks.com/entries/22165005-How-do-I-Upload-a-workout-file-into-TrainingPeaks-or-WKO-

**Comment by gerhardol** [comment]
TrainingPeaks has an API for "approved partners". This means that this is propritary, direct upload from RU will not be approved
https://help.trainingpeaks.com/hc/en-us/articles/234441128-TrainingPeaks-API
