### ISSUE TITLE
Cannot connect with Polar WearLink + Bluetooth ...

### ISSUE THREAD

**Issue by OhCanadaGitHub** [jonasoreland/runnerup#182]
Hej Jonas,

I have issues connecting the Polar WearLink + Bluetooth with the App. It's been already paired with the phone - and it works (only though) with Runtastic Pro.
Anything I might do wrong? [1) Pair via Bluetooth 2) Open Runner Up 3) Setting - Heart Rate 4) Scan - Select Polar WearLink 5) Connect]
Cynogenmod 11 - Screenshot: 
![default](https://cloud.githubusercontent.com/assets/10784269/5987678/fbf65888-a938-11e4-9045-6e5b4f78a879.png)

Best wishes,
Fab

**Comment by mindi-ef** [comment]
Select Bluetooth Smart and not Polar Wearlink. You have to wait a while...Then it shows up the Bluettooth devices. I needed some trials for my Polar H7. But now the connection is stable.

**Comment by jonasoreland** [comment]
working ?
shall this be closed ?

**Comment by OhCanadaGitHub** [comment]
Oh sorry. Please close it. Forgot it.

xx,
Fab.

**Comment by boxemall** [comment]
Sorry to Nero on this thread, but it seems this is the closest I can get. I have a polar wear link as well, and I can't get the phone to pair with it. "Select Bluetooth Smart" is not present when I try to search for it. It may very well be the phone (Bluetooth stack maybe?) that is causing the issue.
To confirm the sensor still works, I paired it with my polar watch, and it immediately paired. HR data seems in sync with my smartwatch as well.
I hope someone will read this. If I can provide more information, just ask away.

Regards

**Comment by gerhardol** [comment]
I have no WearLink device and cannot test it.
Can you build and debug with Android Studio?
Anyway, you should open a new issue about Wearlink.

I have not seen any WearLink devices for quite some time and am not surprised it has stopped working...
The feature is less promoted now.
If it cannot be supported, it should maybe be removed.

**Comment by gerhardol** [comment]
It is unfortunate that also old products require maintenance, many changes in the app are done to satisfy Google and new Android versions. It is hard to fix this without having a device, so it may be hard to fix.

It is not the app to so large extent is the limitation, it is the Bluetooth in the phone vs the HR strap. Most Bluetooth low energy straps from the last years should work (the retailers do not want returned products, so the really bad ones are out of the market).

**Comment by boxemall** [comment]
I'd like to try to build (with some help as I'm not that savvy) but as I
already said (and you too) as well, it's probably the stack against the
strap. Nonetheless I'd like to try just to cancel things out. Sometimes
it's just good to know instead of just assume. :-)

Am 6. April 2023 19:10:57 schrieb Gerhard Olsson ***@***.***>:
