### ISSUE TITLE
runkeeper: successfully uploaded activities not marked as uploaded

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#183]
Pretty much what's on the tin; I just uploaded ~100 activities to runkeeper, 95% successfully uploaded (show up in runkeeper feed), but they are not marked as uploaded in runnerup.

**Comment by jonasoreland** [comment]
hmm...works for me...
do you have a logcat ?
and...android version ?

/Jonas

**Comment by dhiltonp** [comment]
Android version 4.4.2.

My logcat buffer has overflowed from then, but I just created and sent a new activity. It correctly marked itself as uploaded, and when I checked, the others had as well.

-----

Ok, this was user error. I have over 300 recorded activities in runnerup and I guess we only push up to 100 at a time; I uploaded 100 and after that finished saw that there were still 100 left to upload, so I thought that they hadn't been marked as uploaded.
