### ISSUE TITLE
Runkeeper login

### ISSUE THREAD

**Issue by mwallgren** [jonasoreland/runnerup#185]
I was writing in a closed thread https://github.com/jonasoreland/runnerup/issues/171 on difficulties connecting Runkeeper. I'm now running latest test-version available via Play testarea, but the problem remains. 

I have a new Runkeeper account created Jan 31 with Google-account login. Trying to connect from RunnerUp brings up the Runkeeper login-screen. The Google-login button takes me to Google-account login. After typing epost and password and so on the screen goes white and nothing more happens. 

I'm not into this stuff very deep, but I think other apps recognises the google accounts already logged into on the android. Isn't that correct? As I have two accounts on the phone I often get the question which one I'd like to use. That's the way the Runkeeper app works if I log in. 

I hope my information can be helpful.

**Comment by jonasoreland** [comment]
android version ?

/Jonas

**Comment by mwallgren** [comment]
4.2.2

/Markus

**Comment by mwallgren** [comment]
Ok. Some kind of good news here...

I've from start used the Google-account to log in to RunKeeper. Never used the mail and password login, and thus think I don't have a password for RunKeeper. As Google-login only led to blank page, I tried the "Forgot password"-link to create new RunKeeper password ("new"... don't think I ever had one.) So. I got a reset-mail, created a password and was able to log in to RunKeeper that way. And - it worked connecting RunnerUp to RunKeeper. I'm very satisfied with that. I just run and log. :-) 

I hope you coding people can get some useful info out of this. RunnerUp is just superb. Keep up the good work! Thanks!!!

**Comment by mwallgren** [comment]
Still issues connecting properly to RunKeeper. 
Login only via RunKeeper username and password.  Google+ is not working for me.  Ends up in white screen. 
Upload activity works, but getting the RunKeeper feed to RunnerUp don't work. Pressing sync gives a try I think, but a second later the screen is back blanc. But that is not a big issue for me.  Just reporting what I notice.

**Comment by gerhardol** [comment]
RunKeeper feed does not work #234 
Is login working?

**Comment by gerhardol** [comment]
RK login and up/download works fine.
Feed created an extra login popup that always failed though. Feed was not using a supported API and was removed in #608
