### ISSUE TITLE
Translation - Översättning

### ISSUE THREAD

**Issue by mwallgren** [jonasoreland/runnerup#186]
I've done Swedish translation almost to the end. There are some strings I dont know how to translate, and some of them are not reviewed. It's an issue for someone else Swedish-speaking runner to finish the translation. 
Link to translation: https://www.transifex.com/projects/p/runner-up-android/translate/#sv_SE

/Markus

**Comment by Mixb** [comment]
I have same problem with translate to Russian.

Need to be able to manual choose language in settings. Many Russian-speaking users are accustomed to the English language in fitness applications, as a long time had no alternatives.

**Comment by Mixb** [comment]
2mwallgren - i see your untranslated words, real problem is:
Target pace moving average seconds - matematical termin moving average
Target pace grace seconds
other termins may be translated (without ok, rats :))

**Comment by bagage** [comment]
Hi,

Can you give me with sentences need some hints please? So everyone will know what's the context. Here are my missing-context ones:

- Convert rest-step with type distance to recovery-step for Interval-tab
- Convert rest-step with type distance to recovery-step for Advanced-tab
- Poll interval (ms)
- Poll distance (m)
- Live
- New audio scheme

I will add hints for these unclear sentences (+ @Mixb 's ones), but feel free to open issue on Transifex for every unclear sentence / word to translate.

In the meantime, I do not think that we should handle localization issue on Github?

**Comment by gerhardol** [comment]
Closing issue on GitHub, open on Transifex if needed
