### ISSUE TITLE
Translation - untranslated words

### ISSUE THREAD

**Issue by Mixb** [jonasoreland/runnerup#189]
Hi all!
1) List of world is unwrited in xml files:
*Audio cue scheme:
Default
New audio scheme

*WORKOUT:
my phone
Garmin
Create new workout
Set workout name

*ABOUT:
No much to say at this point

*MAIN FORM: 
heart rate sensor 

*History:
Notes about your workout

*Accounts edit:
website
Automatic upload
*Account Add:
OK
Skip

2) Create separate string for each pair of activity/interval/lap started/stopped/paused and etc.
In language exists stable combinations of these concepts. It is particularly important for voice circuits, translating single words very badly perceived by sound.
as is: " activity " + " paused ", to be: " activity paused " ;

**Comment by Mixb** [comment]
*Point label on Google Map
Paused
Resumed
Etc...

**Comment by jonasoreland** [comment]
i think can now be closed.

**Comment by Mixb** [comment]
Hi Jonas!

1)_ IMHO this items must be sets to read only (trouble if you to add new lang in list bellow. All early translated lang will be wihout new lang). You can delete thise items from transifex.
<item> English </item> ⏎
<item> Dutch </item> ⏎
<item> German </item> ⏎
<item> Japanese </item> ⏎
<item> Arabic </item> ⏎
<item> Russian </item> ⏎
<item> Spanish </item> ⏎
<item> French </item> ⏎
<item> Italian </item> ⏎
<item> Polish </item> ⏎
<item> Turkish </item> ⏎

and

<item> en </item> ⏎
<item> nl </item> ⏎
<item> de </item> ⏎
<item> ja </item> ⏎
<item> ar </item> ⏎
<item> ru </item> ⏎
<item> es </item> ⏎
<item> fr </item> ⏎
<item> it </item> ⏎
<item> pl </item> ⏎
<item> tr </item> ⏎

2) I updated translation of Russian language. There are some doubts about the voice cue. I want to hear how it voice live. Can you compile source for me with Russian? (I have not yet found time to understand Android Studio. Now many overtime, migrating to productive (Gazprom, BI reporting on SAP BEx). Business trips. Hotel, work, repeat.

3) My plans:  improve playback voice use Google voice. I need to undestand how to set accent (like single quote before the letter)

Вторник, 24 февраля 2015, 11:53 -08:00 от Jonas Oreland <notifications@github.com>:
>i think can now be closed.
>—
>Reply to this email directly or  view it on GitHub .


С уважением, Михаил
