### ISSUE TITLE
Feature Request: Show Instantaneous readings heart rate

### ISSUE THREAD

**Issue by Mixb** [jonasoreland/runnerup#191]
Now RunnerUp apps displays HR only of interval, or total. This is calculated values of Heart Rate. Can you add displays Heart Rate on every moment of time during activity.
And add moment HR to Cue scheme. 
I use Timex IronMan Global Trainer Clock with this feature. Cool features in Timex IronMan - manual choise params for show to display.
You can add a choice of parameters to be displayed on the main screen during activity, by analogy with Settings of Cue Scheme. Now part of screen during activity is empty. 
It will be interesting to add various parameters on Lock screen.

**Comment by gerhardol** [comment]
Show HR while exercising (the information should be selectable)
There are other issues to improve the information during activities, for instance #553
