### ISSUE TITLE
Trouble in latest version apps

### ISSUE THREAD

**Issue by Mixb** [jonasoreland/runnerup#192]
*I get this version RunnerUp of e-mail from Jonas (for testing of translating to Russian).
1) Bad work with GPS - start/stop point during walk/ski run/bike. Other apps without this problem.
2) I can not choise Pulse (HR) in Target List on Main screen. (Stable buid apps from Google Play Market wihout this bug)
3) No work settings HR Zone (i can not caclulate HR Zone use age, max HR, sex). Crash apps. I can add HR ZOne manual (enter value). (Stable buid apps from Google Play Market have this bug)
4) First run of app eq Crasth, second run - good. (Stable buid apps from Google Play Market without this bug)

**Comment by jonasoreland** [comment]
Hi there,

Trying to make sense of what you're saying here.
1) There should be no GPS changes in any beta version.
I.e do you have this problem in stable version too ??

2) If HR zones are not configured, that item should be greyed-out in the
drop down and not selectable.
and...3) seems to indicate that you can't do that.

3) & 4) which android version do you have ? can you reproduce in emulator ?

/Jonas

**Comment by Mixb** [comment]
Android is 4.4.2. Emulator is next step :)
I have GPS problem in stable version too. Recurring problem in city and in forest, walking/biking/ski running. I can show screenshots - 2 point start and stop. Between start and stop - 2-10sec.
2) - OK, problem is found. Pulse radio button is disabled. But 3) Crash apps will be prev (first version with Russian) and stable version (from PlayMarket). Now is good :)

**Comment by jonasoreland** [comment]
i think i'll close this,
reopen (clarifying what is left) or open new bug report to start fresh,
with *one* problem per bug report
