### ISSUE TITLE
Can't connect to garmin

### ISSUE THREAD

**Issue by Syn4pse** [jonasoreland/runnerup#193]
I just try this app that looks awesome but i can't connect to Garmin. No error message.
Any idea about that.
So great job
Regards

**Comment by jonasoreland** [comment]
adopt to recent garmin api changes.
https://github.com/jonasoreland/runnerup/commit/b1a59a2c2224cd9f92df218b4dcf07d281ce8c9c
will be part of next release.

/Jonas

**Comment by nebmo** [comment]
I just started AS for the first time in months to fix this issue. Now I can go to bed instead :)

**Comment by jonasoreland** [comment]
You should go out running instead!
Weather here in Stockholm is great so i will

**Comment by nebmo** [comment]
I will tomorrow, time to try some new kind of interval I think!

**Comment by Zutalor73** [comment]
Hello,
I want to update to runnerup 1.41. How can i do ?

**Comment by Syn4pse** [comment]
Ok i'm waiting for next update.
Thanks !!

**Comment by jonasoreland** [comment]
join https://plus.google.com/u/0/communities/112040124647770742805 to get
access to *BETA* releases

/Jonas

**Comment by Syn4pse** [comment]
Thanks I try it

**Comment by Zutalor73** [comment]
I test the new version.
To create its training manually is an excellent new.
Thank you for this application and your help.

**Comment by Syn4pse** [comment]
Garmin's connection is ok.
I try tonight my workout.
Good job ant thanks too for this application

**Comment by Syn4pse** [comment]
I try tonight. It's perfect ! Just what i need. Thanks again.

**Comment by jonasoreland** [comment]
fixed and released
