### ISSUE TITLE
RunnerUp Live server selection not working

### ISSUE THREAD

**Issue by JanKrAppel** [jonasoreland/runnerup#194]
Hi,

I'm trying to set up my own RunnerUp Live server (the PHP based one from [markcs](https://github.com/markcs/RunnerUpLive)). I have changed the server adress to my own server in the advanced settings of RunnerUp, but when I try to create a RunnerUp Live account, it defaults to the websparkles server that is, I believe, preconfigured.

I have no idea where to even start troubleshooting this. Please advise.

Thanks in advance for any help!

**Comment by nebmo** [comment]
Should be in settings / advanced settings

**Comment by JanKrAppel** [comment]
Yes. I did change the server adress in the advanced settings, but when I create the account, it still shows the default server.

**Comment by d0mi** [comment]
Hi,

I got the same problem. I changed url in advanced settings, but during account creation it's still the old url.

**Comment by gerhardol** [comment]
RunnerUp Live is not working what I know but the URL is displayed correctly with #593
