### ISSUE TITLE
Downloading recorded activities from RunKeeper

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#196]
The main idea is to get a possibility to download previously recorded activities from Runkeeper into RunnerUp local database. 

With this solution there should be introduced a way of mapping database objects as entity object in form of Java classes (e.g. Lap, Activity, Location, etc.).

This way there will be a good code base created to make it possible to download activities from other serviced. 

Further argument for this solution
Based on my observation and my personal preferences I thought that it might be useful to create a tool that would keep different accounts in sync. Probably all (or at least many) users have accounts on different services at once just because we like different features of those services or because we just like to share our activities with many friends :)

With the proper design of the upper requirement, the code can be used to create another complementary app with synchronization functionality.

**Comment by paradix** [comment]
Jonas what do you think about creating a RunnerUp database content provider based on the android.content.ContentProvider class. There are nice tools that make the process of generating appropriate java classes really easy?

**Comment by jonasoreland** [comment]
don't know enough about it to have an opinion.

what is is used for ?
what are the tools ?
what should the generated classes be used for ?

generally, i'm not too keen on generated code either...

/Jonas

**Comment by paradix** [comment]
Here are the basics: http://developer.android.com/reference/android/content/ContentProvider.html

The code is generated to make you life easier. You can/have to alter the code that will be generated. Based on a json representation the basic entities and all needed accessors will be automatically  available.

There will be no need for writing sql queries, all this will be wrapped in the ContentProvider.

**Comment by jonasoreland** [comment]
preliminary opinion: not excited.
where do you want to use this ?
what is "wrong" with current proposal? i.e entities that are easy
construct, and we can write one class the persists them to db.

but...code is what matters, if you show me good code, i really don't care
how you wrote/generated it...

/Jonas

**Comment by paradix** [comment]
In the end the ContenProvider is exactly what we were discussing earlier it just wraps it all up.
It's a pattern that can be used to manage the layer between our entities and the db.

Here you can find an example --> https://github.com/BoD/android-contentprovider-generator/tree/master/etc/sample/app/src/org/jraf/androidcontentprovidergenerator/sample/provider

In my opinion it's exactly what you want to achieve and you can get rid of all current queries to db that are in part plain text.

**Comment by jonasoreland** [comment]
so...if you do pull-requests with good code that replaces current code, i'm
super happy!!

/Jonas

**Comment by jonasoreland** [comment]
and if there are things that i don't know much about...
do a small proof a concept

/Jonas

**Comment by paradix** [comment]
Yeah, that's what I intend to do and than we see where this can go.

**Comment by jonasoreland** [comment]
Hi,

Are you still working on this ? Or have I killed all enthusiasm with my retro cobol preferences ?

/Jonas

**Comment by paradix** [comment]
Hi,

I definitely want this to be done, but I'm struggling a little bit because of lack of time.
I also need to rethink my concept of entities because of the closed issue #203 and the ContenProvider concept not being accepted.

So don't think I have abandoned this. I'll be getting back to this issue for sure.

Regards

**Comment by paradix** [comment]
I think this can be closed now.
