### ISSUE TITLE
Singleton to instantiate the SQLiteOpenHelper

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#203]
As I was looking into the code and read about patterns of database handling in android I stumbled upon few articles and discussions;
https://nfrolov.wordpress.com/2014/08/16/android-sqlitedatabase-locking-and-multi-threading/
http://www.androiddesignpatterns.com/2012/05/correctly-managing-your-sqlite-database.html
http://stackoverflow.com/questions/1483629/exception-attempt-to-acquire-a-reference-on-a-close-sqliteclosable

What are your thoughts on this? Any motivation to change that in RunnerUp?

**Comment by jonasoreland** [comment]
one could ofcourse use a singleton for the db.
but I think we got all the open/close correctly, and then this is
"prettier" than a singleton.

i.e I don't know of any problem in this area, so I don't see anything to
fix. do you ?

/Jonas

**Comment by paradix** [comment]
Well there are no known bugs, but from my point of view a singleton would be safer in means of data handling and you wouldn't have to pass around the SQLiteDatabase instanced from method to method.

**Comment by jonasoreland** [comment]
interesting...
from my pow singletons have frequently meant: nice in the beginning but
headache after a while.
though, that is mainly c/c++ experience.

i think passing objects as arguments is good. makes code clear, makes
dependencies obvious.

/Jonas

**Comment by daverix** [comment]
Open the database first when you need to and then store a reference to the database in the application. Don't get it through a static method which singleton might suggest. You cab get it by casting get application() or getApplicationContext() depending on where you are. You should store data in objects for easy inserts, updates and retrieval. That way you can easily mock the the database layer from your logic in unit tests.

**Comment by paradix** [comment]
@daverix this issue and #196 is meant to supply objects (proper java classes) that would wrap all necessary "business" objects of the RunnerUp app. 
By the way I wanted to get rid of the necessity of handling open/close calls to the database by creating an singleton DatabaseHelper since Android handles the open/close correctly.

**Comment by jonasoreland** [comment]
hmm...i thought #196 was about downloading activities from RunKeeper,
and the db-objects was a potential way of make the implementation easier...

maybe i have missunderstood


/Jonas

**Comment by paradix** [comment]
:) 
yes you understood correctly, but on the way to make the RunKeeper work, ideas pop up which I want to discuss here and which could make it all a bit easier.

**Comment by paradix** [comment]
It just leaves me with one question. Is there from your point of view anything worth discussing?
I just don't want to invest my time if there is no interest from you as the author of the app.

**Comment by jonasoreland** [comment]
Hi,

Sorry, can you clarify.
I.e what specific topic do you wonder if I find worth discussing ?
Singleton, db-objects, something else

/Jonas

**Comment by paradix** [comment]
A centralized way of handling db access i.e. through singleton or any other pattern.

**Comment by jonasoreland** [comment]
my current position is "not interested".
- i think the endeavour sounds dangerous in that it's easy to introduce
bugs you/me/beta-testers won't find before making a release,
especially wrt to different behaviour in different android versions....
- i don't think it's problematic to open/close db in each place where it's
needed.

---

though,
1) making code simpler by making the existing 3 lines present in many
places, 1 line instead is ofcourse nice.

2) i don't think that my position is necessarily frozen forever, good
arguments, new circumstances, nice weather
or other factors could change my mind.

sound ok ?

/Jonas

**Comment by paradix** [comment]
OK, but in my opinion without doing some changes you will not be able to create any reasonable test coverage, because you will always need a database somewhere.
Centralizing database access gives you the possibility to mock the layer and test on artificial data.

All in all it's probably a lot of work, but it will pay off in the future if you plan to keep developing the app and changing functionality.

As for opening/closing the database in different places --> http://touchlabblog.tumblr.com/post/24474398246/android-sqlite-locking

Please close the issue if the topic is of the table.

**Comment by jonasoreland** [comment]
- agree that it's probably a lot of work, and maybe it will/would pay off.
so far we've managed fine without it...

- regarding test: i would LOVE if i got a test submitted. for anything
really, so far i've seen none.
i don't give much for the opinion that "if we do this, we could write tests
easily".

- i don't really see any big problems with mocking a database as it is now
either...

I'll close the issue
