### ISSUE TITLE
Write some hrdevice javadoc

### ISSUE THREAD

**Issue by xbao** [jonasoreland/runnerup#207]
Howdy. I'm writing up some JavaDoc for the main classes that client code of the hrdevice module uses.  Pretty much done, just one question if you don't mind. 

What's the purpose of `HRProvider#isBondingDevice()`? 

To refresh your mind: 

It returns `true` for `PolarHRM`, `StHRMv1` and `false` for `AntPluse`, `AndroidBLEHRProvider`, `SamsungBLEHRProvider`.

If it's `true`, a button labelled `Pairing` is available that launches the Bluetooth settings menu

**Comment by jonasoreland** [comment]
it is essentially the same as Bluetooth 2.0,
for those you need to "pair" the phone with the HR using the system dialog.
and there are android API to list them all devices that has been paired
(bonded)

sounds reasonable ? (it has been a while since i looked at that)

/Jonas

**Comment by xbao** [comment]
Oh right, yeah that makes sense. Although it would also apply to BLE right? At least, that's the case for my one, I have a Polar H7 and it needs to be paired to show up in the scan. 

I'll change `AndroidBLEHRProvider` and `SamsungBLEHRProvider` to return `true` if you agree?

**Comment by xbao** [comment]
Hmm, I just did a search and it seems some BLE devices don't require pairing:

http://electronics.stackexchange.com/questions/47273/is-bluetooth-communication-possible-without-pairing

I would still suggest we have the pairing button there, so that users who do require it can use it.

**Comment by jonasoreland** [comment]
is that the only current use?

if (isBonding())
  addButtonFor SystemDialog();

/Jonas

**Comment by xbao** [comment]
Yes that's correct. Here's the complete code snippet:

```
    if (hrProvider.isBondingDevice()) {
        builder.setNeutralButton("Pairing", new DialogInterface.OnClickListener() {

            @Override
            public void onClick(DialogInterface dialog, int which) {
                dialog.cancel();
                Intent i = new Intent(Settings.ACTION_BLUETOOTH_SETTINGS);
                startActivityForResult(i, 123);
            }
        });
    }
```

If you're concerned about it being erroneously used later for something else, I could rename it to `canRequirePairing()`?

**Comment by jonasoreland** [comment]
naaa...no need...go ahead with your plans...

**Comment by gerhardol** [comment]
Changes merged
