### ISSUE TITLE
Translation in French.

### ISSUE THREAD

**Issue by Zutalor73** [jonasoreland/runnerup#209]
Hello,
there is a problem when "Intervall started", "Intervall paused" and "Intervall Resumed". The translation bugs.
Instead of "Pause" or "Tour démarré" or "Démarrer", it's translated in English.
I check French in Audio Cue Langage, but it doesn't work.
Bye

**Comment by obiesmans** [comment]
If this can help it's only since the latest relase (v1.43).

**Comment by bagage** [comment]
Translations for these cues were missing from French version. I added them, but in the future you can contribute by translating them in Transifex. Just create an account on Transifex and contribute to runner-up on https://www.transifex.com/projects/p/runner-up-android/

I think @jonasoreland that you can close this issue now.

**Comment by jonasoreland** [comment]
ok, closing.
new translations will be in next version
