### ISSUE TITLE
Use open source map toolkit

### ISSUE THREAD

**Issue by jas4711** [jonasoreland/runnerup#21]
RunnerUp currently uses Google Play Services to display the map, but play services isn't free software, which means RunnerUp (with map functionality) can't be distributed via fdroid for example -- they require that the app is only free software.  There exists a bunch of free software friendly map toolkits, and this issue is about tracking progress to add support for at least one of them.

(Of course, and I mention this for completeness, there is the alternative of distributing runnerup without map functionality in fdroid -- but it would be better to have maps there too.)

One solution -- but by all means not the only one -- is mapbox.  I have not used it myself, so I can't recommend it, but superficially it appears to fit the bill.  Please have a look at https://www.mapbox.com/blog/mapbox-android/

There may be other options, maybe the fdroid community can give recommendations.  I'm asking around...

/Simon

**Comment by patcon** [comment]
Unless I misunderstand, I think this can be closed?
