### ISSUE TITLE
Time and distance triggered cues doesn't work

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#215]
In version 1.43 on distance and time triggered cues doesn't work. 
No exceptions are being thrown just the TTS isn't speaking.

Can anyone confirm this?

**Comment by nebmo** [comment]
I have only tried new lap cue and that seems to work
Den 11 mar 2015 18:21 skrev "paradix" <notifications@github.com>:

**Comment by paradix** [comment]
Lap cue == "Lap started" etc?

**Comment by nebmo** [comment]
I was talking about end of lap audio cue

**Comment by jonasoreland** [comment]
i'll try in emulator tonight...

- what audio cue language do you use ?
- does the "test audio cue" button work ?

/Jonas

On Wed, Mar 11, 2015 at 10:49 PM, Niklas Weidemann <notifications@github.com

**Comment by paradix** [comment]
I have used the polish language (I'll try others)
The button works, that's why I was wondering.

**Comment by paradix** [comment]
Seems like my /data/data/org.runnerup/shared_prefs/Default_audio_cues.xml has disappeared.

**Comment by paradix** [comment]
It looks like the problem present when the R.string.default_audio_scheme_name is translated
In this case the app looks for Default_audio_cues.xml which isn't present and expected would be to return the org.runnerup_preferences.xml PrefFile

**Comment by paradix** [comment]
This can be closed now, I think.
