### ISSUE TITLE
Can not add Garmin in Accounts on my Samsung Galaxy S5

### ISSUE THREAD

**Issue by RunningCl0ud** [jonasoreland/runnerup#221]
I am sorry to say that adding Garmin do not seem to work in Accounts on my Samsung Galaxy S5.

**Comment by jonasoreland** [comment]
when did you last try ? i.e do you know when it last worked...

comment: those guys on garmin seems to be changing quite frequently :(

/Jonas

**Comment by RunningCl0ud** [comment]
I have just changed phone. It worked on 15/3 -15 last time on my S3 but as mentioned I have a S5 now.

**Comment by jonasoreland** [comment]
ok thx

/Jonas

FYI: you don't need to add an account,
if you on your old phone go to "advanced settings=>export database"
that will create a file on disk that you can transfer to new phone,
and do "advanced settings=>import database"
then your accounts will be transfered...

**Comment by RunningCl0ud** [comment]
Thanks for the tip! Unfortunately I have a happy trigger finger so I missed that one. :-D

**Comment by RunningCl0ud** [comment]
It is working. I think it was my fault. So I close this issue.
