### ISSUE TITLE
Build problem on master branch

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#224]
Error:Some problems were found with the configuration of task ':wear:packageRelease'.
> No value has been specified for property 'signingConfig.storePassword'.
> No value has been specified for property 'signingConfig.keyPassword'.
> File 'C:\down\RunnerUp\my-release-key.keystore' specified for property 'signingConfig.storeFile' does not exist.

**Comment by jonasoreland** [comment]
i'm not sure what caused it...but I solved it by creating the
release.properties
(by creating the release.properties from the release.properties.sample and
following the instructions)

/Jonas

**Comment by nebmo** [comment]
Was caused by a PR where the path in gradle was changed (I think)

**Comment by paradix** [comment]
So this can be close I assume?
