### ISSUE TITLE
Activity time is stored in wrong format

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#225]
The org.runnerup.tracker.Tracker#saveActivity methos stores time as double value.
This lead later on to ClassCastException which are caught and a NULL is returned instead.

This can lead to values being unusable.

**Comment by paradix** [comment]
This seems to be a feature of SQLite --> https://www.sqlite.org/faq.html#q3

**Comment by jonasoreland** [comment]
so is it a bug or not ?
and...is it coming a fix ?

**Comment by paradix** [comment]
Yes it is a bug, and yes I can fix it.

**Comment by paradix** [comment]
Do you want me to inspect all the code for handling time in milliseconds with a double or just fix this one spot?

**Comment by jonasoreland** [comment]
how can I reproduce this bug ? i.e how can I get it in my current version ?
how is it visible to me ?

fix all places that give user visible bug, ignore or do other as you like.


/Jonas

**Comment by paradix** [comment]
It's a very wired bug. I'm not sure how it happened. I was only possible to find it with one recorded activity, where the value DB.ACTIVITY.TIME from table "activity" was returned with a value after the comma i.e. 5834.1

I have exported the db from my phone and opened it with Sqlite Expert to see what's saved in the db. To my surprise I have found the value 5834. After I changed the type of the field TIME from INTEGER to REAL the Sqlite Expert showed the real saved value in the database.

So this way you can check if you have any of this activities in you db. If that's the case you should get a NPE while trying to download something from RunKeeper.

**Comment by paradix** [comment]
But I have already pushed the fix, so you will not see the NPE coming.

**Comment by paradix** [comment]
This problem occurs due to android.database.DatabaseUtils#cursorRowToContentValues using cursor.getString(i) for retrieval of the single column values.

Using cursor.getLong(i) for the TIME column works fine as probably the underlying implementation handles the cast in a proper way. Unfortunately the ContentValues.getAsLong() doesn't handle the cast but just returns null when not able to format as Long.
