### ISSUE TITLE
No altitude tracking function

### ISSUE THREAD

**Issue by g-allen** [jonasoreland/runnerup#229]
I was looking for a compact, basic running app and RunnerUp looked like just what I wanted. I tried it out yesterday and it works well for me. (I'm 67 years old and run just to keep fit.)
Two suggestions however:
1. I live in a hilly area and was disappointed to find no altitude tracking. I'd like to see a graph of up and down hill (ideally superimposed on the speed graph!)
2. The map function required me to install Google Play Services, a huge 30 Mb app, which rather defeated the purpose of looking for a compact running app (my phone is short of memory). Isn't there some other way to access Google Maps? (I'm non a technical expert).
Best wishes, and thanks for your hard work.

**Comment by jonasoreland** [comment]
Hi,

1) Altitude is tracked...but not (yet) graphed

1&2) The easiest to see maps and altitude (and other stuff) is to upload it
to one site
and look at it on the web...RunnerUp supports plenty of them

/Jonas

**Comment by paradix** [comment]
I have been doing some changes to the graphs just for fun and wanted to create a graph similar to what you can find on Endomondo. Part of this is also the altitude,
When I find time I can show some screen shots or create a pull request.

**Comment by g-allen** [comment]
Thank you, good work!
I think your app is great, keep it up!
Please let me know when these functions are incorporated in a new version.
Geoffrey

Il 07/04/2015 alle 10.49, paradix ha scritto:
>
> I have been doing some changes to the graphs just for fun and wanted 
> to create a graph similar to what you can find on Endomondo. Part of 
> this is also the altitude,
> When I find time I can show some screen shots or create a pull request.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jonasoreland/runnerup/issues/229#issuecomment-90468674>.
>

-- 
Via S. Tommaso 13, I-25049 Pilzone (BS), Italy
tel. (+39) 030-523425, +39 348-8130057

**Comment by g-allen** [comment]
Thank you.

Sorry to bother you again but... I uploaded my data to Facebook, but 
where is it now? I can't find any trace of it on FB!!!


Il 05/04/2015 alle 3.24, Jonas Oreland ha scritto:
> Hi,
>
> 1) Altitude is tracked...but not (yet) graphed
>
> 1&2) The easiest to see maps and altitude (and other stuff) is to 
> upload it
> to one site
> and look at it on the web...RunnerUp supports plenty of them
>
> /Jonas
>
> On Sat, Apr 4, 2015 at 7:50 AM, g-allen <notifications@github.com> wrote:
>
> > I was looking for a compact, basic running app and RunnerUp looked like
> > just what I wanted. I tried it out yesterday and it works well for 
> me. (I'm
> > 67 years old and run just to keep fit.)
> > Two suggestions however:
> > 1. I live in a hilly area and was disappointed to find no altitude
> > tracking. I'd like to see a graph of up and down hill (ideally 
> superimposed
> > on the speed graph!)
> > 2. The map function required me to install Google Play Services, a 
> huge 30
> > Mb app, which rather defeated the purpose of looking for a compact 
> running
> > app (my phone is short of memory). Isn't there some other way to access
> > Google Maps? (I'm non a technical expert).
> > Best wishes, and thanks for your hard work.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jonasoreland/runnerup/issues/229>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/jonasoreland/runnerup/issues/229#issuecomment-89697664>.
>

-- 
Via S. Tommaso 13, I-25049 Pilzone (BS), Italy
tel. (+39) 030-523425, +39 348-8130057

**Comment by jonasoreland** [comment]
<your name>
<activity log>
it should be there...

**Comment by jonasoreland** [comment]
it should be under activity log.
it you comment it, it will show up on feed.

**Comment by davidedelvento** [comment]
I think it would be useful to have the altitude plotted, and I'll try to work on it but I'm ok with closing this one. See https://github.com/davidedelvento/runnerup/issues/25
@davidedelvento

**Comment by gerhardol** [comment]
@davidedelvento 
I believe there are other issues with enhancements already. Only find #17 now though
