### ISSUE TITLE
RunKeeper feed is not working

### ISSUE THREAD

**Issue by paradix** [jonasoreland/runnerup#234]
I have tried to debug, and I'm getting response code = -25
Can you confirm it's not working?

**Comment by jonasoreland** [comment]
yes,
they changed something, don't know what
and yes, you get error code back...
haven't debuged

/Jonas

**Comment by paradix** [comment]
I think the feed api has changed.
Now runnerup uses fitnesskeeperapi but the health graph offers runkeeper api with a specific feed request url. At first glance the image url isn't part of the json response.

**Comment by mzandbelt** [comment]
To add to this: I had Strava, Runkeeper and Endomondo accounts connected and the only one of the three that came up in the feed tab was the one of Endomondo. Both the Runkeeper and the Strava feed did not come up (not a big deal for me, just as a feedback) in RunnerUp 1.54, Android 5.1 Moto G.

**Comment by gerhardol** [comment]
RunKeeper feed has been broken for a long time (changed API?), Strava feed has never been implemented
