### ISSUE TITLE
Upload to several sites has been disabled

### ISSUE THREAD

**Issue by nebmo** [jonasoreland/runnerup#236]
@paradix, have you missed to implement some interface for some of the uploaders?
Upload to at least jogg.se and strava is not working anymore

**Comment by paradix** [comment]
Could you please write more about what is not working anymore?
I don't have account on either of this so can't test it.

**Comment by nebmo** [comment]
Ok yeah sorry. When i go to Settings / configure accounts and edit Runkeeper there is a checkbox for automatic upload. That checkbox is not available for strava and jogg.se anymore.
So when i go to a completed Run and look at the upload tab strava and jogg.se are not available in the list.

**Comment by nebmo** [comment]
In AccountActivity:
if (uploader.checkSupport(Uploader.Feature.UPLOAD)) {
                CheckBox cb = new CheckBox(this);

Seems checkSupport is not implemented in JoggSE and checkSupport of DefaultUploader returns false for all features

**Comment by nebmo** [comment]
But I can't find any code written by you that would have introduced this. Strange

**Comment by paradix** [comment]
The logic has been changed in the DefaultUploader.checkSupport. It used to (FormCrawler) always return true for UPLOAD, but I changed it to always return FALSE for all Features, as it doesn't support any Feature in the default implementation.

So the site specific Uploaders need to implement the proper chechSupport() method.

**Comment by paradix** [comment]
you can test with this commit. I hope it will be working.

**Comment by nebmo** [comment]
Thanks! I'll try it later!

**Comment by nebmo** [comment]
PR seems to be working!

**Comment by paradix** [comment]
great, thnx for testing.
