### ISSUE TITLE
cadence (runzi like)

### ISSUE THREAD

**Issue by raver2046** [jonasoreland/runnerup#24]
Hello,
recently i found an app that count impacts when you run, and in my advice it's a good idea (i have found this because i have an achile tandinitis ...)

It seems the app count impacts with accelerometer, can you do that ?

thank you by advance

**Comment by gerhardol** [comment]
As time goes by, step sensors get more and more common, in many high-end phones the last years.
Using Step Counter or accelerometer(/gyro) should be configurable, maybe even accelerometer can be better (and anyway used in no-GPS mode?), but step counter is low power.

Anyone that have tested step counter vs accelerometer?
Anyone compared to a separate footpod?

**Comment by gerhardol** [comment]
Cadence from stepsensor in v1.58
Acceleratometer support could be added too (but that is likely less accurate)

**Comment by davidedelvento** [comment]
@gerhardol @jonasoreland wasn't the cadence via phone accelerometer already supported in the previous beta?

**Comment by gerhardol** [comment]
Cadence from stepsensor supported in #490 
Included in v1.57 (likely 1.58 when officially released)

**Comment by davidedelvento** [comment]
@gerhardol It took me a while to sort this out, so let me make it clear for the sake of the casual reader.  

- as of now, I'm talking of a version not yet released on the play store, but will be soon

- you can measure cadence in 3 ways:
  - accelerometer in the phone
  - dedicated cadence sensor in the phone
  - external cadence sensor

Only dedicated cadence sensor in the phone are supported at the moment, however there is interest in supporting the others, but no ETA yet.

See also #24 #337 and #433 
@davidedelvento
