### ISSUE TITLE
Fails to upload workout to connect.garmin and Funbeat

### ISSUE THREAD

**Issue by RunningCl0ud** [jonasoreland/runnerup#244]
For some reason I can not upload my activity to above mentioned sites for yesterdays run.

I paused the app during my run and had some coffee. I filled in some notes and resumed the activity. when i stopped the app at the end of the run the notes where gone? So I filled it in again. 
Upload worked fine with Runkeeper.  

Edit: Maybe there is some sort of conflict and the notes i made in the first place still is in the memory but invisible to me?

**Comment by jonasoreland** [comment]
can you try again,
like once a day for a couple of days.

"all" sites seems to have downtime every now and then...

/Jonas

**Comment by RunningCl0ud** [comment]
Yepp, done that but I will try couple of more times and tomorrow I will do another run so I will see if I can sort it out.

**Comment by RunningCl0ud** [comment]
Nah, I think that something is wrong with the file but Runkeeper seems to handle that but not Funbeat nor Connect. I have exported as .gpx from Runkeeper and imported it manually to Connect and it then doesn't presents the laps and it is a difference in time between running and total time. As I mentioned above I took a rest and paused the app and after 20 min I resumed it. I think the problem lies here.

How can I help? Is there a way to look at the file in the memory of the app?

**Comment by jonasoreland** [comment]
you can mail it to yourself (and both garmin/funbeat uses TCX)

/Jonas

**Comment by RunningCl0ud** [comment]
the .tcx fails to open with Gedit or import to Connect and the .gpx is impossible to attach to mail?

**Comment by RunningCl0ud** [comment]
Same thing today. I ran a workout imported from Connect and it failed to upload to Funbeat and Connect but was fine with Runkeeper. Sad because I made a PR!

**Comment by jonasoreland** [comment]
can you mail the TCX file ?

/Jonas

**Comment by RunningCl0ud** [comment]
Done! 
/RC

**Comment by jonasoreland** [comment]
this is fixed.
