### ISSUE TITLE
merge activity records

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#245]
It would be nice to have automatic facilities for merging 2 activities, for cases where either via accidental stop or crash an activity has had to be restarted.

**Comment by jonasoreland** [comment]
agree!

**Comment by paradix** [comment]
would this be possible by simply adding a the ID of the previous or next activity and handling this at presentation layer?

**Comment by jonasoreland** [comment]
i think an simple update would work.
something like (roughly):

begin;
update location set activity_id = <new_activity_id>, lap = lap + (max lap
new activity_id) where activity_id = <old_activity_id>;
update lap set activity_id = <new_activity_id>, lap = lap + (max lap new
activity_id) where activity_id = <old_activity_id>;
update activity set total_time=total_time + (time old acitivity),
total_distance=(...) ... where activity_id = <new_activity_id>;
delete from activity where activity_id = <old_activity_id>;
commit;

I can do the SQL...but...we need a GUI to select which activities to
merge...

/Jonas

**Comment by paradix** [comment]
Would be nice to make some plausibility checks before the user ruins his history.
i.e. 
 - checking start time of next against end time of previous activity
 - checking sport types 
 - ...?

**Comment by jonasoreland** [comment]
yes,

**Comment by paradix** [comment]
I could try to do this, but at this point of the week I'm swamped with work.

**Comment by gerhardol** [comment]
#287 implements merging (needs some rework though). Closing issue

**Comment by dhiltonp** [comment]
It's weird to close this as the issue isn't completed.

**Comment by gerhardol** [comment]
The PR is open (there were 150 open issues before so the relevant issues were not found..)
