### ISSUE TITLE
cannot run the application to build as developer

### ISSUE THREAD

**Issue by cuong0906** [jonasoreland/runnerup#252]
Hi jonasoreland,
i got this error after following the instruction from the documentation how to build with android studio

Error:(8, 39) error: package com.dsi.ant.plugins.antplus.pcc does not exist

**Comment by jonasoreland** [comment]
have you missed the "git submodule init && git submodule update" ??

/Jonas

**Comment by cuong0906** [comment]
how can i do it?

**Comment by cuong0906** [comment]
can you guild me how to do it, im kind of new in git

**Comment by jonasoreland** [comment]
google it

**Comment by cuong0906** [comment]
now i got this
pkg: /data/local/tmp/org.runnerup
Failure [INSTALL_FAILED_OLDER_SDK]

**Comment by nebmo** [comment]
You need to deploy froyo flavor, not latest. I think

**Comment by cuong0906** [comment]
thks a lot.
now I can run the apps  ,but in both emulator and physical device, it just show 'Waiting for phone' on the screen.

**Comment by Obfuscati0n** [comment]
AS2.0
Gradle 'runnerup' project refresh failed
Error:Cause: com.android.sdklib.repository.FullRevision

**Comment by jonasoreland** [comment]
this happens after upgrading gradle plugin,
if you don't upgrade it...it works..

however, if someone can find a way of fixing this it would be great!!
see
http://stackoverflow.com/questions/33881984/errorcause-com-android-sdklib-repository-fullrevision

/Jonas

**Comment by Obfuscati0n** [comment]
It's Jake Wharton library, just stumbled over this: https://github.com/JakeWharton/sdk-manager-plugin/issues/99. Thanks for the tip, now up and running :)

**Comment by jonasoreland** [comment]
cool...can you propose a patch ?
(cause i don't know how proceed...except not upgrading plugin)

**Comment by Obfuscati0n** [comment]
Would love to, but I'm pretty new to this...taken me 3 days to get this far. Yours is the first sample code I've managed to import into AS2, clear all the errors & actually run!
