### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bagage** [jonasoreland/runnerup#258]
Could you prepare a new beta/release of RunnerUp @jonasoreland ? I'd like to have fixed French translations and also would like extra sports test (I only dev on simulator because I do not want to mix my accounts). Would it be possible?

**Comment by jonasoreland** [comment]
Yes, i think this is a brilliant idea.
I have thought about it a while, but have not gotten around to it.
Do anyone know of any bugs that we should fix first ??

**Comment by CharString** [comment]
+1 not that I think it should be of any influence on your schedule, but a new release would make me very happy. 😃

**Comment by bagage** [comment]
By the way If you could upload the APK to github too (on release page, [here for v1.43](https://github.com/jonasoreland/runnerup/releases/tag/v1.43)), it would be great! I removed play store stuff, and meanwhile I do fdroid stuff (build without gmaps, etc.), I'd like to still get the "official" release ;-).

**Comment by jonasoreland** [comment]
published v1.44 as beta just now.
if no bug reports shows up, i'll promote it to production in a week or two.

re bagage: I can't upload to github like that...
If you have somewhere to publish it, I can mail it too you

/Jonas

**Comment by bagage** [comment]
@jonasoreland Yes you can: simply go to [release page here](https://github.com/jonasoreland/runnerup/releases/tag/v1.44) then "edit tag", and at the bottom you'll have a drag&drop area for binaries. Browse for your APK and it will then be available as well as source archives.

**Comment by jonasoreland** [comment]
look ok now ?
(cool, i didn't know that...)

/Jonas

**Comment by bagage** [comment]
Yes, thanks! (note: GitHub is everything :) ).
