### ISSUE TITLE
RunKeeper Downloaded workout does not appear in history tab

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#261]
Hi,

After reinstalling runnerup, I tried to download my old workout through runkeeper, but after I downloaded them, my history tab stay empty.

**Comment by paradix** [comment]
There seem to be a problem with activities not having a comment/note. I'll fix it soon.

**Comment by jonasoreland** [comment]
can you check if latest fixes works ??
(so we can close this issue)

**Comment by ixeft** [comment]
It is working,
Thanks a lot !
