### ISSUE TITLE
Map trace is not downloaded with other data using RunKeeper connector.

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#266]
Hello,

When I download my data from RunKeeper,
Map infos are no present in the RunnerUp (the map stays grey)
I can check the map of those workout from runkeeper

**Comment by paradix** [comment]
@jonasoreland - may it be because of maps api key or something similar?

**Comment by nebmo** [comment]
Definitely!

**Comment by paradix** [comment]
Ok, I checked my apps database an all the location points for activities from RunKeeper are stored, just not presented on the maps as I use my custom build.

I haven't installed the official 1.44 beta build, so I'm not sure about the maps api.

**Comment by ixeft** [comment]
Hello,
It is definilty api key problem :s 
Sorry for the bad report !
