### ISSUE TITLE
RunnerUp min sdk is 8 but use function only avalaible in sdk 11

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#271]
### Problem
In AbstractEntity.java line 54,
`setKey()` is used, which is avalaible only for sdk v11 and greater.

it make crash runkeeper import on Android 2.3.7 .

### Solutions : 
- Change minimum sdk, and stop support for 2.3.7 (6% of devices still use this OS, including my old test phone) 
 Source :https://developer.android.com/about/dashboards/index.html?utm_source=suzunone

- Use this trick : https://stackoverflow.com/questions/20152896/nosuchmethod-error-in-contentvalues-keyset-on-old-android-devices
For this particular problem and try to keep compatibility.

(whatever solution is choosen, I will be happy to make the change ;) )

**Comment by skaldarnar** [comment]
The workaround looks reasonable (although it is still a workaround...). As long it is the only thing that does not work on older versions the trick is fine. 
You'll probably should leave a TODO note in place in case the minVersion is bumped in the future and the code can be cleaned up again.

**Comment by jonasoreland** [comment]
we must also be stricter in code review that the classes should be
annotated with @TargetApi(Build.VERSION_CODES.FROYO)

/Jonas

**Comment by jonasoreland** [comment]
update:
1) i added missing annotations:
https://github.com/jonasoreland/runnerup/commit/89d7ae0576a3c5e457118f0e28dd9710a0d9f1a0

BUT!!! i didn't get compile error anyway...
does anyone know why ?? (i used to in eclipse)

2) then i fixed the problem in
https://github.com/jonasoreland/runnerup/commit/c4ef3aaf3c0ef248a3f01025acc502c3e376dd86

/Jonas

**Comment by skaldarnar** [comment]
@jonasoreland do you really need the target API annotation? I understand that the annotation can override the project setting of min SDK. Having the project minimum set correctly should suffice to disallow use of newer functionality... 

Also, the annotation is used by Lint - does Android Studio (or whatever IDE you are using) use it automatically? Maybe you need to trigger it explicitly via *Analyze > Inspect Code*.

/Tobias

[1] http://stackoverflow.com/questions/24798481/android-target-api
[2] http://developer.android.com/reference/android/annotation/TargetApi.html

**Comment by jonasoreland** [comment]
1) re annotations: we want to have a mixed environment...
FROYO is "base", but we also use features in newer versions (gated by
checks)

2) it used to be that using non-supported APIs (incorrectly) caused build
error...
that it doesn't is a regression, that's probably introduced when switching
to gradle

/Jonas

**Comment by jonasoreland** [comment]
i think this is fixed.
reopen if needed
