### ISSUE TITLE
Suggestion: Use Gitflow Workflow

### ISSUE THREAD

**Issue by skaldarnar** [jonasoreland/runnerup#273]
This suggestion is mainly to get some more information about your current workflow, and possibly how to improve it. 

I've seen that there is only one branch (`master`) on which the whole development is happening. Gitflow Workflow [1] separates a branch for ongoing development (`development`) which is used to integrate new features and test them before merging them into `master`. Therefore, `master` would always be in state where the application compiles and works properly. 

Additionally, this approach allows to easily trigger travis CI builds for specific branches or pull-requests. 

As stated in the first sentence, this is only a suggestion. I'd like to learn more about your current workflow and how you plan to go in the future.

/Tobias

[1] https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by jonasoreland** [comment]
my current workflow is this.

1) only master branch, should always compile and work properly

2) me&others develop features on their own branches

i don't have any opinion on what branches others have, or how they organize
them.


3) me&others make pull requests (PR) to get things into master
(i actually mostly just merge my things directly, without pull
requests...but should probably change that for visibility)

4) if feature is BIG, i sometimes requests that the PR is split into
several smaller PR.
the smaller PR should be still compile and work properly
the feature is not enabled until all of the smaller PRs get merged...i.e it
gets enabled in last PR.

5) there might be bugs in new feature, but it should absolutely not
introduce regressions

6) after a number of PRs has been merged...and there been a "quite period",
I make a beta.
after no reports on that for a while, I promote to public release.

---

i don't currently see any particular reason to change,
and think that most contributors are reasonably happy.

first couple of times you submit a PR your code will be reviewed more
carefully.
the more code you submitted, the more trust you earn.

---

- sounds reasonable ?
- you're most welcom to document this, if you think it's valueable

/Jonas

**Comment by skaldarnar** [comment]
Thank you for the explanation :)
