### ISSUE TITLE
wear target not building because missing android:elevation and android:stateListAnimator

### ISSUE THREAD

**Issue by bagage** [jonasoreland/runnerup#275]
Opening runner up and pressing "start" button, it fails yet. If using buildLatest and commenting `   latestWearApp project(':wear')`, it build fine...

Full output is:

> Information:Gradle tasks [:app:compileFroyoDebugSources, :app:compileFroyoDebugAndroidTestSources, :common:compileDebugSources, :common:compileDebugAndroidTestSources, :wear:compileDebugSources, :wear:compileDebugAndroidTestSources, :hrdevice:compileDebugSources, :hrdevice:compileDebugAndroidTestSources]
> :app:preBuild UP-TO-DATE
> :app:preFroyoDebugBuild UP-TO-DATE
> :app:checkFroyoDebugManifest
> :app:preFroyoReleaseBuild UP-TO-DATE
> :app:preLatestDebugBuild UP-TO-DATE
> :app:preLatestReleaseBuild UP-TO-DATE
> :common:compileLint
> :common:copyReleaseLint UP-TO-DATE
> :common:mergeReleaseProguardFiles
> :common:preBuild UP-TO-DATE
> :common:preReleaseBuild UP-TO-DATE
> :common:checkReleaseManifest
> :common:prepareReleaseDependencies
> :common:compileReleaseAidl
> :common:compileReleaseRenderscript
> :common:generateReleaseBuildConfig
> :common:generateReleaseAssets UP-TO-DATE
> :common:mergeReleaseAssets
> :common:generateReleaseResValues
> :common:generateReleaseResources
> :common:packageReleaseResources
> :common:processReleaseManifest
> :common:processReleaseResources
> :common:generateReleaseSources
> :common:compileReleaseJava
> :common:processReleaseJavaRes UP-TO-DATE
> :common:packageReleaseJar
> :common:compileReleaseNdk UP-TO-DATE
> :common:packageReleaseJniLibs UP-TO-DATE
> :common:packageReleaseLocalJar UP-TO-DATE
> :common:packageReleaseRenderscript UP-TO-DATE
> :common:bundleRelease
> :hrdevice:compileLint
> :hrdevice:copyReleaseLint UP-TO-DATE
> :hrdevice:mergeReleaseProguardFiles
> :hrdevice:downloadSamsungBleSdk
> :hrdevice:preBuild
> :hrdevice:preReleaseBuild
> :hrdevice:checkReleaseManifest
> :hrdevice:prepareReleaseDependencies
> :hrdevice:compileReleaseAidl
> :hrdevice:compileReleaseRenderscript
> :hrdevice:generateReleaseBuildConfig
> :hrdevice:generateReleaseAssets UP-TO-DATE
> :hrdevice:mergeReleaseAssets
> :hrdevice:generateReleaseResValues
> :hrdevice:generateReleaseResources
> :hrdevice:packageReleaseResources
> :hrdevice:processReleaseManifest
> :hrdevice:processReleaseResources
> :hrdevice:generateReleaseSources
> :hrdevice:compileReleaseJava
> :hrdevice:processReleaseJavaRes UP-TO-DATE
> :hrdevice:packageReleaseJar
> :hrdevice:compileReleaseNdk UP-TO-DATE
> :hrdevice:packageReleaseJniLibs UP-TO-DATE
> :hrdevice:packageReleaseLocalJar
> :hrdevice:packageReleaseRenderscript UP-TO-DATE
> :hrdevice:bundleRelease
> :app:prepareComAndroidSupportSupportV42220Library
> :app:prepareComMapboxMapboxsdkMapboxAndroidSdk074Library
> :app:prepareOrgRunnerupHrHrdevice10Library
> :app:prepareRunnerupCommonUnspecifiedLibrary
> :app:prepareFroyoDebugDependencies
> :app:compileFroyoDebugAidl
> :app:compileFroyoDebugRenderscript
> :app:generateFroyoDebugBuildConfig
> :app:generateFroyoDebugAssets UP-TO-DATE
> :app:mergeFroyoDebugAssets
> :app:generateFroyoDebugResValues
> :app:generateFroyoDebugResources
> :app:mergeFroyoDebugResources
> :app:processFroyoDebugManifest
> :app:processFroyoDebugResources
> :app:generateFroyoDebugSources
> :app:compileFroyoDebugJava
> Note: Some input files use or override a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> :app:compileFroyoDebugNdk UP-TO-DATE
> :app:compileFroyoDebugSources
> :app:preFroyoDebugAndroidTestBuild UP-TO-DATE
> :app:prepareFroyoDebugAndroidTestDependencies
> :app:compileFroyoDebugAndroidTestAidl
> :app:processFroyoDebugAndroidTestManifest
> :app:compileFroyoDebugAndroidTestRenderscript
> :app:generateFroyoDebugAndroidTestBuildConfig
> :app:generateFroyoDebugAndroidTestAssets UP-TO-DATE
> :app:mergeFroyoDebugAndroidTestAssets
> :app:generateFroyoDebugAndroidTestResValues
> :app:generateFroyoDebugAndroidTestResources
> :app:mergeFroyoDebugAndroidTestResources
> :app:processFroyoDebugAndroidTestResources
> :app:generateFroyoDebugAndroidTestSources
> :app:compileFroyoDebugAndroidTestJava
> :app:compileFroyoDebugAndroidTestNdk UP-TO-DATE
> :app:compileFroyoDebugAndroidTestSources
> :common:preDebugBuild UP-TO-DATE
> :common:checkDebugManifest
> :common:prepareDebugDependencies
> :common:compileDebugAidl
> :common:compileDebugRenderscript
> :common:generateDebugBuildConfig
> :common:generateDebugAssets UP-TO-DATE
> :common:mergeDebugAssets
> :common:generateDebugResValues
> :common:generateDebugResources
> :common:packageDebugResources
> :common:processDebugManifest
> :common:processDebugResources
> :common:generateDebugSources
> :common:compileDebugJava
> :common:compileDebugNdk UP-TO-DATE
> :common:compileDebugSources
> :common:preDebugAndroidTestBuild UP-TO-DATE
> :common:prepareDebugAndroidTestDependencies
> :common:compileDebugAndroidTestAidl
> :common:copyDebugLint UP-TO-DATE
> :common:mergeDebugProguardFiles
> :common:processDebugJavaRes UP-TO-DATE
> :common:packageDebugJar
> :common:packageDebugJniLibs UP-TO-DATE
> :common:packageDebugLocalJar UP-TO-DATE
> :common:packageDebugRenderscript UP-TO-DATE
> :common:bundleDebug
> :common:assembleDebug
> :common:processDebugAndroidTestManifest
> :common:compileDebugAndroidTestRenderscript
> :common:generateDebugAndroidTestBuildConfig
> :common:generateDebugAndroidTestAssets UP-TO-DATE
> :common:mergeDebugAndroidTestAssets
> :common:generateDebugAndroidTestResValues
> :common:generateDebugAndroidTestResources
> :common:mergeDebugAndroidTestResources
> :common:processDebugAndroidTestResources
> :common:generateDebugAndroidTestSources
> :common:compileDebugAndroidTestJava
> :common:compileDebugAndroidTestNdk UP-TO-DATE
> :common:compileDebugAndroidTestSources
> :wear:preBuild UP-TO-DATE
> :wear:preDebugBuild UP-TO-DATE
> :wear:checkDebugManifest
> :wear:preReleaseBuild UP-TO-DATE
> :wear:prepareComAndroidSupportRecyclerviewV72200Library
> :wear:prepareComAndroidSupportSupportV42200Library
> :wear:prepareComGoogleAndroidGmsPlayServicesBase750Library
> :wear:prepareComGoogleAndroidGmsPlayServicesWearable750Library
> :wear:prepareComGoogleAndroidSupportWearable120Library
> :wear:prepareRunnerupCommonUnspecifiedLibrary
> :wear:prepareDebugDependencies
> :wear:compileDebugAidl
> :wear:compileDebugRenderscript
> :wear:generateDebugBuildConfig
> :wear:generateDebugAssets UP-TO-DATE
> :wear:mergeDebugAssets
> :wear:generateDebugResValues
> :wear:generateDebugResources
> :wear:mergeDebugResources
> :wear:processDebugManifest
> :wear:processDebugResources
/runnerup/wear/build/intermediates/exploded-aar/com.google.android.support/wearable/1.2.0/res/values-v21/> values.xml
> Error:(33, 21) No resource found that matches the given name: attr 'android:elevation'.
> Error:(35, 21) No resource found that matches the given name: attr 'android:stateListAnimator'.
> Error:Execution failed for task ':wear:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/android-sdk-linux/build-tools/20.0.0/aapt'' finished with non-zero exit value 1

**Comment by jonasoreland** [comment]
i think https://github.com/jonasoreland/runnerup/commit/a8760afce5305ef4ea80e743dc630abed44562c7 fixed this problem.
can you test ??

**Comment by bagage** [comment]
This problem is fixed yes. But now (eg master) is not building because of:
```
Error:Some problems were found with the configuration of task ':wear:packageRelease'.
> No value has been specified for property 'signingConfig.storePassword'.
> No value has been specified for property 'signingConfig.keyPassword'.
> File '/home/gautier/code/runnerup/my-release-key.keystore' specified for property 'signingConfig.storeFile' does not exist.
```

**Comment by jonasoreland** [comment]
how does your release.properties look like ??

/Jonas

**Comment by jonasoreland** [comment]
made another commit: https://github.com/jonasoreland/runnerup/commit/850ef69086af3a3cfb32439463b7b205d509a12b

works now ??

**Comment by bagage** [comment]
Yes, it's working now!
