### ISSUE TITLE
Graph/Plotting Library

### ISSUE THREAD

**Issue by skaldarnar** [jonasoreland/runnerup#278]
Is there any reason the plotting library [GraphView](https://github.com/jjoe64/GraphView) is used in the old version 3.1? Additionally, why is the library included as a submodule instead of fetching the compiled version from a central repo? 

I'd like to get my hands on the the plots and I'ld like to have some more features, e.g., dotted lines. I'm not sure GraphView can give me everything I'd like to have, so here's a list comparing some other plotting libs. I took the minimal version into account, please let me know if I'm missing something importing for RunnerUp.

| Library | Version | min SDK | Note |
| --- | --- | --- | --- |
| [GraphView](http://www.android-graphview.org/) - [Source](https://github.com/jjoe64/GraphView) | 4.0.1 | 9 | Maven Central; styles (dotted, …); last commit in april |
| MPAndroidChart - [Source](https://github.com/PhilJay/MPAndroidChart) | 2.1.0 | 8 | jitpack.io (maven); clean look; good documented; |
| [androidPlot](http://androidplot.com/) - [Source](https://bitbucket.org/androidplot/androidplot/src/397fac6a3541b4020a716e958a9c0b42bd2450fd?at=master) | 0.6.x | ? | Maven Central; last commit sep 14! |

I'm thinking about trying out MPAndroidChart. Do you have any objections @jonasoreland ?

**Comment by paradix** [comment]
I have been trying on my local repo branch to incorporate MPAndroidChart. It looked nice and clean, but I think there were also some problems with the X-Values on the chart. I would have to look for that branch.

**Comment by jonasoreland** [comment]
1) no particular opinion which graph library to use
but supporting froyo is a requirement...still approx 400 runnerup'ers using froyo

2) i like/prefer submodule,
no blob and no download that suddenly stops working (we had that for ANT before)

**Comment by skaldarnar** [comment]
re 1) From that point of view it seems like we should give MPAndroidChart a try. 

re 2) I never encountered any problems with (stable) libs from maven repos. I'd like to have gradle do the work of dependency management instead of maintaining submodules by hand. Since git submodules are in detached head state it can be a bit complicated to see which version of library is actually in use.

**Comment by nebmo** [comment]
1. do it.
2. Gradle is awesome as long as they keep old versions there (or else we have to regression test). When graphview was added years ago we didn't use gradle.

**Comment by jonasoreland** [comment]
Any update?

**Comment by gerhardol** [comment]
Graphs (and maps) are dropped on pre 4.03 releases since 1.56
GraphView is updated (changes was required), maven repo used

If other libs are better, use them instead
GraphView can be improved (multiple charts in one graph for instance)
New dev will increase minimal version anyway

**Comment by davidedelvento** [comment]
@gerhardol @cmmata -- I'm interested in looking at improving the graphs, and I plan to try MPAndroidChart too. I'm fine with closing this issue, just letting you know my intentions, so maybe we communicate before duplicating efforts.
