### ISSUE TITLE
Port to Ubuntu for phones

### ISSUE THREAD

**Issue by ktatar156** [jonasoreland/runnerup#281]
Hello,
today Meizu started selling their MX4 with Ubuntu, that's a third phone with that system. The main issues for me (and I think, for many people) is lack of sport tracker app on that system.
Please look here https://plus.google.com/+KrzysztofTataradzi%C5%84ski/posts/LY6YeZarqS8
Is it possible to port that app to Ubuntu Touch? Will it be hard? Could you do it?
I think this is a great opportunity to get a large number of users, due to the lack (for now) of competition.

**Comment by jonasoreland** [comment]
i have personally no idea how easy/hard it might be.
but it would be cool if someone could do this!

/Jonas

**Comment by ktatar156** [comment]
Can you do that port? You can create crowdfunding project and I think you'll get plenty of backers (I'm the first). Or if you don't know how to port that/don't have time, maybe that crowdfund will be great opportunity to hire developer(s) for that?

**Comment by jonasoreland** [comment]
i'll cose this...
it's probably best done as a fork

**Comment by cmmata** [comment]
Taking a quick look at Google, I see that it's possible to install java VM in Ubuntu Touch, but not easy. So the first problem is that final users must be able to "open" Ubuntu touch and install java.

About porting the app, you should find alternatives to Google Play Services if the app uses them, and converting all the interface to another java's UI system. So it's not an easy port, it could take a long time. Do you think there would be enough bakers? I don't know how much Ubuntu Touch phones are out there.

**Comment by ktatar156** [comment]
it depends how many cash we need to get that app working in UT. 2000 $ would be enough? Someone can create crowd-funding campaign and I will help with promoting it. If we don't get needed resources, we don't lose anything (maybe some time).
