### ISSUE TITLE
Missing summary if device shutting down during activity

### ISSUE THREAD

**Issue by bagage** [jonasoreland/runnerup#283]
My last ran could not be completed because my device battery was too low and the device shutdown before the end; the summary of this activity has not been created (duration / distance).

What would be a good solution to "rebuild it" if missing? Either:

1) add a settings "Rebuild database" which would check that summaries are all present or recompute them (not very user friendly)
2) check at each startup that all recorded activities are valid (what about 100+ activities? would it be ok?)
3) when going to history tab, if missing summary, show a popup asking user if he wants to reconstruct missing data and/or do it automatically?

Anyway my truncated activity was still uploaded to Endomondo which displays me a 0 km in  0h00min activity even if map is actually filled with GPS points... I'd like to avoid this in the future, if possible.

WDYT @jonasoreland ?

**Comment by dhiltonp** [comment]
If we can detect that an activity was aborted mid-run without pressing "Stop", we should definitely be able to continue that activity correctly - this relates to #245 which I would like to resolve (and I'll have access to a development environment within the next week).

**Comment by bagage** [comment]
hmm, indeed I did not thought about it. In this case "Resume" is obviously irrelevant, but having the opportunity to save the activity properly would be the best scenario indeed! 
I will wait for your PR then :-).

**Comment by jonasoreland** [comment]
i made a "recompute activity" once for this exact use-case

have you tried that ?


/Jonas

**Comment by bagage** [comment]
I bet I saw this once... but I could not find it anymore???

Is it maybe in the "..." menu? It does not appear on my Android 5.0 so it would explain it?

**Comment by jonasoreland** [comment]
if the menu is disappeared on android 5.0, that is it...hmm..annoying...
/Jonas

**Comment by dhiltonp** [comment]
Reopening #141

**Comment by dhiltonp** [comment]
Jonas, what do you think about setting/clearing a flag on activity start/end (written to db?) in order to catch this type of situation? Or is there some characteristic of the most recently logged activity that we could check for?

**Comment by jonasoreland** [comment]
i think the "activity row" is missing distance/duration,
this is only populated when the activity is completed...

so I don't think a new flag is needed...

/Jonas

**Comment by dhiltonp** [comment]
Very good.

@bagage, could you share your db export? It would simplify testing for me :)

**Comment by bagage** [comment]
Sure, you can download it from [here](http://tinyurl.com/njb8env)

**Comment by dhiltonp** [comment]
Thanks for your help, @bagage :)

**Comment by dhiltonp** [comment]
#286 fixes this.
