### ISSUE TITLE
Sync to dropbox so that tapiriik can sync to other services

### ISSUE THREAD

**Issue by patcon** [jonasoreland/runnerup#284]
https://tapiriik.com/

Seems like it might absolve you from having to integrate any more providers? :)

cc: @cpfair

**Comment by jonasoreland** [comment]
comment: you can already e.g mail a tcx, and then use tapiriik,
but having it simple and automatic is really nice...

though i don't mind syncing to dropbox (e.g as backup)

/Jonas

**Comment by gerhardol** [comment]
You can use the File synch since 1.56 or so to save runs to a file and use DropSync to trigger upload.
