### ISSUE TITLE
Export history and or single tracks from history

### ISSUE THREAD

**Issue by OvOwl** [jonasoreland/runnerup#297]
I recorded a session and would like to share it with someone who uses another service.
As I have no account whatsoever, i'd like to export it directly from the app.

**Comment by dhiltonp** [comment]
Go to an activity, then click on the "..." to see the extended menu. Click Share Activity. Does that do what you need it to?

**Comment by OvOwl** [comment]
That's the point there is no extended menu, not even a menu.
Nexus 4 Android 5.1.1
RunnerUp v1.47 from F-Droid

**Comment by dhiltonp** [comment]
Ah. That is a problem.

**Comment by bagage** [comment]
Already know issue unfortunately but no one has found (searched?) a workaround for this yet. I am also affected and yes, this is an issue :).

**Comment by OvOwl** [comment]
Thanks for the info, wasn't sure about translations. With #141 open I'll close this one.
