### ISSUE TITLE
Heartrate not uploaded to runkeeper anymore

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#299]
Hello,

since end of May / Beginning of june, my Heartrate is not uploaded into runkeeper, while i can see it on runnerup :/

**Comment by jonasoreland** [comment]
It "has" to be related to this commit:
https://github.com/jonasoreland/runnerup/commit/14815976c05428807804ef193025541c28bfb661

i fixed one issue with
https://github.com/jonasoreland/runnerup/commit/7ff55a9df913d6be4859378457674cdca9ca0d12,
maybe it's similar??

(my heartrate belt has been out of battery last couple of month...but I
actually replaced it yesterday!)

/Jonas

**Comment by bagage** [comment]
Hm I do not get why this is broken but yes this commit seems a reasonable culprit.

But was is your commit `7ff55a` fixing then if it is still broken?

**Comment by jonasoreland** [comment]
fixed by https://github.com/jonasoreland/runnerup/commit/d1032f4a7e730edaeecc5961188df9cb5ee7e621
