### ISSUE TITLE
Sync to runalyze

### ISSUE THREAD

**Issue by piratenpanda** [jonasoreland/runnerup#300]
I don't know if runalyze can import sync data but as it's also free software it would be nice if you could cooperate in some way :)

https://runalyze.com/login.php

**Comment by sporkbyspork** [comment]
This would be really great. By self-hosting Runalyze, you wouldn't need to give the data collected by Runnerup away to third parties.

**Comment by jonasoreland** [comment]
hmm...it seems this is also open source,
https://github.com/Runalyze/Runalyze
so it should be very doable to fix synchronization.

**Comment by lenucksi** [comment]
That would be splendid for the reasons @sporkbyspork named!
They appear to already support quite a number of sync services.
:+1:

**Comment by mipapo** [comment]
Should be no problem, when we have our API. Please stay tuned. We will inform you!

**Comment by RunningCl0ud** [comment]
I cross my fingers and hope you make it happen @mipapo  :+1:

**Comment by powellc** [comment]
Anyone else working on this? Otherwise I've got a pull request coming in a few here.

**Comment by mipapo** [comment]
@powellc Without our API it will be just a dirty hack. So my recommendation is to wait for it ;)

**Comment by powellc** [comment]
Yeah, after I posted that I took a look at Runalyze source and realized what I was up against! Also I haven't done PHP work in years so I don't trust myself to work on that codebase ... I'll wait. In the meantime, just getting gpx files in ownCloud would be awesome, so I'm working on that.

**Comment by Marx2** [comment]
I've succesfully launched selfhosted runalyze site, and imported all my trainings from RunnerUp through gpx files (downloaded from Strava). It would be great to have it automated. And it would be great to integrate live positioning on the map during run with this webapp.

**Comment by Marx2** [comment]
As their API doesn't seem to appear in a near feature, maybe it would be nice to implement so called "dirty solution" 
referenced here:
https://github.com/Runalyze/Runalyze/issues/498
https://gist.github.com/mipapo/cafe45b0c2a247d9c0614bd2cc8fe4d0

**Comment by mipapo** [comment]
I'm not sure if it would be a great idea to do this. 
I really try to get the basic API done by the end of the year.
Next RUNALYZE release will be 3.0 and I think we will just getting faster after that version in our development process. I'm getting more confident that we manage that this year

**Comment by rickyepoderi** [comment]
Hi everyone,

I have implemented a very simple automatic synchronizer to runalyze. It is very simple and follows the ideas presented previously in this [blog entry](http://blogs.nologin.es/rickyepoderi/index.php?/archives/130-Integrating-runalyze-into-runnerup-Part-I.html). The basics are quite simple:

* A new auth method is created in order to let you change the connection URL (by default the public runalyze url is presented). I want to use my own runalyze.
* A new format RunzalizePost parses the database and writes the enormous post data runalyze needs.
* The synchronizer just uploads the activity (no more features).

There are some quirks with conversions of IDs, calories and so on but it works. The branch is my repo:

https://github.com/rickyepoderi/runnerup/tree/runalyze

I'm open to make changes or any other improvements (just I can't guarantee any schedule, sorry I have  very little free time). When you agree I can submit a pull request.

Thanks!

**Comment by mipapo** [comment]
@rickyepoderi The URI won't work with the upcoming release (v3.0).  `activity/add` instead of `call/call.Training.create.php` should be the new one

**Comment by rickyepoderi** [comment]
@mipapo  We can change it later or check the two urls at connection time (when configuring username and password). But if v3.0 is going to have an API (I hope it's a restful WS api) we can redo the synchronizer then and adapt it properly to the new version, making it as full-featured as possible. 

But the reality is that now it's impossible to upload my data to my own server, which annoys me a lot, I have to say.

**Comment by mipapo** [comment]
@rickyepoderi The API will come later with a version 3.* (Not directly with 3.0) (Yes it will be a RESTFUL WS API)

**Comment by rickyepoderi** [comment]
Fantastic! Then I think the better approach is trying to guess the URL when defining the synchronizer (try one, if 404 or something, the other). Later on, somebody should redo the synch for the API. Is there some alpha or beta for 3.0? Should I compile myself from current github?

**Comment by mipapo** [comment]
@rickyepoderi You could get a tester (write a mail to us). Latest master-dev package is available at dl.runalyze.com
Checkout the administration docs: https://docs.runalyze.com/en/latest/ (Also when you want to checkout directly from github)

**Comment by rickyepoderi** [comment]
Ok, I have just prepared my synchronizer to detect v2 and v3. Finally v3 also changes the way to login (it seems that runalyze uses now a new framework and everything is a bit different), so finally with the login the synchronizer can detect if the version is 3.x or 2.x and then call proper URLs. 

@mipapo  Can you confirm the same post fields are used in both versions? I have uploaded five or six activities and no problem with the upload (just changing the URL they were uploaded successfully).

The changes are incorporated to my branch if you want to test.

**Comment by mipapo** [comment]
>@mipapo Can you confirm the same post fields are used in both versions?
Yes!

**Comment by rickyepoderi** [comment]
I have released a debug version in case you want to test (please do a backup before, this is at your own rick). I have tested with my own phone. I'd  just test it and revert to the original app (restoring the backup). Here is the link:

https://github.com/rickyepoderi/runnerup/releases/tag/v1.54-alpha

Please connect to a runnalyze account (2.x and 3.x would be great) and import some activities. Remember that the URL should be changed if you want to test your own server (if your installation has a path, for example _http://192.168.1.2/runalyze_, you have to include the context too).

**Comment by rickyepoderi** [comment]
Has somebody tested the release or checked the code changes?
Are you interested in this?
Is it ok if I submit a pull request?

**Comment by mipapo** [comment]
Just a feedback from my site: It's working for me

**Comment by jonasoreland** [comment]
pull request sounds like a good idea!!

**Comment by Marx2** [comment]
As we have Runalyze synchronization merged and working, shouldn't we close this task?

Anyway, there's a small bug - all activities in Runalyze doesn't have sport type set to Running (it's empty). If it's not set, they are not used to calculate statistics.

**Comment by craftyguy** [comment]
Something is off a bit. When I try to sync an activity in runnerup that is 'biking', it gets synced to runalyze as a running activity.

**Comment by rickyepoderi** [comment]
@craftyguy Please open a new issue and be sure to include my name @rickyepoderi on it.

I always run (and I never cycling) so I personally have never tested another activity. In theory the column `DB.ACTIVITY.SPORT` from table `Constants.DB.ACTIVITY.TABLE` is read, transform into an `Sport.valueOf(dbValue)` and then if `sport.isCycling()` a `3` is returned. The magic 3 number is because in my ddbb was like this.

Please add to the bug if you are using your own server o the runalyze.com web.

**Comment by mipapo** [comment]
@rickyepoderi I think that "3" was your local sport id. You would need to read all the users sport names and map the sport name to your `sport.isCycling()` method. 

By the way: The next version of Runalyze will have some configureable "fixed" sport types. So we are getting closer to an API

**Comment by gerhardol** [comment]
Mapping included in v1.58 (but upload fails for other reasons, new issue?)

**Comment by Marx2** [comment]
It shouldn't be closed. As I understand it's about implementation of new
Runalyze API

śr., 9.08.2017, 01:27 użytkownik Gerhard Olsson <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
@Marx2 This issue was about synching to Runalyze
I suggest you open a new issue that clearly is about the planned upload API for future changes
