### ISSUE TITLE
Provide easy export of activities to SD card

### ISSUE THREAD

**Issue by piratenpanda** [jonasoreland/runnerup#303]
Maybe I missed it, but I can't seem to export my activities to SD card from the activity overview menu.

**Comment by RunningCl0ud** [comment]
@piratenpanda  Maybe You can find answers in #297?

**Comment by kas70** [comment]
I think there's no option to export to storage. Would be nice to have this.

**Comment by RunningCl0ud** [comment]
In My case I go to History and choose the activity relevant. Long press on menu button and then press Share activity. A box pops up and I can export in .gpx or .tcx with Gmail, Dropbox, Skype and so on. But yes, SD storage seems to be missing on my SG S5

**Comment by jonasoreland** [comment]
and the menu button only works for android 4.x (and below)

**Comment by RunningCl0ud** [comment]
I'm on 5.0 and it works fine?

**Comment by gerhardol** [comment]
The File exporter allows export of multiple activities
