### ISSUE TITLE
Map view buggy on activities overview

### ISSUE THREAD

**Issue by piratenpanda** [jonasoreland/runnerup#304]
I didn't move much but still the map shows a few white lines on blue background, which is probably not what it's supposed to show

**Comment by piratenpanda** [comment]
Seems to only happen when you don't move, when doing a normal run it displays just fine

**Comment by bagage** [comment]
Well yes, this is actually a know issue... If your activity does not contain GPS points, the map will zoom by default on some Africa isle... Can you confirm that your first activity has really 0 GPS point?

**Comment by piratenpanda** [comment]
I don't know how to check this as I can't export to sd card or is there a way?

**Comment by bagage** [comment]
I guess you are using device on Android lolipop / 5.0+? If yes, then you are affected by #298  but if you are not running it, go to your activity then click `...` and select `Share` option.

**Comment by piratenpanda** [comment]
Ok, yeah, 5.1.1 here

**Comment by bagage** [comment]
Hmm, can you try [that](http://stackoverflow.com/questions/27269579/menu-not-displayed-in-android-lollipop):

> Just needed to long press the task manager button and the menu options appears.

**Comment by piratenpanda** [comment]
nope, doesn't work

**Comment by bagage** [comment]
ok then #298 should be fixed urgently... do not have time for this yet, but maybe @paradix  or @jonasoreland  or someone will take a look at it.

**Comment by gerhardol** [comment]
The map implementation is updated and the other discussed issues are addressed too
