### ISSUE TITLE
Biking - too many points on the map

### ISSUE THREAD

**Issue by ziima** [jonasoreland/runnerup#305]
The activity map shows at least one point every 1 km which is probably too much for a bike ride. At least an option in settings to set the distance of these points would be improvement.

**Comment by dhiltonp** [comment]
Those points indicate each lap. Can you change the auto lap settings to
work for you?

**Comment by ziima** [comment]
I have autolap disabled. And before that it was set to 1609 m which is different length than on the map.

**Comment by bagage** [comment]
Yes map aumatically marks all kilometers. In `master` I changed that to show maximum 10 checkpoints to avoid this issue. Can you try it ?

-------- Message d'origine --------
De : Vlastimil Zíma <notifications@github.com> 
Date :  
A : jonasoreland/runnerup <runnerup@noreply.github.com> 
Objet : Re: [runnerup] Biking - too many points on the map (#305) 
 
I have autolap disabled. And before that it was set to 1609 m which is different length than on the map.

**Comment by ziima** [comment]
I'd love to, but since I'm new to Android, I don't know how to install version different from the one available in Play store. Is there any how to?

**Comment by bagage** [comment]
The easiest way would be to wait for a new release. @jonasoreland is releasing often and I think that a new one should be done pretty soon.

**Comment by gerhardol** [comment]
Note: This was changed to max 10 but is since 1.56 or so set to every lap.
(Limiting to 10 was maybe OK for autolap, but is undesired when you have intervals/manual laps.
