### ISSUE TITLE
Biking - Optimize autopause

### ISSUE THREAD

**Issue by ziima** [jonasoreland/runnerup#306]
It seems autopause sometimes behaves weird when used with biking, especially while biking in city. 

Few times I encountered a incorrect autopause when I stop on crossroads or lights for very short time. The pause happened after I started moving again and resumed when I was far from the stop.

An today the activity paused when I slowed down to about 15 km/h and haven't resumed since, even though I was moving.

**Comment by dracorp** [comment]
When I run last time in forest I lost about 3km(from 21) because of autopasue. But I think that is also hardware problem. My phone too often loses the GPS signal.

**Comment by nebmo** [comment]
I did the implementation.. I think it has two issues in AutoPauseTrigger class:
1. It does not seem to take into account if gps connection is lost (last known location is older than mAutoPauseAfterSeconds).
2. I think mHasStopped should be set to false if last speed is > autostopspeed && mHasStopped

Not sure if changing these two will solve both your issues..
*missing unit tests!*

**Comment by ziima** [comment]
Several trips later I think the issues are more caused by GPS than autopause algorithm.
