### ISSUE TITLE
Question: does GPS fix require at least 3 satellites to be accurate?

### ISSUE THREAD

**Issue by sasadangelo** [jonasoreland/runnerup#311]
Hi,
I am not sure if this is the right place to put my question. If no, please remove it. I do not have any contact point to reach you.
I am looking at source code of Runner Up and it is not clear to me why in GPSStatus class in onLocationChanged method you checks that:

} else if (mKnownSatellites >= mFixSatellites) {

where mFixSatellites is equal to 2 while it is well know that to have a GPS fix are necessary at least 3 satellites. What I am missing? Thanks.
You can contact me also to sasadangelo@gmail.com

**Comment by gerhardol** [comment]
The phone will not report a lock with less than 4 sats normally, this is an additional check that are a little confusing in my opinion too. (There are a lot of things that can be improved, dropping this.)
