### ISSUE TITLE
Feature request: merge heart rate data from FitBit

### ISSUE THREAD

**Issue by bernerbrau** [jonasoreland/runnerup#313]
I'm currently doing a lot of manual cross-referencing between fitbit heart rate graphs and workout maps to adjust my target paces. It would be nice if I could have this in one place to make this job simpler. 

It's not currently possible to get realtime heart rate data from a FitBit Charge HR/Surge device, and the technical team at FitBit seems highly opposed to offering this at any point in the future. Also, FitBit's historical heart rate APIs are currently not implemented and return empty results. However, this should be implemented at some point in the future. At that point, it may be desirable to merge historical heart rate data into a completed workout.

**Comment by darander** [comment]
Well, just in case someone actually wanted to have a look at this feature request. 

It appears that it's actually possible to get access to minute-by-minute and second-by-second data from Fitbit. (Well, after syncing the Fitbit device etc, so it would have to be post-training merge of the data from Fitbit).

See eg. https://community.fitbit.com/t5/Web-API/How-can-I-get-minute-and-second-level-data/m-p/324362#U324362 and for an example appliction (only using minute-by-minute data) at https://github.com/qslabs/FitbitIntraday/blob/master/FitbitIntradayScript.gs.

Though, I'm not really sure that it would make that much sense to have RunnerUp do the merging of the data streams. In my mind, it might be easier to do that as a post-processing after exporting the data, especially if / when #284 gets implemented.

**Comment by CharString** [comment]
IMHO this would be feature creep. I think RunnerUp should focus its attention to trying to be the best recording and guidance tool imaginable. Enable the best possible workouts.

Analysis is better left to desktop applications, where you have the screen real estate and processing power to do visualisation.

I see the proposed post-workout integration of external data as a task  in the data gathering and cleaning step of such an analysis software. 

RunnerUp already has extensive support for real-time heart rate recording. This fitbit scheme doesn't add to the quality of a workout, just to its analysis afterwards.

**Comment by gerhardol** [comment]
This not what RU should do (if someone implents support, I guess it could be merged still..)
