### ISSUE TITLE
Feature Request: Add rest distance and pace

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#315]
Wow!  Blown away by this app which is the only one I could find to easily do intervals with a mix of distance for laps and time for rests.  However, at the end of the workout it shows each (rest) as 0m whereas I am actually jogging for that recovery time.  (This also results in jumps/gaps on the map in RunKeeper after an upload, even though the route is joined up in the RunnerUp map).  I don't see why the distance/pace/heartrate cannot be captured during that period in the same way as the (warm up) and (cool down) segments are so that is my suggestion.

I have only just started using this so maybe I am not using it correct.  Or maybe this is actually just a bug.  My java is "novice" and I am a bit lost looking around the github repository but I'd have a go at fixing it myself if I could find the code!

Any clarification on this would be great.

**Comment by nebmo** [comment]
Could be that it is missing for intervals. I usually create my workouts at Garmin connect. Then you can download and edit them in RunnerUp (advanced tab)

**Comment by jonasoreland** [comment]
FYI: distance and time are saved for RECOVERY but not for REST.
If you make an advanced workout (in the app or on garmin site), you can
select for yourself what you want.

In the interval-tab it creates a REST (unless you set a distance and click
convert-rest-to-recovery in advanced settings).

I think this can be closed.
Wdyt ?

/Jonas

**Comment by CharString** [comment]
@jonasoreland I understand not recording distance and speed during REST eliminates the GPS jitter from that step. But heart rate isn't stored either, making [heart rate recovery](https://en.m.wikipedia.org/wiki/Heart_rate#Heart_rate_recovery) measurement during an activity impossible.

PS Had a look and that issue is #66

**Comment by jonasoreland** [comment]
Hi,

I (think, 99% sure) that GPS and heartrate is *measure* but not stored.
Hence heart-rate-recovery should be possible...

/Jonas

**Comment by Cagier** [comment]
I can see both sides of the argument.  I get the point that a "rest" is different from a "recovery" but if it is meant to be an inactive rest then why record the distance under a "distance rest" but not under a "time rest"?  It is nicer to see your total distance at the end of the workout with no gaps on the map.

However, as I can achieve what I want with the advanced time I am happy that there is a workaround.
I still think it would be a nice feature but there are probably higher priority items so if you want to close it then that is fine with me.

**Comment by gerhardol** [comment]
Cannot find any obvious improvement from this discussion, closing

**Comment by davidedelvento** [comment]
I think the difference between recovery and rest (for the app) should be documented somewhere
