### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by Erdener** [jonasoreland/runnerup#323]
This ise my first time contributing to a project as a translator. Please pull the Turkish translation from Transifex.

**Comment by jonasoreland** [comment]
done

**Comment by Erdener** [comment]
In the latest release not all the translation seem to be applied. I guest this ise because there are more that one Turkish translation topics. 

The one that I contribute and nearly completed is here: https://www.transifex.com/runner-up/runner-up-android/translate/#tr
