### ISSUE TITLE
Samsung S5 - Polar HRM N2965 - Not connecting

### ISSUE THREAD

**Issue by zaeiou** [jonasoreland/runnerup#325]
Trying to connect a Polar Bluetooth HRM N2965 and it does not want to connect.

Read the previous issue threads and tried the proposed solution, ie installing BLE, still does not worked.

Used the "Bluetooth SMART (BLE)" and waited... but never found it?

This app is great, can't wait to use it, currently I am using runtastic and my Polar HRM works with it but Runtastic does not as feature rich...

Great Job Jonas!

**Comment by PanderMusubi** [comment]
This might be related to https://github.com/jonasoreland/runnerup/issues/334

**Comment by gerhardol** [comment]
The N2965 seem to be a WearLink, not BLE sensor like the H7
