### ISSUE TITLE
Owncloud upload

### ISSUE THREAD

**Issue by acht** [jonasoreland/runnerup#327]
Hallo,

an automated upload to owncloud (to a preselected folder as gpx with name based on time) would be a nice feature.

Thanks

**Comment by dradux** [comment]
@acht I agree, this would be a great new feature.

**Comment by tbdal** [comment]
@acht i totally agree, too. maybe there is even a way to sync it with the calendar?

**Comment by acht** [comment]
More general would be a integration with the standard android calender (which can be synced by the owncloud app) or a connection to a standard webdav/caldav calender (e.g. a owncloud server). But this would be an other feater then the file upload.

**Comment by jonasoreland** [comment]
why could you sync with a calender ? what does that mean ?

/Jonas

**Comment by tbdal** [comment]
before using runnerup i was used to create a manual entry in my android calender looking like "running, x km, hf yyy" place "zzz", which is synced via caldav to owncloud.
this was helpful to get an overview of the training, without having the need to sync with an external service but having all data on my own systems.
my vision would be to have a combined sync with one click: a) upload gpx to owncloud & b) entry in the calendar or even having an owncloud app which allows you to use the standard calendar&file system to display training over time

**Comment by Vebryn** [comment]
:+1:

**Comment by speendo** [comment]
+1 ;-)

**Comment by 31416r** [comment]
+1 :-)
