### ISSUE TITLE
Logging treadmill activity (interval, ...) with heartrate data and manual distance entry

### ISSUE THREAD

**Issue by lduros** [jonasoreland/runnerup#331]
Does anyone use RunnerUp to track treadmill activities? I have a compatible heart rate monitor and tend to do my hill repeats on the treadmill because it is convenient (no downhill before repeats.) Ideally this activity could be uploaded to Strava/Runkeeper and be representative of the activity (manual entry of the distance from the treadmill, heartrate logged by RunnerUp, ...)
I may be trying to add such a feature to RunnerUp, but I want to make sure this isn't something that's already possible (There are so many features in the app, great job!)

Loic

**Comment by lduros** [comment]
I should add: from my experience when using basic run on treadmill with hr, uploading the activity to Strava results in no data because there's no meaningful position data tied to the heartrate. This may be only an issue with Strava though and not other services.

**Comment by jonasoreland** [comment]
currently not supported...
cool idea

is the hr data coming from the treadmill, or from your own hr-belt ?
in my office there are special hr-belts that are somehow connected with the
treadmill, not sure how that works...

/Jonas

**Comment by lduros** [comment]
I meant using my own HR belt connected to my android device (A Zephir HxM Smart), which data is already collected by RunnerUp without issue for regular runs. Alright, I'll see if i can work on this on my own. Thanks!

**Comment by achimwagenknecht** [comment]
Would love this one, too. Just the possibility to record the heart rate without recording a gps track.

**Comment by gerhardol** [comment]
See #533
