### ISSUE TITLE
Activity autopauses frequently (every couple of seconds)

### ISSUE THREAD

**Issue by cweickhmann** [jonasoreland/runnerup#343]
Hi all!

I like the app and am using it with Sony Xperia Z2, Android 5.1.1.
It worked fine three times (out of which on with a BT BLE+ heartrate monitor belt). The fourth time, it started inserting random stop/pause points but continued tracking. Eversince, it randomly pauses the activity after a few seconds.
It does not seem to be a GPS issue, since tracking with e.g. OSMTracker works well.
There seems to be no difference between with and without heartrate monitoring as well.

I'm not sure but the only thing I could figure at the moment was activating a target pace once. Eversince it does not track properly anymore.

Any ideas? It may be a settings issue, but to me it seems like the code that decides whether or not to pause the activity is sort of overly impatient.

Bests,
Christian

**Comment by nebmo** [comment]
Hi, i was the one that implemented autopause a year ago. Until recently I haven't had any issues with it but now i do. I don't know what is causing it...

**Comment by cweickhmann** [comment]
Hi! But you have the same issue? And didn't change the code in the last couple of days?
I'm absolutely no expert in Adroid, but my first suspicion would be a change in the GPS API or any other API you used in your code...
How difficult would it be to include a settings item to deactivate auto-pause?

**Comment by nebmo** [comment]
I'm currently trying to add some unit tests for this and see what i can find.

There is a setting to disable autopause (Settings / AutoPause)

**Comment by jonasoreland** [comment]
My experience/guess is this:
- Auto-pause works OK if GPS is good.
- Auto-pause works super poor if GPS is not so good.

I sometimes get a workout with really poor GPS, (when I look at map
afterwards it looks like I've been "all over")
When this happens, it's not unusual that it auto-pauses 25 times in 40
minutes...very annoying.

Most of the time GPS is good, and auto-pause does nothing...(though it have
a tendency of auto-pausing immediately when I start the workout).

The workouts with really poor GPS happens like once every 2 weeks for me.

---

I think that auto-pause should be made more resilient to poor/shaky
GPS...and that will remove this problem.

/Jonas

On Mon, Oct 19, 2015 at 12:17 PM, Niklas Weidemann <notifications@github.com

**Comment by nebmo** [comment]
Not sure how it can be implemented though without using accelerometer.
http://labs.strava.com/blog/improving-auto-pause-for-everyone/

**Comment by kroeckx** [comment]
Today it was doing the "Activity paused - activity resumed" for me every 5 seconds. It was actually just pausing it every 5 seconds first and I had to press resume all the time. The GPS said that it was tracking 10 out of 14 satellites and had a normal error estimate.

**Comment by gerhardol** [comment]
Auto pause and voice coach uses the same pace data, this is related to #465

**Comment by davidedelvento** [comment]
This is also related to #598
