### ISSUE TITLE
Activity tracking: Background service

### ISSUE THREAD

**Issue by jerriclynsjohn** [jonasoreland/runnerup#346]
Once the activity tracking starts, I prefer to play my music. It works perfectly fine if I do not close it. Can we not make this run in the background once the user closes it and give provision to open the application with a "Running activity" notification.

The "activity paused", "activity resumed" audio cues are a pain in the ass, considering the fact that I'm playing loud music in between. I found the same #343 in here, as well.

**Comment by jonasoreland** [comment]
I don't understand

1) I run with music every time ?
2) once the activity is started, it will run until it's stopped. no matter
if put in background or not
3) i think there is a knob to silence also the "activity paused", "activity
resumed" cues.
if there is no such knob, i think you should file a feature request for
*that*

/Jonas

**Comment by jerriclynsjohn** [comment]
True the music application runs in the background and doesn't affect the working of RunnerUp, but yeah I was suggesting a feature like once we start the activity tracking in the RunnerUp application, even if the user unknowingly closes the app - it should run in the background and be present in the notification drawer giving the user the ability to reopen the app.

**Comment by jonasoreland** [comment]
it already does this!

once activity is started you can only stop it by pressing the STOP button

**Comment by jonasoreland** [comment]
i'll close this,
reopen if you want to
