### ISSUE TITLE
Cannot edit workouts

### ISSUE THREAD

**Issue by embeh** [jonasoreland/runnerup#352]
Despite the GUI label "Manage workouts \ Download/edit/remove workouts" in Settings, there seems to be no way to modify an existing workout. All you can do is delete what you have and start over, which is a pain if you have created a complex workout.

**Comment by RunningCl0ud** [comment]
Therese is no problem with my SG S5? What kind of Android do you use?

**Comment by jonasoreland** [comment]
existing workouts can be modified directly on the start->advanced screen,
there you can (atleast) modify e.g repeat count, phase, duration etc

have you tried that ?

--

But I agree, it would be nice if you could get to edit (rather than just
create) a workout.

/Jonas

**Comment by embeh** [comment]
@RunningCl0ud This is on Android 4.4

@jonasoreland Yes, I can modify the numbers but cannot add or remove a step

**Comment by RunningCl0ud** [comment]
@embeh Ok I see what you mean. It could be an extra feature to "edit" f.ex put in an extra step somewhere in the existing workout. That does not seem to be doable for the moment and I am on Android 5.0. 
If you have Garmin Connect you can easily edit the workout there. But I see your point and it is a good one I think. 
And if you just want to modify existing steps @jonasoreland s idea should work?

**Comment by embeh** [comment]
@RunningCl0ud Exactly. I recently had two cases where I created a workout with maybe 15 steps (more than could fit on a single screen, with several repetitions), and each time the app would insert an additional step somewhere above - which I did not notice until afterwards. All I could do then was to set these back to 0 minutes. But the voice coaching would still deal with those steps, which was all somewhat confusing. I realize I can edit the json file but that is not really what you want an app user to do, right?

**Comment by davidedelvento** [comment]
I think this whole way of editing workouts should be refreshed. See #567 

@davidedelvento

**Comment by gerhardol** [comment]
This is handled in #587 
Closing this issue

**Comment by davidedelvento** [comment]
@gerhardol I think #587 is totally different: that is not for long-term editing but for throw-away changes done while running.
This is more for things like #567 #583 and similar things I'm working on now. No need to reopen, but just making it clear we're talking about different things.

**Comment by anusser** [comment]
First, thanks a lot for this great app!

As there hasn't been any activity in this issue since a few years, I just wanted to bump it. For me this issue is still there and the only drawback in an until now flawless app.

**Comment by gerhardol** [comment]
It is possible to change the number of steps and types for a workout. 
Is it really that important to add or remove new steps to a workout?

**Comment by Upabjojr** [comment]
> For me this issue is still there and the only drawback in an otherwise flawless app.

100% agree

**Comment by anusser** [comment]
Wow, that was quick. Thanks a lot for giving it a shot @Upabjojr.

@gerhardol, the main reason why this is an important enhancement in my opinion is that it causes a lot of frustration if one  creates a workout with a small mistake and then needing to take the time to completely recreate it again just to fix this small mistake. So, it boils down to avoiding frustration.

**Comment by Upabjojr** [comment]
> I am completely fine though with this separation between just modifying parameters on the main screen and editing the workout on a separate screen. That certainly makes sense.

It makes more sense to have a read-only screen and a full-edit screen.

**Comment by anusser** [comment]
Thanks a lot to both of you, @gerhardol and @Upabjojr, for investing your time on resolving this issue! :)
