### ISSUE TITLE
Connected account button says "Connect".

### ISSUE THREAD

**Issue by jonfre** [jonasoreland/runnerup#355]
RunnerUp version: ad9cc1b
Android Version: 5.0.1

Test Case
1. Go to accounts screen.
2. Connect to an unconnected account.
3. When getting back to the accounts screen, verify the new account has an "edit" button (not a "Connect" button). Pushing the button should open the account screen.

3 fails. 

If the accounts screen is reopened the button is correct.

**Comment by jonfre** [comment]
I did some debugging and found that in `org.runnerup.view.AccountListActivity.AccountListAdapter#bindView`, auth_config is missing in `ContentValues tmp` which makes the added synchronizer (`mSyncManager.add(tmp)`) not consider itself as configured, hence the "Connect" button further down.

**Comment by gerhardol** [comment]
This handling is rewritten for #590 and similar and should be working with those (I believe it is working in later releases already)
