### ISSUE TITLE
Jaggy GPS track?

### ISSUE THREAD

**Issue by embeh** [jonasoreland/runnerup#356]
Ever since I switched from Runtastic to RunnerUp, I noticed that the recorded GPS track data is very jaggy when zoomed in. It always looks as if the track is only measured east-west (horizontal) for a bit, and then suddenly a jump in north-south occurs, just for another perfectly horizontal bit and so on. (here is a screenshot 
![screenshot_2015-11-16-18-25-38](https://cloud.githubusercontent.com/assets/3431046/11189300/ad479b58-8c8f-11e5-8b4b-b2eaf4139114.png) -- for reference, the track shown covers about 350 Meters from left to right)

Recently, I also detected a noticeable difference in distance measurement between RunnerUp and an officially measured track (RunnerUp reported about 10% longer distance).

So I wonder whether there is a common reason for these two and what to do about it? This is on a Samsung S4 running Cyanogenmod 11, based on Android 4.4.4

FWIW, emailing myself the activity in GPX format and importing it into Google Earth without any filtering will produce a very dense and smooth track (that deviates of course from the real track a bit) that shows none of the jaggedness:  
![2015_11_16_18_36_58_google_earth_pro](https://cloud.githubusercontent.com/assets/3431046/11189596/3910a944-8c91-11e5-920b-f0f36a867d80.png)

so maybe this is only a display problem in RunnerUp?

**Comment by jonasoreland** [comment]
1) the jagged graph came when we switched to open street map (from google
maps).
i don't know if there is a problem with how we use it, or if it's a problem
with the map it self.

2) for me the 10% varies, sometimes it's long and sometimes it's shorter,
i attribute it to GPS imprecision, or me simply not running exactly the
same each time.

**Comment by bagage** [comment]
1) I think MapBox do not smooth lines by default, hence the very rough curve when zooming in. But I do not think it's the root issue in there.

**Comment by embeh** [comment]
Please note that the GPX data is fine, without any smoothing. There is one measurement for every second, so the resolution of the track is much higher than what is shown in the map..

**Comment by antonkratz** [comment]
I have the exact same issue as reported by embeh in the first post.

**Comment by gerhardol** [comment]
Mapbox was updated in v1.56 (or slightly earlier), all points are shown on the map now

**Comment by embeh** [comment]
Thank you, seems to be fine now!
