### ISSUE TITLE
Crash in custom workout with sequence warmup->rest->active->cooldown

### ISSUE THREAD

**Issue by bernerbrau** [jonasoreland/runnerup#358]
I created the following workout for a 5k race last week:

1. Warm Up 5:00 (before the race)
2. Rest Until Pressed (waiting for race to begin)
3. Active 5000m @ 8:00/mile (the actual race)
4. Cool Down until Pressed

What I expected to happen was to have a 5-minute warm-up, followed by a rest period that I could advance when ready, time my race, and give me a cool down period. 

What actually happened was it didn't start the warm-up timer at all, and it displayed 3 rest steps.
![screen shot 2016-01-05 at 4 06 35 pm](https://cloud.githubusercontent.com/assets/3019392/12128991/74d567b0-b3c6-11e5-9888-c4b8ea90bbc8.png)

When I manually advanced it to the rest, it crashed. 

(I switched over to Basic and set my target pace before crossing the start line, so I was able to track my race. Anyhow...)

It seems like a Warm Up before a Rest is not allowed, but this should be disallowed when building the workout, not during the workout. Either this, or there is a bug which needs to be identified and corrected. 

I forked RunnerUp and ran it in Android Studio to replicate. The [workout json](https://github.com/jonasoreland/runnerup/files/79126/crashing.workout.json.txt) and [logcat](https://github.com/jonasoreland/runnerup/files/79117/log.txt) are attached.

**Comment by jonasoreland** [comment]
greate bug report, fixed with https://github.com/jonasoreland/runnerup/commit/1b5ea81f5dc85c2c225c35795fb0baef9917fa68
