### ISSUE TITLE
Crash after saving if auto upload disabled

### ISSUE THREAD

**Issue by derivator** [jonasoreland/runnerup#359]
I linked a runtastic account and enabled automatic uploading. Used it for a while, but the upload only works some of the time and sometimes has the wrong activity type set (running instead of biking), so I disabled automatic upload. From there on, the app would always crash after saving an activity. Turning automatic uploads back on fixes the crashing.

**Comment by gerhardol** [comment]
Runtastic synch is no longer working and will be hidden/disabled in a future release with #590
