### ISSUE TITLE
Gitter chat (or IRC)?

### ISSUE THREAD

**Issue by jluttine** [jonasoreland/runnerup#360]
Hi, and thanks for the great app! :)

I have some questions I'd like to casually discuss with other users. Would it be possible to set up Gitter.im chat room (very easy to set up) and provide a link to it in README? Gitter.im integrates smoothly with GitHub.

The chat would then exist here:
https://gitter.im/jonasoreland/runnerup

Alternatively, an IRC room but I noticed you had already rejected that suggestion in an other issue.

**Comment by bagage** [comment]
I wasnt aware of Gitter but it looks an interesting alternative to irc!

**Comment by jluttine** [comment]
It is possible to integrate Gitter with IRC. At least, I'm using Gitter from my IRC client.

**Comment by jonasoreland** [comment]
I rejected IRC as (normally) leaves persons not present without option to
read what was said.
Does Gitter provide history ?

/Jonas

**Comment by jluttine** [comment]
Gitter provides full history for all users (even new ones).

**Comment by nebmo** [comment]
Do it Jonas :)

**Comment by jonasoreland** [comment]
done. i think :)
