### ISSUE TITLE
I want to use the code of tracking in eclipse project.

### ISSUE THREAD

**Issue by AnjanaNm** [jonasoreland/runnerup#364]
Hello All,

I have read in README.md that "**Eclipse is currently broken**."  Is it possible to refer android studio code to create eclipse project for tracking. 
I'm not getting from where should I start. 
Please reply.

**Comment by AnjanaNm** [comment]
Anybody there. Its quite urgent.

**Comment by nebmo** [comment]
I don't think anyone here is using eclipse anymore. Can't you use android studio instead? :)

**Comment by AnjanaNm** [comment]
Actually I can't use studio. I need to integrate tracking code in existing eclipse project.

**Comment by AnjanaNm** [comment]
Please reply if I can refer android studio's tracking code to integrate in eclipse project.

**Comment by johnsie** [comment]
Doesnt make much sense to be using eclipse for andriod development in 2016, but here's something you could try:

http://stackoverflow.com/questions/18130157/can-i-import-an-android-studio-project-to-eclipse/29214033#29214033

Bear in mind that this project containss hundreds of files and several packages and you will need to add each one manually in the correct manner.

Easiest option, get in you DeLorean, hit 88 mph and come join us in 2016 where everyone is using Andriod Studio.

**Comment by AnjanaNm** [comment]
Thanks
