### ISSUE TITLE
MapMyRun synchronization broken

### ISSUE THREAD

**Issue by joemccall86** [jonasoreland/runnerup#366]
It looks like they may have killed support for the v3.1 api used in this app, in favor of the v7.1 version. I cannot log in, and when I try to query the API endpoint manually I get a 504 Gateway Timeout.

**Comment by plutocrat** [comment]
I concur. Can't log into Mapmyrun to register account. Can't upload runs.

**Comment by gerhardol** [comment]
MapMyRun synch will hidden/disabled in a future release when #590 is merged
