### ISSUE TITLE
Not getting value of Last Fixed satellite 

### ISSUE THREAD

**Issue by AgNm** [jonasoreland/runnerup#369]
Hello,

I have created a new android studio project and implemented tracking code in it. Currently I'm getting value of Available Satellites but not for fixed satellites. It's value is always 0.
I have added all the required permissions. I have implemented code as it is, except the layout part because I want to track location in background.
Will you please let me know what I'm missing? 
Please help.

Below is the code :

@Override
public void onGpsStatusChanged(int event) {
        if (locationManager == null)
            return;
           android.location.GpsStatus gpsStatus = locationManager.getGpsStatus(null);

        if (gpsStatus == null)
            return;

        int cnt0 = 0, cnt1 = 0;
        Iterable<GpsSatellite> list = gpsStatus.getSatellites(); 
        for (GpsSatellite satellite : list) {
            cnt0++;
            if (satellite.usedInFix()) {
                           cnt1++;
            }
        }
        mKnownSatellites = cnt0;
       
        mUsedInLastFixSatellites = cnt1;
        
        if (listener != null)
            listener.onTick();
    }

**Comment by CtiAndroid** [comment]
i also getting same problem.

**Comment by AnjanaNm** [comment]
This issue is resolved. Actually I was testing this in my office premises so I was not getting count. When I tested the app while I was travelling, it showed the count around 9-10.
