### ISSUE TITLE
Not calling onLocationChanged from Tracker Service

### ISSUE THREAD

**Issue by AgNm** [jonasoreland/runnerup#370]
Hello,

I have created a new android studio project and implemented tracking code in it. Currently I'm getting value of Available Satellites and fixed satellites. 
I have added all the required permissions. I have implemented code as it is, except the layout part because I want to track location in background.
Here I'm getting location from GPS Status onLocationChanged but onLocationChanged is not getting called from Tracker Service. Please help.
Will you please let me know what I'm missing? 

`@Override
 public void onLocationChanged(Location arg0) {
        onLocationChangedImpl(arg0, false);
    }`

**Comment by AnjanaNm** [comment]
Can anyone please help. I have debugged and I found that instead of `RESULT_PENDING` , I'm getting `RESULT_OK` state when "setup()" method is called from "connect()" method :

`public void setup() {
        switch (state.get()) {
            case INIT:
                break;
            case INITIALIZING:
            case INITIALIZED:
                return;
            case CONNECTING:
            case CONNECTED:
            case STARTED:
            case PAUSED:
            case ERROR:
            case STOPPED:
                assert(false);
                return;
            case CLEANUP:
                /**
                 * if CLEANUP is in progress, setup will continue once complete
                 */
                nextState = TrackerState.INITIALIZING;
                return;
        }

        state.set(TrackerState.INITIALIZING);

        TrackerComponent.ResultCode result = components.onInit(onInitCallback, getApplicationContext());
        if (result == TrackerComponent.ResultCode.RESULT_PENDING) {
            return;
        } else {
            onInitCallback.run(components, result);
        }
    }
`

**Comment by jonasoreland** [comment]
are you doing this on real phone or in emulator.
there is special code to make it work in emulator...
/Jonas

**Comment by AnjanaNm** [comment]
I'm testing it on real device.

**Comment by AgNm** [comment]
Resolved. nextState was NULL. So currently set it hardcoded. 

nextState = TrackerState.CONNECTED;

**Comment by jonasoreland** [comment]
??
