### ISSUE TITLE
Regarding flow of the code

### ISSUE THREAD

**Issue by AgNm** [jonasoreland/runnerup#371]
Hello All,

I've created a Phonegap project in android studio. I'm trying to implement the location tracking code. As I'm creating project in phonegap I had to remove all the layout related code. But I'm not understanding the flow of  the project. 

I've got the available & fixed satellites. Getting location from both GpsStatus & Tracker Service. But I'm unable to understand how states like Start, Connected, Connecting etc. are changing . 

Can anyone please suggest what should I do or study so that I can properly understand the flow of the code. I really need your help.

**Comment by jonasoreland** [comment]
what are you trying to do ? what is your purpose ?

**Comment by AgNm** [comment]
I want to implement the location tracking code along with distance calculation. I want to do this in background.

**Comment by jonasoreland** [comment]
Why?
All of that is already implemented!

**Comment by AgNm** [comment]
Yes all these things are already implemented and i want to use that code but as I want to do this in Phonegap in background, I have removed all the layout related code. I'm facing issues due to this.
