### ISSUE TITLE
Feature Request: Filter out zero bpm heartrate

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#373]
Hi guys
Sometimes I get the odd gap in the HRM, which is not a big issue.  However, when you go to view a run on strava or runkeeper the whole graph is skewed as there are huge dips down to 0 bpm.  If these could be filtered out (possibly by just taking the average of the previous and the next or even just duplicating the previous) then it would make post-run analysis much easier as the scale would then be the real min/max.
Cheers,
Keith

**Comment by wbrenna** [comment]
This might be related to issue #279 - an exponential smoothing might be suitable.

**Comment by Cagier** [comment]
Looks like that might be a solution alright.  I'll close this issue on that basis.

**Comment by jonasoreland** [comment]
Actually I think that special handling of 0 bpm is needed...i.e when connection to heart rate belt is lost.

**Comment by Cagier** [comment]
Well, I'm happy to re-open it on that basis then. ;)

**Comment by gerhardol** [comment]
Related to PR #477 handling as duplicate
