### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by speendo** [jonasoreland/runnerup#375]
Hi!

For analytic and testing purposes, I'd like to export the data RunnerUp collected about my last workouts.

Is there a way to do so? Or, in other words: where can I find the database/the files in which RunnerUp stores the information about my workout?

Thank you!

**Comment by gerhardol** [comment]
Related to https://github.com/jonasoreland/runnerup/issues/298
The app implements editing, exporting (and deleting) of activities but a Menu button is required on Android >= 5.

**Comment by speendo** [comment]
thanks! that worked
