### ISSUE TITLE
hr monitor connection error

### ISSUE THREAD

**Issue by 19github9** [jonasoreland/runnerup#377]
Hi RunnerUp staff and Hi Jonas,
I would make you my compliments for the job; I love it.

I would ask you for a problem relative to hr monitor.
I have a MOTO 360 v2 smartwatch connected to LG G4 but I'm not be able to connect the device to hr monitor (I'm using RunnerUp app published on google play).
I've tried to connect it by each one of elegible option (Bluetooth SMART (BLE), Zephyr, Polar WearLink, SportTracker HRM v1, ANT+).
While the first and the last entry don't find the device, the others find it but, when I'm gonig to connect it, all they return me a connect failed!

I'll be very happy if you can help me.
Have you a very nice day

**Comment by jonasoreland** [comment]
this is a feature request,
using a wear device as heartrate monitor is currently not support...(but might be!)

**Comment by kngharv** [comment]
1.  I just want to express I have the same desire of using my Android Wear device as my heartrate Monitor

2. out of curiosity.  what kind of things need to be done in order to get this feature implemented?

**Comment by jonasoreland** [comment]
1) using android wear as HR-monitor is currently not supported.

2) I think first thing to get it working is finding documentation showing
how it should be done :)

/Jonas

**Comment by gerhardol** [comment]
#253
