### ISSUE TITLE
Upload to Facebook not working

### ISSUE THREAD

**Issue by rstruminski** [jonasoreland/runnerup#382]
I connected the app to Facebook - the connection seems to be okay.
However, when I try to upload an activity, I only see an "uploading" window very, very briefly, and that's it. There's no confirmation, and nothing shows up in my Facebook.

Things I've tried:
- I checked my Facebook activity log. There's nothing there.
- I disconnected and reconnected the app to Facebook. Didn't help.

(Samsung Galaxy S5 Neo)

**Comment by johnsie** [comment]
Same issue here. I think I have a development environment set up for runner up on my laptop, but the app is probably linked to a specific Facebook application.

**Comment by gerhardol** [comment]
Seem to be a problem for me too
Will hide/disable Facebook sync, no change planned #590
