### ISSUE TITLE
Bluetooth LE support without Google Play services

### ISSUE THREAD

**Issue by somehowdifferent** [jonasoreland/runnerup#383]
Hi,

I installed RunnerUp 1.51 from F-droid, have been out for some rides and was really enjoying it. Everything you want from a fitness tracker and FOSS. Thank you.

I just bought two different Bluetooth LE heart rate monitor straps and none of them is recognized by RunnerUp. I am running CM13 without any Google Play services. Is Gapps essential for Bluetooth LE support? If so, would it be possible to implement this function with plain Android?

Thank you for your time.
Carsten

**Comment by jonasoreland** [comment]
i don't think there is any connection between BLE and gapps, i.e it should
work.

how do you do to "pair" them ?

/Jonas

On Thu, Apr 21, 2016 at 12:00 PM, somehowdifferent <notifications@github.com

**Comment by somehowdifferent** [comment]
Hi Jonas,

it was an issue with BLE device itself. It needs to record a proper heartrate to broadcast a BLE signal. Hence, just holding it and trying to connect won't do. It's just inactive.

Sorry for bothering you.
