### ISSUE TITLE
[Feature Request] Graph view for cycling: Speed instead of pace over time

### ISSUE THREAD

**Issue by somehowdifferent** [jonasoreland/runnerup#384]
Hi,

I installed RunnerUp 1.51 from F-droid, have been out for some rides and was really enjoying it. Everything you want from a fitness tracker and FOSS. Thank you.

Here's one thing, I'd like to point your attention to. Since cycling is supported as a recording option, would it be possible to adapt the graph view in this case. Instead of showing the pace ( a thing exclusively popular in running community), cyclist would rather appreciate a speed over time representation.

Thank you for your time.
Carsten

**Comment by jonasoreland** [comment]
this is a good (but not new idea).
there is a bunch of things that would make most sense to configure per sport.
see #27 
i'll close this as duplicate
