### ISSUE TITLE
Licence and source code for samsung_ble_sdk_200.jar

### ISSUE THREAD

**Issue by krt16s** [jonasoreland/runnerup#385]
Could you please state the licensing terms for `samsung_ble_sdk_200.jar` and provide a link to the source code?

**Comment by rickyepoderi** [comment]
I've been investigating this issue for a while and my findings are the following:

* This library is for the Bluetooth Low Energy client API (runnerup uses it for the Heart Rate monitor). It seems that BLE was integrated in stock Android in 4.3 but previously (for 4.2) samsung gave this library for some devices.
* It is used only inside the class _SamsungBLEHRProvider_ for HR monitoring provider, used for devices 4.2 with the jar installed in the system (S4 for example). It is used only for compiling, not included in the app.
* The library was provided by samsung but not anymore. You can check the web archive page: http://web.archive.org/web/20131027012145/http://developer.samsung.com/ble
* Now it can be downloaded via github: https://github.com/cjhuo/Android-Samsung-Ble-APIs-Bluedroid
* I was unable to find the sources (I think the library was never open sourced) and no license is specified.

If this library is a problem for f-droid it would be possible to add a project property switch to not compile that provider. Something like:

    ./gradlew build -Porg.runnerup.hr.disableSamsungBLE=true
    or
    ./gradlew build --project-prop org.runnerup.hr.disableSamsungBLE=true

Obviously some modifications are needed to load the _SamsungBLEHRProvider_ using reflection when the class is not compiled. I can add the modifications if you think is useful (I want runnerup in f-droid). Another option is delete this provider completely. But first I need to know if the library is a problem for f-droid (I don't know the rules of the repository).

Comments are welcome!  :smile:

**Comment by krt16s** [comment]
Well, it's a non-free (legal), non open-source (tech) binary. I don't think we should keep that within f-droid. So any plans of getting rid of it, either by removing, replacing or excluding it from a special build flavor, would be welcome.

To make sure: This is used only for Samsung devices with 4.0 to 4.2.x? (We dont build the froyo flavor iirc, so that wouldnt concern me).

**Comment by rickyepoderi** [comment]
The web archive pages says the following: "The Samsung BLE SDK is only supported on Android 4.2, 4.2.1 and 4.2.2. Please use the global Google BLE API for Android versions 4.3 and later. "

So I think it is only available for 4.2.x and, obviously, the device should be a samsumg with BLE (S4 seems to be one of the terminals that support it). If the users have upgraded the terminal to a newer android (4.3 and above) the stock android implementation is used.

@jonasoreland or any other member, what do you think? Is the project property a valid option? Or do you prefer removing the provider completely?

**Comment by jonasoreland** [comment]
Project property sounds good to me

**Comment by rickyepoderi** [comment]
Hi,

I've been working on this and the result is in this branch:

https://github.com/rickyepoderi/runnerup/tree/remove-samsung-ble

The basics ideas are the following:

* The _checkLibrary_ method is moved out from _SamsungBLEHRProvider_ to general _HRManager_ to check the dependency without the class.
* The _SamsungBLEHRProvider_ is created using reflection instead of doing a common new over the constructor. This way the _HRManager_ can compile without the _SamsungBLEHRProvider_ class.
* Finally I added a project property called _org.runnerup.hr.disableSamsungBLE_ to avoid download the jar and exclude the _SamsungBLEHRProvider_ class from the project.

I've tested the f-droid version (without the jar and it compiles and runs ok). The problem is that I cannot test the version with the _samsung_ble_sdk_200.jar_ library (I don't have such a phone and version). I've just tested that the creation using reflection works (using another provider instead of samsung one).

Please check if you like the idea and, if someone is using a phone that depends on _samsung_ble_sdk_200.jar_, it would be nice to try the branch out.

Thanks!

**Comment by rickyepoderi** [comment]
Have you seen the modifications? What's your opinion?

**Comment by jonasoreland** [comment]
LGTM
make into a PR and I'll merge it

**Comment by gerhardol** [comment]
A link to the source in About in the app
https://github.com/fishkingsin/BLEDialogTool/
License here too: https://github.com/jonasoreland/runnerup/blob/master/app/assets/samsung_ble_license.txt

Also #602 that adds the lib as Git LFS instead
The lib will be removed in future development

**Comment by krt16s** [comment]
The linked repo references the jar file, which does not contain source files:

````
 inflated: META-INF/MANIFEST.MF
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattCallback.class
 inflated: com/samsung/android/sdk/bt/gatt/g.class
 inflated: com/samsung/android/sdk/bt/gatt/MutableBluetoothGattDescriptor.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattDescriptor.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattCharacteristic.class
 inflated: com/samsung/android/sdk/bt/gatt/f.class
 inflated: com/samsung/android/sdk/bt/gatt/d.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGattServerCallback$Stub.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGatt.class
 inflated: com/samsung/android/sdk/bt/gatt/h.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattServerCallback.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGattCallback.class
 inflated: com/samsung/android/sdk/bt/gatt/MutableBluetoothGattCharacteristic.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattAdapter.class
 inflated: com/samsung/android/sdk/bt/gatt/MutableBluetoothGattService.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGattServerCallback.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGatt$Stub.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattServer.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGatt.class
 inflated: com/samsung/android/sdk/bt/gatt/a.class
 inflated: com/samsung/android/sdk/bt/gatt/e.class
 inflated: com/samsung/android/sdk/bt/gatt/c.class
 inflated: com/samsung/android/sdk/bt/gatt/BluetoothGattService.class
 inflated: com/samsung/android/sdk/bt/gatt/IBluetoothGattCallback$Stub.class
 inflated: com/samsung/android/sdk/bt/gatt/b.class
 inflated: com/samsung/android/sdk/bt/gatt/i.class
````

**Comment by gerhardol** [comment]
The .jar seem to be from Samsung and is closed source. So using GPL is stretching the license. Really similar for ANT+.
