### ISSUE TITLE
Feature request: out of heart rate zone audio cue

### ISSUE THREAD

**Issue by Solarlark** [jonasoreland/runnerup#388]
In order to use the heart rate zone as a target, it seems like it would make a lot of sense to have an audio cue alert you when you're out of your target heart rate zone. I don't want to be running with my phone in my hand, so it would be nice to have a vibrate/audio alert.

**Comment by jonasoreland** [comment]
If you enable "target coaching" it will tell you this.
So I think this is already fixed. Or?

/Jonas

**Comment by Solarlark** [comment]
Okay, got it. Thanks for pointing that out! I guess I didn't do enough checking initially. Thanks again!
