### ISSUE TITLE
Problem with Runtastic connection

### ISSUE THREAD

**Issue by Gittino** [jonasoreland/runnerup#389]
Good morning,
first of all thanks for this amazing app!
I have a problem connecting to Runtastic.
Before I was able to connect to it and upload my data without any problem but from about one week I'm not able anymore. When I try to connect to the account after having entered my username and password it tries to connect but after few seconds it ask me my username and password again.
Could you kindly have a look and at least tell me if there is a workaround to skip this problem? I really would like to upload my new data on the runtastic portal.
Thanks and best regards.

**Comment by jonasoreland** [comment]
Hi,

I have experienced the same actually.
Do you happen to know if it started with the new release, or it also
happened with old release ??

/Jonas

**Comment by Gittino** [comment]
Hi Jonas,
no, it is not a problem of the last release.
I faced it in the previous release also (that should be 1.51 if I don't go wrong).

**Comment by dhiltonp** [comment]
#390 submitted as a potential fix

**Comment by Bonbadil** [comment]
Hello,
I've just installed 1.57 from F-Droid and I get the same problem.

**Comment by gerhardol** [comment]
Runtastic sync is not working and will be hidden/disabled in an upcoming release #590
