### ISSUE TITLE
[Feature request] Lower playing music during audio cues

### ISSUE THREAD

**Issue by pace6666** [jonasoreland/runnerup#394]
Add Audio option to lower playing music during audio cues

**Comment by Marx2** [comment]
With PlayerFM it's stream is not interrupted, and RunnerUp has much higher sound level

**Comment by pace6666** [comment]
With my lg g4 and spotify I have to pause music option otherwise it's not clear

**Comment by alonevino** [comment]
the feature doesn't work for me

**Comment by gerhardol** [comment]
Option in Audio preferences, may not have been working in all situations, see #475 
This should be included in v1.58

**Comment by davidedelvento** [comment]
This is also related to #604
