### ISSUE TITLE
Summary recalculation and resend

### ISSUE THREAD

**Issue by Marx2** [jonasoreland/runnerup#395]
It happened twice to me, that at the end of training my phone has restarted (restart is not fault of RunnerUp). RunnerUp saved most of track, finished training, but didn't calculate final distance, pace etc - it's set to 0.
After exporting such track to Endomondo - Endomondo also shows 0 in it's summary. In Strava is ok, so it recalculate itself.
While restart doesn't happen very often, it would be nice to have possibility to:
- recalculate track (to have correct history view)
- resend training (probably I would need to delete it first in Endomondo not to have duplicates, so warning should exists)
It's only new two buttons to launch existing functionalities, so seems simply to add.

Edit: after reading #393 I've tried to "recalculate activity" but it's inactive. How to enable it?

**Comment by jonasoreland** [comment]
both of these feature exist!
1) Go to activity
Menu-> Edit Activity
Menu-> Recompute activity

2) Go to activity
Menu-> Edit Activity
Long click checkbox for site that you want to resend to

--

Please confirm that it worked!
(e.g by closing this bug report)

/Jonas

**Comment by Marx2** [comment]
Thank you, I didn't know :)
Tested, works, issue can be closed.
