### ISSUE TITLE
Add walk activity

### ISSUE THREAD

**Issue by Almtesh** [jonasoreland/runnerup#396]
Would that be possible to add walking activity with integrated podometer? I always use "Other" activity with a external podometer (Pedometer from f-droid (name.bagi.levente.pedometer)) and put the count in comment.
If you're on it, you could add the podometer on the running activity.
Thanks.

**Comment by gerhardol** [comment]
Walking activity is prepared in the code, dont know why it is not enabled (probably need some more review, that affects a lot of the code.)

I am adding StepSensor support, the Android sensor (on newer phones, at least mid range and higher). That is used to get Cadence. Adding total steps could be possible. It increases the size of data for all users though (as well as complexity and configuration).

**Comment by radekkuchta** [comment]
I'm waiting for a pedometer. I want to measure cadence. Please hurry up.

**Comment by gerhardol** [comment]
I submitted #490 for step sensor support in December, it has been merged so it should be included in next release. I have no information when that will happen. That adds cadence, not step count though.
Walk activity update in #453.

**Comment by gerhardol** [comment]
Cadence from stepsensor is supported in 1.58
The original request for steps is not supported, no direct plan either
