### ISSUE TITLE
Build error when building SignedAPK

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#422]
:app:transformClassesAndResourcesWithProguardForFroyoRelease
ProGuard, version 5.2.1
Reading program jar [/home/jonas/src/runnerup/GraphView/public/graphview-3.1.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp/okhttp/2.4.0/40340c0748190fe897baf7bffbc1b282734294e5/okhttp-2.4.0.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.nineoldandroids/library/2.4.0/e9b63380f3a242dbdbf103a2355ad7e43bad17cb/library-2.4.0.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.vividsolutions/jts/1.13/3ccfb9b60f04d71add996a666ceb8902904fd805/jts-1.13.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp/okhttp-urlconnection/2.4.0/a0c195f14cefc7597e0bebf22c3e7b43920dcf4/okhttp-urlconnection-2.4.0.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.jakewharton/disklrucache/2.0.2/93b399470e72c0bc8cb52379943b63c9aa586cd8/disklrucache-2.0.2.jar] (filtered)
Reading program jar [/home/jonas/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.4.0/5b72bf48563ea8410e650de14aa33ff69a3e8c35/okio-1.4.0.jar] (filtered)
Reading program jar [/home/jonas/Android/Sdk/extras/android/m2repository/com/android/support/support-annotations/24.1.1/support-annotations-24.1.1.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/design/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/recyclerview-v7/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/appcompat-v7/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/animated-vector-drawable/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/support-vector-drawable/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.mapbox.mapboxsdk/mapbox-android-sdk/0.7.4/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/com.android.support/support-v4/24.1.1/jars/libs/internal_impl-24.1.1.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/runnerup/common/unspecified/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/org.runnerup.hr/hrdevice/1.0/jars/classes.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/exploded-aar/org.runnerup.hr/hrdevice/1.0/jars/libs/antpluginlib_3-1-0.jar] (filtered)
Reading program jar [/home/jonas/src/runnerup/app/build/intermediates/transforms/mergeJavaRes/froyo/release/jars/2/1f/main.jar] (filtered)
Reading program directory [/home/jonas/src/runnerup/app/build/intermediates/classes/froyo/release] (filtered)
Reading library jar [/home/jonas/Android/Sdk/platforms/android-24/android.jar]
Reading library jar [/home/jonas/Android/Sdk/platforms/android-24/optional/org.apache.http.legacy.jar]
Note: duplicate definition of library class [android.net.http.SslCertificate]
Note: duplicate definition of library class [android.net.http.SslError]
Note: duplicate definition of library class [android.net.http.HttpResponseCache]
Note: duplicate definition of library class [android.net.http.SslCertificate$DName]
Note: duplicate definition of library class [org.apache.http.conn.scheme.LayeredSocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.SocketFactory]
Note: duplicate definition of library class [org.apache.http.conn.scheme.HostNameResolver]
Note: duplicate definition of library class [org.apache.http.conn.ConnectTimeoutException]
Note: duplicate definition of library class [org.apache.http.params.CoreConnectionPNames]
Note: duplicate definition of library class [org.apache.http.params.HttpParams]
Note: duplicate definition of library class [org.apache.http.params.HttpConnectionParams]
Note: there were 11 duplicate class definitions.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
Note: android.support.v4.app.NotificationCompatJellybean calls 'Field.getType'
Note: com.nineoldandroids.util.ReflectiveProperty calls 'Field.getType'
Warning:com.almeros.android.multitouch.TwoFingerGestureDetector: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath
Note: android.support.v4.media.ParceledListSliceAdapterApi21: can't find dynamically referenced class android.content.pm.ParceledListSlice
Note: android.support.v4.text.ICUCompatApi23: can't find dynamically referenced class libcore.icu.ICU
Note: android.support.v4.text.ICUCompatIcs: can't find dynamically referenced class libcore.icu.ICU
Note: android.support.v7.widget.DrawableUtils: can't find dynamically referenced class android.graphics.Insets
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class com.android.org.conscrypt.OpenSSLSocketImpl
Note: com.squareup.okhttp.internal.Platform: can't find dynamically referenced class org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGatt
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGattAdapter
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGattCallback
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGattCharacteristic
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGattDescriptor
Note: org.runnerup.hr.SamsungBLEHRProvider: can't find dynamically referenced class com.samsung.android.sdk.bt.gatt.BluetoothGattService
Note: android.support.v4.app.NotificationCompatJellybean accesses a declared field 'icon' dynamically
      Maybe this is program field 'android.support.design.R$attr { int icon; }'
      Maybe this is program field 'android.support.design.R$id { int icon; }'
      Maybe this is program field 'android.support.v4.app.NotificationCompat$Action { int icon; }'
      Maybe this is program field 'android.support.v7.appcompat.R$attr { int icon; }'
      Maybe this is program field 'android.support.v7.appcompat.R$id { int icon; }'
      Maybe this is program field 'com.mapbox.mapboxsdk.overlay.Marker { com.mapbox.mapboxsdk.overlay.Icon icon; }'
      Maybe this is program field 'org.runnerup.R$attr { int icon; }'
      Maybe this is program field 'org.runnerup.R$drawable { int icon; }'
      Maybe this is program field 'org.runnerup.R$id { int icon; }'
      Maybe this is library field 'android.R$attr { int icon; }'
      Maybe this is library field 'android.R$id { int icon; }'
      Maybe this is library field 'android.app.LauncherActivity$ListItem { android.graphics.drawable.Drawable icon; }'
      Maybe this is library field 'android.app.Notification { int icon; }'
      Maybe this is library field 'android.app.Notification$Action { int icon; }'
      Maybe this is library field 'android.appwidget.AppWidgetProviderInfo { int icon; }'
      Maybe this is library field 'android.content.pm.PackageItemInfo { int icon; }'
      Maybe this is library field 'android.content.pm.ResolveInfo { int icon; }'
      Maybe this is library field 'android.inputmethodservice.Keyboard$Key { android.graphics.drawable.Drawable icon; }'
      Maybe this is library field 'android.service.notification.Condition { int icon; }'
      Maybe this is library field 'android.speech.tts.TextToSpeech$EngineInfo { int icon; }'
Note: android.support.v4.app.NotificationCompatJellybean accesses a declared field 'title' dynamically
      Maybe this is program field 'android.support.design.R$attr { int title; }'
      Maybe this is program field 'android.support.design.R$id { int title; }'
      Maybe this is program field 'android.support.v4.app.NotificationCompat$Action { java.lang.CharSequence title; }'
      Maybe this is program field 'android.support.v7.appcompat.R$attr { int title; }'
      Maybe this is program field 'android.support.v7.appcompat.R$id { int title; }'
      Maybe this is program field 'com.jjoe64.graphview.GraphView { java.lang.String title; }'
      Maybe this is program field 'org.runnerup.R$attr { int title; }'
      Maybe this is program field 'org.runnerup.R$id { int title; }'
      Maybe this is library field 'android.R$attr { int title; }'
      Maybe this is library field 'android.R$id { int title; }'
      Maybe this is library field 'android.app.Notification$Action { java.lang.CharSequence title; }'
      Maybe this is library field 'android.preference.PreferenceActivity$Header { java.lang.CharSequence title; }'
Note: android.support.v4.app.NotificationCompatJellybean accesses a declared field 'actionIntent' dynamically
      Maybe this is program field 'android.support.v4.app.NotificationCompat$Action { android.app.PendingIntent actionIntent; }'
      Maybe this is library field 'android.app.Notification$Action { android.app.PendingIntent actionIntent; }'
Note: android.support.v4.app.NotificationManagerCompatKitKat accesses a declared field 'OP_POST_NOTIFICATION' dynamically
      Maybe this is program field 'android.support.v4.app.NotificationManagerCompatKitKat { java.lang.String OP_POST_NOTIFICATION; }'
Note: android.support.v4.media.session.MediaSessionCompatApi24 accesses a method 'getCallingPackage()' dynamically
      Maybe this is program method 'android.support.v4.app.ShareCompat$IntentReader { java.lang.String getCallingPackage(); }'
      Maybe this is program method 'android.support.v4.media.session.MediaSessionCompat { java.lang.String getCallingPackage(); }'
      Maybe this is program method 'android.support.v4.media.session.MediaSessionCompat$MediaSessionImpl { java.lang.String getCallingPackage(); }'
      Maybe this is program method 'android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21 { java.lang.String getCallingPackage(); }'
      Maybe this is program method 'android.support.v4.media.session.MediaSessionCompat$MediaSessionImplBase { java.lang.String getCallingPackage(); }'
      Maybe this is library method 'android.app.Activity { java.lang.String getCallingPackage(); }'
      Maybe this is library method 'android.content.ContentProvider { java.lang.String getCallingPackage(); }'
      Maybe this is library method 'android.service.voice.VoiceInteractionSession$Request { java.lang.String getCallingPackage(); }'
Note: android.support.v4.text.ICUCompatApi23 accesses a method 'addLikelySubtags(java.util.Locale)' dynamically
      Maybe this is program method 'android.support.v4.text.ICUCompatIcs { java.lang.String addLikelySubtags(java.util.Locale); }'
Note: android.support.v4.text.ICUCompatIcs accesses a method 'getScript(java.lang.String)' dynamically
      Maybe this is program method 'android.support.v4.text.ICUCompatIcs { java.lang.String getScript(java.lang.String); }'
      Maybe this is library method 'android.icu.util.ULocale { java.lang.String getScript(java.lang.String); }'
Note: android.support.v4.text.ICUCompatIcs accesses a method 'addLikelySubtags(java.lang.String)' dynamically
Note: android.support.v7.widget.DrawableUtils accesses a method 'getOpticalInsets()' dynamically
Note: android.support.v7.widget.ViewUtils accesses a method 'makeOptionalFitsSystemWindows()' dynamically
Note: com.jjoe64.graphview.compatible.ScaleGestureDetector accesses a method 'getScaleFactor()' dynamically
      Maybe this is program method 'com.jjoe64.graphview.compatible.ScaleGestureDetector { double getScaleFactor(); }'
      Maybe this is library method 'android.view.ScaleGestureDetector { float getScaleFactor(); }'
      Maybe this is library method 'android.view.animation.Animation { float getScaleFactor(); }'
Note: com.jjoe64.graphview.compatible.ScaleGestureDetector accesses a method 'isInProgress()' dynamically
      Maybe this is program method 'com.almeros.android.multitouch.BaseGestureDetector { boolean isInProgress(); }'
      Maybe this is program method 'com.jjoe64.graphview.compatible.ScaleGestureDetector { boolean isInProgress(); }'
      Maybe this is library method 'android.view.ScaleGestureDetector { boolean isInProgress(); }'
Note: com.jjoe64.graphview.compatible.ScaleGestureDetector accesses a method 'onTouchEvent(android.view.MotionEvent)' dynamically
      Maybe this is program method 'android.support.design.widget.CoordinatorLayout { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.design.widget.FloatingActionButton { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.GestureDetectorCompat { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImpl { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplBase { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2 { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.PagerTabStrip { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.view.ViewPager { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.widget.DrawerLayout { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.widget.NestedScrollView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.widget.SlidingPaneLayout { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v4.widget.SwipeRefreshLayout { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.view.menu.ActionMenuItemView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.AbsActionBarView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.ActionBarContainer { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.ActionBarContextView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.AppCompatSpinner { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.ListViewCompat { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.RecyclerView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.SearchView$UpdatableTouchDelegate { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.SwitchCompat { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'android.support.v7.widget.Toolbar { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'com.almeros.android.multitouch.BaseGestureDetector { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'com.jjoe64.graphview.GraphView$GraphViewContentView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'com.jjoe64.graphview.compatible.ScaleGestureDetector { void onTouchEvent(android.view.MotionEvent); }'
      Maybe this is program method 'com.mapbox.mapboxsdk.views.MapView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.app.Activity { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.app.Dialog { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.inputmethodservice.KeyboardView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.media.tv.TvInputService$Session { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.service.wallpaper.WallpaperService$Engine { void onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.view.GestureDetector { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.view.ScaleGestureDetector { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.view.TouchDelegate { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.view.View { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.webkit.WebView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.AbsListView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.AbsSeekBar { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.AdapterViewAnimator { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.Gallery { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.HorizontalScrollView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.MediaController { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.NumberPicker { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.ScrollView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.SlidingDrawer { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.Spinner { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.StackView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.Switch { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.TextView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.Toolbar { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.VideoView { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.ZoomButton { boolean onTouchEvent(android.view.MotionEvent); }'
      Maybe this is library method 'android.widget.ZoomControls { boolean onTouchEvent(android.view.MotionEvent); }'
Note: com.squareup.okhttp.internal.Platform accesses a method 'tagSocket(java.net.Socket)' dynamically
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$BaseTrafficStatsCompatImpl { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$IcsTrafficStatsCompatImpl { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$TrafficStatsCompatImpl { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompatIcs { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'com.squareup.okhttp.internal.Platform { void tagSocket(java.net.Socket); }'
      Maybe this is program method 'com.squareup.okhttp.internal.Platform$Android { void tagSocket(java.net.Socket); }'
      Maybe this is library method 'android.net.TrafficStats { void tagSocket(java.net.Socket); }'
Note: com.squareup.okhttp.internal.Platform accesses a method 'untagSocket(java.net.Socket)' dynamically
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$BaseTrafficStatsCompatImpl { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$IcsTrafficStatsCompatImpl { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompat$TrafficStatsCompatImpl { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'android.support.v4.net.TrafficStatsCompatIcs { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'com.squareup.okhttp.internal.Platform { void untagSocket(java.net.Socket); }'
      Maybe this is program method 'com.squareup.okhttp.internal.Platform$Android { void untagSocket(java.net.Socket); }'
      Maybe this is library method 'android.net.TrafficStats { void untagSocket(java.net.Socket); }'
Note: com.squareup.okhttp.internal.Platform accesses a method 'get(javax.net.ssl.SSLSocket)' dynamically
Note: com.squareup.okhttp.internal.Platform accesses a method 'remove(javax.net.ssl.SSLSocket)' dynamically
Note: the configuration keeps the entry point 'com.mapbox.mapboxsdk.views.MapView { MapView(android.content.Context,int,com.mapbox.mapboxsdk.tileprovider.MapTileLayerBase,android.os.Handler,android.util.AttributeSet); }', but not the descriptor class 'com.mapbox.mapboxsdk.tileprovider.MapTileLayerBase'
Note: the configuration keeps the entry point 'com.mapbox.mapboxsdk.views.MapView { MapView(android.content.Context,int,com.mapbox.mapboxsdk.tileprovider.MapTileLayerBase); }', but not the descriptor class 'com.mapbox.mapboxsdk.tileprovider.MapTileLayerBase'
Note: there were 2 classes trying to access generic signatures using reflection.
      You should consider keeping the signature attributes
      (using '-keepattributes Signature').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#attributes)
Note: there were 2 unkept descriptor classes in kept class members.
      You should consider explicitly keeping the mentioned classes
      (using '-keep').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#descriptorclass)
Note: there were 12 unresolved dynamic references to classes or interfaces.
      You should check if you need to specify additional program jars.
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclass)
Note: there were 17 accesses to class members by means of introspection.
      You should consider explicitly keeping the mentioned class members
      (using '-keep' or '-keepclassmembers').
      (http://proguard.sourceforge.net/manual/troubleshooting.html#dynamicalclassmember)
Warning:there were 1 unresolved references to library class members.
         You probably need to update the library versions.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibraryclassmember)
Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
:app:transformClassesAndResourcesWithProguardForFroyoRelease FAILED
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForFroyoRelease'.
> java.io.IOException: Please correct the above warnings first.
Information:BUILD FAILED
Information:Total time: 19.838 secs
Information:1 error
Information:3 warnings
Information:See complete output in console

**Comment by jonasoreland** [comment]
any ideas @gerhardol  ?

**Comment by gerhardol** [comment]
I see the same problem.
Obvisiouly, deactivating minify/ proguard gives no error.
There has been no changes to minify that I see.
I got the same error a week ago or so when trying to use the recommended setup:
 proguardFiles getDefaultProguardFile(‘proguard-android.txt'), 'proguard.txt'

So it likely is a new error.
I cannot see what is causing it, I would guess at some tool changes.
Note that this is not detected by Travis after lint was enabled. We should add "assembleLatestRelease" target too (again).

I got a "java.lang.ClassNotFoundException" when running some days ago. building directly with gradle was OK, but always failure in AS. This was after playing around with newer versions, but I had it still after restoring.
Worked OK after using AS 2.2 preview (canary channel).
I upgraded SDK Tools at that time too I believe, from 25.2rcX to 25.2. I tested with 25.2.1rc1 too
(pain those cannot be controlled)
Platform Tools is 24.0.1

**Comment by gerhardol** [comment]
The duplicate class definitions can be avoided by updating proguard.txt
http://stackoverflow.com/questions/33047806/proguard-duplicate-definition-of-library-class

-dontnote android.net.http.*
-dontnote org.apache.commons.codec.**
-dontnote org.apache.http.**

**Comment by gerhardol** [comment]
For the other problem:
[ERROR] [system.err] Warning: com.almeros.android.multitouch.TwoFingerGestureDetector: can't find referenced method 'float sqrt(float)' in library class android.util.FloatMath

-dontwarn com.almeros.android.multitouch.TwoFingerGestureDetector
Will remove the warning, minify still fails

-keep public class android.util.FloatMath         
Not working, FloatMath removed in Marshmallow

The solution may have to be to replace usage of FloatMath
It seems like com.almeros.android.multitouch.TwoFingerGestureDetector is used in MapBox, so upgrade may be required.

**Comment by gerhardol** [comment]
There seem to be a second hidden error. When I enabled default files, I could see the error that hopefully just can be supressed:

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard.txt'

-dontwarn com.google.android.gms.common.GooglePlayServicesUtil

Submitting a patch
