### ISSUE TITLE
Map and Graph tabs incorrect

### ISSUE THREAD

**Issue by jluttine** [jonasoreland/runnerup#434]
I'm using kilometers as my units, not sure if it's related to that. Total time, distance and pace are correct. However, the distance markers in Map tab and pace&distance in Graph tab are somehow incorrect. My total distance was 7.90km but Graph shows 9.53km and computes pace values also incorrectly. I switched to Miles units but these are still wrong. Any ideas?

**Comment by AlwaysBiking** [comment]
Same here.  No solution yet :-(.

**Comment by gerhardol** [comment]
The distance in the graph is calculated from data saved in the database and may give different values.
Dont know why this occurs (it for sure is an issue when playing around in the emulator, should not be this obvious in real devices) but the solution I have suggested to @jonasoreland  is to store distance in the database. However, this requires some migration when updating, first time starting will be slow. See what Jonas wants.
