### ISSUE TITLE
Support for Miband 2

### ISSUE THREAD

**Issue by Almtesh** [jonasoreland/runnerup#445]
Hi,

Would that be possible to use Mi band as cardiometer? I tested all available models, none fit this device.

**Comment by alexcmoa** [comment]
+1

**Comment by Almtesh** [comment]
The Gadgetbridge team is umplementing it or will. You could collaborate.

**Comment by gerhardol** [comment]
Something like Mi Band 2 support is implemented if someone with a device has the interest to get around the closed source wall.
The RunnerUp author accepts most patches.

From reviews I have seen, the HR is useless in sports, so steps would be the useful data to collect. Maybe it is possible to use the device to display something like pace too.

**Comment by Almtesh** [comment]
Steps, like I suggested in #396.
