### ISSUE TITLE
Manually recorded activities not uploaded to Strava

### ISSUE THREAD

**Issue by ajhepple** [jonasoreland/runnerup#447]
This is more of an observation really, as it's hardly a significant issue and may even be a limitation of the Strava API. RunnerUp has been wonderful for me; simple, functional and reliable.

If I manually record an activity with RunnerUp and upload it to Strava the activity does not appear in my Strava timeline. No upload error message is presented and the activity is marked as uploaded in RunnerUp. Activities that RunnerUp records automatically, do appear in my Strava timeline.

This is not a big problem as I could manually record the activity directly to Strava instead of manually to RunnerUp. However, I only use Strava as a backup and for web access to my activity history. RunnerUp is my primary and preferred way of recording and viewing my activity history.

**Comment by gerhardol** [comment]
Strava requires data, does not allow manual creation. (GPS is not required though, maybe tcx can be used for empty activities instead of gpx.)

**Comment by gerhardol** [comment]
I have not found any format Strava allows upload without tracks. It may be possible to add an empty tcx track or dummy gps points, but it is a separate feature.
I will close this for now, someone else may find a reasonable workaround though.

**Comment by ajhepple** [comment]
Okay. Many thanks for looking in to it.
