### ISSUE TITLE
Support of Sports Tracker

### ISSUE THREAD

**Issue by alexcmoa** [jonasoreland/runnerup#449]
Hi

Thanks for this fabulous application !!
Before I was w/ Sports Tracker.
Is it planned to add the support of it ?
I would like to add my new records made from runnerup.

BR
alexcmoa

**Comment by gerhardol** [comment]
Not what I know. Support like that would probably be added if a user contributed the code.

You can bulk export Sport Tracker activities:
http://www.dcrainmaker.com/tools

or use SyncMyTracks to sync to another service.

**Comment by gerhardol** [comment]
Sports Tracker has no public API, support cannot be added easily
