### ISSUE TITLE
Can not fetch workout list from Garmin

### ISSUE THREAD

**Issue by RunningCl0ud** [jonasoreland/runnerup#451]
I can not import workouts from Garmin nor load the workout list. 
Edit: With my Samsung Galaxy S5, Android 6.0.1

**Comment by jonasoreland** [comment]
the entire garmin integration is broken since some time...
they changed something, I haven't search for it...or fixed it...

**Comment by gerhardol** [comment]
Duplicate of #438

**Comment by RunningCl0ud** [comment]
Ok I see, so I close this and cross my fingers for a happy ending
