### ISSUE TITLE
full compatible devices list ?

### ISSUE THREAD

**Issue by Vebryn** [jonasoreland/runnerup#457]
Hi,

Congrats to all RunnerUp contributors! Quite interesting functions!

I would like to buy an HRM to use hearth rate monitoring function, is there a list of 100% compatible devices ?

Thank you,

Best regards.

**Comment by gerhardol** [comment]
I have not seen one. If a HRM works with other standard BLE apps, it should be working in RunnerUp too.
Compatibility is more an issue the phone/Android version/Dmanufacturer changes/HRM BLE implementation than the "BLE app".
RunnerUp has some special device support too.

**Comment by Vebryn** [comment]
Thank you, I will buy an ANT+ / BLE compatible device :
- http://www.decathlon.co.uk/ant-textile-hrm-belt-id_8244113.html
- http://www.decathlon.co.uk/cardio-ant-bluetoothsmart-id_8334795.html

You're talking about some RunnerUp special devices ?

**Comment by gerhardol** [comment]
RunnerUp has implemented support for Polar WearLink, Zephyr, SportTracker HRM v1. (No idea what HW they work with. These devices are quite old now.)

**Comment by dafette** [comment]
Hello,
Thanks a lot for your app. I used a lot but yours is the best for me.
Now i look too for connecting an hrm, but my hrmdon't work with. 
If some user have an hrm wich good connect, please tell me the model.
Thanks and great job !

**Comment by jedie** [comment]
The polar A360 is not supported, isn't it?

**Comment by gerhardol** [comment]
RunnerUp supports Pebble and Android Wear to show data from the phone app to a external watch. 
Polar M360 is not supporting any "companion" protocol atall what I know.
Something like notifications could be used for "slow" data like autolap maybe, but that is not implemented now.

**Comment by gerhardol** [comment]
Closing this issue. While it would be helpful to have a list with working devices, there is a plethora of device andphone combinations. Most standard compliant devices work.
