### ISSUE TITLE
Feature request: always report 1 Km data

### ISSUE THREAD

**Issue by sasadangelo** [jonasoreland/runnerup#466]
Hi all,
If I plan an activity of 10 Km where:

5 minutes warm up
2Km at a specific pace
6 Km at another pace
2 Km at another pace
5 minutes cool down

At the end I have the pace for 2Km, 6Km and 2Km. It would be nice always have a report for 1 Km that usually is a reference distance for runners. Runners uses it to check if the pace was smooth during an interval.

**Comment by jonasoreland** [comment]
doesn't it already do this ? (i assuming you have autolap = 1000)

/Jonas

**Comment by sasadangelo** [comment]
Hi Jonas,

Thanks for reply. I think you're right the option is disabled. I remember I did it because it was really annoying for other reasons. To be honest I do not remember exactly why I disabled it (probably too many notifications during the run). I'll try with option enabled my next long run (sunday) and I'll let you know if this solve. For the moment I close the feature request and as soon as I have more info and more details I reopen it if necessary.

**Comment by sasadangelo** [comment]
Hi,
Now I remember why I disabled that option. The reason is that if I do a progressive running like this:
2 Km at pace1
6 Km at pace 2
2 Km at pace 3

with option enabled I see the pace by 1 Km.
With option disabled I see the pace by interval. 
I seems I cannot have both. Am I right?
In this case I preferred to disabled it so that in whatever interval training I always have the average pace for each interval (a measure more interesting for me).
Runkeeper, instead, give both the information.

**Comment by davidedelvento** [comment]
@johnlepikhin Yes, I think it would be nice to be able to have both. Would you accept a PR for this?

@davidedelvento

**Comment by gerhardol** [comment]
You can have cues for the lap as well as intervals, use separate audio schemes for different types of functionality. Close this?

**Comment by davidedelvento** [comment]
I think we can close this. I think the root of the problem here is the confusion between intervals and laps which is the reason I started #597
