### ISSUE TITLE
HR Tracker DEAD! v1.56

### ISSUE THREAD

**Issue by JoeUsername** [jonasoreland/runnerup#532]
The newest update v1.56 killed the HR tracker! It will tell you when you are below, but not above your target HR zone. Also, in the history it shows the bar graph of everything being in zone 0. The hr/pace line graphs are there so I know it recorded the info.

Is there anywhere to download the old version (the one right before this last update)?

Thanks all!
Joe

**Comment by gerhardol** [comment]
1.54 is on f-droid (see link on start page).
I am not aware of any changes for the target HR zone (not something I use)
HR zone graph is fixed in a PR #622 (not merged yet so not included in upcoming 1.58)
