### ISSUE TITLE
Version 1.56 unstable, crashes permanently, multiple issues

### ISSUE THREAD

**Issue by renegat** [jonasoreland/runnerup#537]
Android CM 11 (KitKat 4.4.4)
Huawei Y300

runnerup V. 1.56
- cannot disable audio output
The settings cannot be saved, always reverted to standard permanently bleating at you during training
- weird overlay effects with transparent unreadable text snippets
- often crashes with 'runnerup exited' (or similar translation)
- maps in history recorded with former versions not compatible (ru crashes)
- most entries in settings menu unreadable because screen does not rotate and text is cut off even if autorotate is enabled for device
- german translation partial gibberish pidgin
- bloated from small 3MB to over 16MB size!

runnerup V. 1.54 *last usable version*
- does not even start ('runnerup exited')
EDIT: Had to delete 'app data' and 'cache' in ru apps settings if other version was installed before - than it worked!

runnerup V. 1.53
- unable to disable 'Activity stopped' audio output
EDIT: Setting is hidden in audio settings, must be explicit selected instead of unselect like every other setting ('jump over eventaudiohint'?! - german translation for this entry is gibberish pidgin, cannot be read because display does not rotate and the text is cut off even if autorotate is active for device)

**Comment by gerhardol** [comment]
* I believe the "Skip audio messages" hasbeen like this for a long time.
 * Crashes can be debugged by Jonas with Google Play feedback (or very specific ways to recreate for everyone else). Try deleting the cache and data (export database in maintenance to keep the activities).
 * German translation has been updated, some new parts not yet translated for next version. A German speaker must update.
https://www.transifex.com/runner-up/runner-up-android/language/de_DE/
 * Autorotate is disabled on main screen (actually rotation added to other screens in 1.56), could be confusing if rotation change when running. The GUI probably needs to be rewritten to separate settings and the recording. (I would have preferred to have enabled autorotate everywhere but some users could have been irritated so I kept it for the main activity.)
 * Mapbox update increased the size. Next version should reduce the size for versions downloaded from Play to maybe 6 MB (as binaries for other platforms do not have to be downloaded). (I submitted a patch for this in December.)

 * You cannot downgrade RU without deleting cache, data as the database is updated. If you have exported a bckup prior to the upgrade, you can reimport it.

**Comment by gerhardol** [comment]
No debug data supplied, this issue is closed
