### ISSUE TITLE
Version 1.56 map display blank, because of old install?

### ISSUE THREAD

**Issue by eamonegan** [jonasoreland/runnerup#539]
Android 5.0.1, Galaxy S4

Earlier (unreleased, debug) version previously installed. Uninstalled (dragged to trash) prior to installing 1.56.

Map shows blank (dark) screen except Mapbox logo and information link.

Deleted Documents/RunnerUp folder (I'm pretty sure that was it), and maps now work.

**Comment by gerhardol** [comment]
I have not seen this specifically. MapBox has described that there were some kind of incompatibility in some update, I do not think that should have affected the 1.56 betas., 
Documents/RunnerUp only contains exported activities what I know. 
MapBox maps are not explicitly stored in the map, not sure where they go. Probably somewhere in the data partition.

**Comment by dapgo** [comment]
I have last version of runnerup from F-droid, and yesterday I tracked a path without internet signal.
When i finished i enabled internet but the background map was still not showed, just the mapbox logo (same than  eamonegan  said)

Today I checked the path, and now the map is displayed. :)

**Comment by eamonegan** [comment]
So, deleting stuff, as I said I did, could well be a red herring.

**Comment by gerhardol** [comment]
No change done, assuming this was an upgrade issue in MapBox
