### ISSUE TITLE
v1.56: Audio Cue stopped announcing current pace

### ISSUE THREAD

**Issue by iam-TJ** [jonasoreland/runnerup#541]
I've been using v1.56 daily without problems for recording cross country runs. I have an Audio Cue profile set to announce every 200m distance. It is set to announce "Interval distance" and "Current pace". The profile has "Target coaching" enabled but I don't set a target on the runs.

Two days ago the announcer stopped reporting the "Current pace"; it is only reporting the "Interval distance". I've checked the profile, used its "Test audio cue" to confirm it 'seems' correct, but not been able to fix this.

The text-to-speech is using the standard Android/Cyanogenmod Pico-TTS voice.

The recorded maps and graphs are all accurate so I don't think its a case of it being confused by intermittent GPS signal (signal is strong and consistent).

How can I further investigate and debug this?

**Comment by gerhardol** [comment]
Probably same as fixed in #571 included in v1.58
