### ISSUE TITLE
MapMyRun accounts won't log in

### ISSUE THREAD

**Issue by en3742** [jonasoreland/runnerup#542]
App won't proceed past username/password screen. I suspect this is because the calls to https://api.mapmyfitness.com/3.1 are outdated and now hosted on api.ua.com?

https://developer.underarmour.com/docs/v71_OAuth_2 might have more information that is helpful?

**Comment by en3742** [comment]
(I might attempt to see if I can "branch" this on my own and get it working, but I'm a complete novice here)

**Comment by gerhardol** [comment]
No info on this specific service. There is a page that should describe the status here (should be in the wiki instead):
https://github.com/jonasoreland/runnerup/blob/master/SYNCHRONIZERS.md

The page is not updated. It should be put in the wiki so users can describe the status instead.
(For instance Garmin has changed authencication (and they charge for it) and RunningAhead is gone etc).

**Comment by gerhardol** [comment]
MapMyRun will be hidden in the GUI, see #590 
There is no direct plan to reenable direct sync in the app
