### ISSUE TITLE
Creating new Workouts

### ISSUE THREAD

**Issue by finostro** [jonasoreland/runnerup#543]
I just created an account on garmin connect, but the app won't connect (no error message). 

Where are the json files, so I can see if I can copy and edit them myself?
I looked for them on the android filesystem but I could not find them. 

Thanks for the help

**Comment by gerhardol** [comment]
Garmin connectivity is supposedly broken
The .json files are in the <context>.getFilesDir(), which depends on release. Often something like /data/data/RunnerUp (root required)
You can export workouts though...

**Comment by gerhardol** [comment]
You can import workouts as described in #567 
Garmin import is not working, will be hidden from GUI when #590 is implemented

There can be other ways added to import workouts as files, should be handled in new issue
Closing
