### ISSUE TITLE
Import fails because of "missing Storage permission" - which was never asked for.

### ISSUE THREAD

**Issue by fuu0** [jonasoreland/runnerup#548]
Hey,

OS: LineageOS 14.1
Android 7.1.1, Sec Lvl 5 March 2017
Device: Nexus 5x aka bullhead

I'm using RunnerUP 1.56 from FDroid, without Live Services or GAPPS.

Problem:
I can't import my tracks, when I try I get the Error Message:
"Import runnerup.db
Storage permission not granted in Android settings
DARN!"
But the Android does not ask for this permission, so maybe its not requested?
I'm coming from the same RunnerUP Version but Android 6 on an other Device, so maybe its a problem with new Android Permissions...

**Comment by gerhardol** [comment]
I believe the request of permissions failed in settings for some unknown reason. The popup was the solution.
Requesting Storage permission works for Upload Activity to File
The workaround here would be to add the permission manually in settings. I rather keep it at that, this is special functionality. 
(To always request permission for this debug functionality would be to misuse permissions.)

**Comment by gerhardol** [comment]
No simple fix, there are instructions for this "advanced" functionality
