### ISSUE TITLE
Show URL of used server while using Runalyze

### ISSUE THREAD

**Issue by avanc** [jonasoreland/runnerup#549]
If RunnerUp is configured with another Runalyze server, the main server https.runalyze.com ist still mentioned as Website:
![screenshot_20170410-104019](https://cloud.githubusercontent.com/assets/2905029/24853145/64e1beba-1dda-11e7-8eb9-f741862cbddf.png)

This creates some confusion, as I'm not sure if the desired server is configured. Instead, the website URL of the configured server should be shown.

**Comment by gerhardol** [comment]
This is supported in #593 , not yet merged
