### ISSUE TITLE
Map does not show travel

### ISSUE THREAD

**Issue by Estbm** [jonasoreland/runnerup#555]
Hello, I am using the source code in android studio, I enable the map in the details class but when it runs, in history the map does not show me any route, just the map of the world. Since I could solve this problem, I want to implement that function in an application I'm building, but I can not solve that problem. I hope you can help me. Greetings from Ecuador. 
Your application has helped me alot with my project, I hope you can help me with this problem. 🔢 
Sorry for my english

**Comment by gerhardol** [comment]
You will not see any map in Android Studio details, start the emulator, enable GPS and record a track first.
