### ISSUE TITLE
feature request: disable pause button

### ISSUE THREAD

**Issue by tpapp** [jonasoreland/runnerup#556]
One of the physical buttons (the one on the side that locks the screen, below the volume rocker) on my phone pauses runnerup. I frequently press this accidentally, and it would be nice to be able to disable this.

**Comment by gerhardol** [comment]
The Power button? That cannot be disabled by user apps.

Is GPS enabled when screen is off?
(Could be restricted per app or the phone even if it normally is enabled.)

What phone, Android version and ROM is it?

**Comment by tpapp** [comment]
I have experimented with various options and suspect that it is not the power button, but the `Autopause` setting. It looks like the screen goes to sleep after a while, and that turns off the GPS. When I press the power button, the screen lights up and I guess that makes the GPS come back. Autopause is just a symptom. Disabling `Autopause` gives me straight lines on the map, as described in other issues.

GPS is enabled for RunnerUp specifically in Permissions. I don't know how to make GPS stay on when the screen is off: I saw some hints that claim one needs developer mode (which I enabled), but could not find it. If you have a link, it would help.

In the meantime, using Google Maps simultaneously seems to fix the issue.

The phone is Xiaomi Redmi 3S, Android 6.0.1 MMB29M.

**Comment by gerhardol** [comment]
This seem  to be some MIUI tweak. Google showed other users with similar problems.
http://en.miui.com/thread-162531-1-1.html

To force screen on will eat battery

**Comment by tpapp** [comment]
Thanks for the link, I will experiment with various settings and report back here (will take a while, may no go running for a few days).

**Comment by gerhardol** [comment]
Seem to be MIUI issue, closing
