### ISSUE TITLE
Current Time verbal cue

### ISSUE THREAD

**Issue by wbrenna** [jonasoreland/runnerup#557]
I'm not sure if this needs a pull request because it might not be something most are interested in, but I wanted an audio cue that reads the current time. It exists in two commits here: wbrenna/runnerup@4ab9141fa4a5f35e2afae4a3f588772e5ad3c46b and wbrenna/runnerup@31819601c3868784d877b3a69f7644a7b81a86c2.

**Comment by jonasoreland** [comment]
i think the idea is good,
1) but i don't like the hack.
can you think of a better way do you think ?
2) I also think that the entire date/time format (e.g am/pm) should be based
on locale...not hardcoded into formatter.

**Comment by wbrenna** [comment]
Agreed on both counts - I just don't have the time to learn the structure of the codebase to clean this up right now! Perhaps someone will see this and get an idea of how to properly implement it if there is interest in such a cue...

**Comment by jonasoreland** [comment]
Hi,
I added TXT_TIMESTAMP in https://github.com/jonasoreland/runnerup/commit/88c90e3053cc8cba5ec3bbe77d80eeabb9054d47
Maybe you can use that...and maybe add a CUE_TIMESTAMP

**Comment by gerhardol** [comment]
Included in v1.58
