### ISSUE TITLE
More frequent releases?

### ISSUE THREAD

**Issue by craftyguy** [jonasoreland/runnerup#558]
Hi! I understand this project is probably not a super high priority for you, but I was curious if it'd be possible to get more frequent releases. In particular, I would like to see #552 in a release, but looking through the commits since the last release, there has been a LOT of great stuff that would benefit others. Sure, I could build and sign a release myself, but that'd really only be helping myself and not your other users.

**Comment by jonasoreland** [comment]
I hope to do a beta soonish...

**Comment by craftyguy** [comment]
Awesome!
