### ISSUE TITLE
Support for old (Bluetooth 2.0) Polar devices

### ISSUE THREAD

**Issue by ezeenova** [jonasoreland/runnerup#559]
It would be nice if RunnerUp supported pre-BLE Polar devices, such as the Wearlink+. For reference, [this app](https://github.com/marcolivierarsenault/PolarHeartRateApplication) supports such devices, but it supports neither gps tracking nor exporting heartrate data, so it is of limited use.

**Comment by gerhardol** [comment]
How are the non BLE belts connecting to the phone?
I doubt that more protocols are priotized right now though.

**Comment by ezeenova** [comment]
> How are the non BLE belts connecting to the phone?

I'm not familiar with the ins-and-outs of the protocol, but from the user's perspective the Bluetooth version doesn't matter. The method for pairing them is exactly the same, and they all show up in the list of paired devices. The device's Bluetooth version isn't even explicitly stated anywhere in the operating system, as far as I can tell.

> I doubt that more protocols are priotized right now though.

No problem, this is more of a wish-list item.

**Comment by gerhardol** [comment]
If someone creates a patch I guess that could be supported.
However, most new development will be done for Android 5.0 and later and Zephyr/WearLink will be removed for that version. The existing app for earlier versions will not be removed.

Will therefore close this issue.

**Comment by gerhardol** [comment]
WearLink is supported by the way, not sure if it is working though

**Comment by ezeenova** [comment]
WearLink+, at least, does not work. Maybe regular WearLink does, I don't have one to test.
