### ISSUE TITLE
Support for old android devices

### ISSUE THREAD

**Issue by davidedelvento** [jonasoreland/runnerup#560]
I have an old phone with android 2.3.6 and I use only as a phone, not smartphone, so I have no internet no nothing.

I've seen a comment on Google Play that said that runnerup works with such a old device, however F-droid says *This version requires Android 4.0.3 or newer*. I tried downloading the apk from F-droid anyway to sideloading it, but it fails with *there's an error parsing the package*.

At this point you certainly know that I know nothing about smartphones, but before I waste my time trying to fix the impossible, is runnerup supposed to work (even partially) on my phone? If so, is the last version ok, or should I use an old one (which one)?

Now, the real "issue" is that it'd help if you said something about requirement(s) such as android version in the README file on the front page.

**Comment by gerhardol** [comment]
There are two builds of RunnerUp
* 4.0 and up, with map and Graph. Current binary is big, will be decreased when downloading from Play for next version.
* 2.2 and up. Graphs from 2.3 (I believe).

The 4.0 version is only in Play, the author has not published the 2.3 version on F-droid.
Someone else can build the 2.3 version.

The 2.3 version is slowing down development, I would prefer to release a classic version (both on Play and F-droid) and split the development.

**Comment by davidedelvento** [comment]
@gerhardol This is great information, thanks!
I think it would be worth publishing on the front page. I'll see if I can build the version for froyo myself. As for splitting the development, I understand the issue (I'm a software engineer myself), but of course I have no say for this project. 

If you'd like, I can make a PR for the README.md adding the information about the supported android versions.

**Comment by gerhardol** [comment]
It is not me accepting PRs, I submit them...
Jonas generally accepts PRs

**Comment by gerhardol** [comment]
Documentation updated in #606 
@jonasoreland OK to move all but README to the wiki?
