### ISSUE TITLE
Test Audio Cue Crashes

### ISSUE THREAD

**Issue by sunfish62** [jonasoreland/runnerup#566]
Clicking the "Test audio cue" on the Audio Cues settings page yields the error: "Unfortunately, RunnerUp has stopped."

Android 6.0.1

**Comment by gerhardol** [comment]
Have you tried the beta version?
(There is a link in the wiki.)

If not working, specify what cues you are using.

**Comment by sunfish62** [comment]
Haven't knowingly tried the beta version, although I am running 1.57, which appears to match the beta.

Doesn't matter which cues are set, result is the same. 
Tried: Time triggered, Distance triggered, separately and together. 
Tried with only Total Distance selected.
Tried with various other individual settings.

Every one causes the mentioned crash.

**Comment by gerhardol** [comment]
1.57 is not officially released yet, so this is the beta.
It could be something with the selected language too.
However, this is most easily solved with submitting a log to Play (only the app owner can access those and debug) or by reproducing in the debugger (possibly just connecting with adb).

**Comment by sunfish62** [comment]
Thank you for the reply. I am using English. The audio cues work under normal session use. As a non-programmer, I know nothing about how to "submit a log to Play" or "reproduce in the debugger."

**Comment by gerhardol** [comment]
Submit a log to Play:
What you do when submitting feedback when an app has crashed.
(I have not paid for a developer account and do not know what details you actually see).

Debugger:
A log with adb should show wher (but not how) an application creashed. You do not have to be a programmer to get such a log. A simple instructuion here:
https://support.apteligent.com/articles/knowledge_base/How-to-Collect-Logs-via-Command-Line-ADB-on-Android-Devices

**Comment by bme13** [comment]
Hi. I'm having the same issue. Running v1.57 on Android 6.0.1. I've captured some debug information. See:
[runnerup_crash_audio_cue_test_v1.57.txt](https://github.com/jonasoreland/runnerup/files/1085045/runnerup_crash_audio_cue_test_v1.57.txt)
In this log Dutch language is selected, however I've also tested this with English selected and the result was the same. I've selected total distance and interval tempo. I've noticed that the total distance is not announced during my run. A new test with only the interval tempo revealed that the cue test works fine then. Perhaps related to #541.

**Comment by gerhardol** [comment]
This should only occur for distance cues (and cadence, but there is no way to enable that). 
It should occur also for normal activities (the error is probably caught).
Jonas made the change to fix such a problem according to the commit comment.

**Comment by jonasoreland** [comment]
FYI: reproduced for "Total distance"

**Comment by gerhardol** [comment]
Corrected in #571 released in 1.58
