### ISSUE TITLE
Add JSON Workout to app?

### ISSUE THREAD

**Issue by sunfish62** [jonasoreland/runnerup#567]
I am a new user of RunnerUp, and I very much like what I see. 

I generally like to run interval sessions, but need a little more configurability than I see on the Interval tab, specifically in regard to the warmup and cooldown. These currently are hard coded into the app as continue until tap steps. I much prefer to have timed warmup and cooldown, but have no way to change them on the Interval tab.

I thought that perhaps I could add my own custom workouts in the advanced tab. Currently, there are three workouts listed there, and digging around here shows me that these workouts are individual Garmin Connect JSON files that are stored here in runnerup/app/assets/bundled/app_workouts.

Is there a way to add other JSON files directly to my phone so that they appear in the options? Or do I have to add the file to the sources and build the app locally? I will note that I am not a programmer, and have zero experience with java, so building the app will be a challenge.

**Comment by gerhardol** [comment]
You can create and export workouts from Settings-Workouts-Manage eWorkouts
No way to import what I know (now when Garmin import is gone, should be hidden in the app).
The "asset" is included in the app itself, so no way to change that right now. Workaouts are internally stored in a SQLite database.

There should be an option to create workouts from the tab, interval and advanced/interval should be merged.
It should be possible to import .json from a file

**Comment by sunfish62** [comment]
Thank you for your replies, both here and on my other threads. I really appreciate it. 

I agree that creating workouts should be accessible from the tabs.

I asked about importing json files because I didn't see how to create workouts in RunnerUp, or how to edit the workout in the Interval tab. I figured out how on the Garmin connect site to make a workout and save it locally as a json file. I figured that I might then import a workout json file. This functionality is not really required, given the existence of the Create Workout option, which creates a json entry on the Advanced tab anyway.

To discuss the tab issue a little more, I think the Interval tab could be eliminated altogether. The Advanced tab could be renamed Workouts, and a default Interval workout be added to the initial set of offerings in app_workouts.

**Comment by gerhardol** [comment]
The GUI should be refreshed at RunnerUp with a normal toolbar and navigation drawer before other changes are done.
I started that briefly some months ago but await pull requests to be merged before I continue.
I also would to prefer to focus development on new Android versions only, maintaining older versions separately.

**Comment by jonasoreland** [comment]
you can import json workouts (from garmin)
by mailing them with correct mime-type and
then runnerup will import then...

the easiest way of seeing how that work is by "sharing" a workout,
that will send such a mail...

**Comment by davidedelvento** [comment]
@jonasoreland Would you be ok with some PRs to refresh this part of the GUI? I'm thinking:

- remove the json extension from the UI (that's an implementation detail that just make the visible name shorter)
- allow a "new" option in the json dropdown menu, so people don't have to go to Settings-Workouts-Manage Workouts to create new ones
- make it possible to edit existing workouts, e.g. adding steps as describe in #352 
- allow the use of variables (and add a way to set them) as described in #314 

@davidedelvento

**Comment by jonasoreland** [comment]
Sounds exiting...
Go for it...
Advise: One change at a time...it takes me much longer to review a big patch
than it takes to review many smaller

**Comment by gerhardol** [comment]
The enhancment from this discussion is merged, closing this specific issue, @davidedelvento knows how to crete new issues
