### ISSUE TITLE
Zero iteration repeat step causes race condition that crashes phone

### ISSUE THREAD

**Issue by sunfish62** [jonasoreland/runnerup#568]
In trying to create a basic interval workout with timed warmup and cooldown, I modified the MalinEwerlov workout in the Advanced tab so that the later interval steps used zero iterations of zero duration. RunnerUp successfully processed the timed warmup and the five iterations of the first interval. 

Once it reached the zeroed out steps, however, my phone completely froze up, and I had to hard boot it. Upon restart, I reopened RunnerUp and opened the workout entry in the History tab. The workout was not accurate in regards to distance and duration (that much I expected). However, opening up the laps page of the workout showed a huge number of zero value laps. I was unable to scroll through all these entries because RunnerUp crashed out again, and my phone reported that RunnerUp was consuming far too many system resources. It is apparent that RunnerUp did not catch the zero iteration setting correctly.

Version 1.57
Android 6.0.1

**Comment by jonasoreland** [comment]
cool!
that should be easy to fix....don't allow zero iterations...

**Comment by gerhardol** [comment]
In pull request, closing
