### ISSUE TITLE
Manual Workout Entry enters null date

### ISSUE THREAD

**Issue by sunfish62** [jonasoreland/runnerup#569]
When I attempt to create a workout using the Manual entry tab, RunnerUp fails to set the date correctly, and instead enters a null value in the date. This results in every manual entry receiving the 01/01/1970 Unix "zero" date setting. 

Version 1.57
Android 6.0.1

**Comment by gerhardol** [comment]
Same for me in 1.57
(Working in my unmerged pull request by the way.)

**Comment by jonasoreland** [comment]
hmm...this sounds like a regression from @gerhardol

**Comment by gerhardol** [comment]
Included in v1.58
