### ISSUE TITLE
"Searching for GPS"

### ISSUE THREAD

**Issue by davidhedlund** [jonasoreland/runnerup#578]
I share the same problem. GPS works fine in other apps but I never get it in RunnerUp from F-Droid, I only get this in the notification message:

> Searching for GPS

Repository: https://f-droid.org/packages/org.runnerup/
RunnerUp: 1.54
Android: 4.4.2. The Location is enabled off course.
Device: Samsung Galaxy Express 2

**Comment by davidhedlund** [comment]
https://github.com/jonasoreland/runnerup/issues/464#issuecomment-315567517

**Comment by gerhardol** [comment]
What do you see in the notification field?
(should by fixed_sats/available_sats, accuracy)

RunnerUp considers satallites to be found when one of the following occurs: more than two satellites are fixed, acurracy is better than 10m or location updates are received more than once a second.

Can you confirm that no permission blocking is done for the app?

**Comment by davidhedlund** [comment]
@gerhardol The RunnerUp window says:

> GPS satellites: 2/26
> WAITING FOR GPS

> Can you confirm that no permission blocking is done for the app?
Yes.

**Comment by davidhedlund** [comment]
The location is enabled off course.

**Comment by gerhardol** [comment]
The phone has only two sats here, which is not sufficient for a fix.
The Android API used (LocationManager) is not reporting any location updates to the application.
The code seem fine to me, GPS status could be tested with other APIs too (even if that is not the recommended way).

Can you get a better GPS coverage to get 4 sats?
Any other apps like GPStest that get a fix with 2 sats in RunnerUp?

**Comment by davidhedlund** [comment]
@gerhardol Can you please indicate that in RunnerUp like this?:

> GPS satellites: 2/26 (min 4 connected required)
> WAITING FOR GPS

**Comment by gerhardol** [comment]
The accuracy is more important than the number of satellites.
However, many sats are important if conditions change (like other side of a building).
Just 4 sats will give low accuracy too, quite useless when moving. At least 8 is what I was aiming at with my Garmin Forerunner 305. Most apps are hiding the sats/accuracy, just "searching". Numbers can confuse people. 

So is it working with better GPS coverage?

**Comment by davidedelvento** [comment]
I tried RunnerUp with two different phones, and one would work only if I held it in my hand pointing to the sky, whereas the other would work even if it's my pant pocket. The point I'm trying to make is that this might not necessarily be a RunnerUp issue, not sure how to prove/disprove this with just one phone and the satellites that move all the time and their visibility changes even if you are still....

**Comment by gerhardol** [comment]
Try several apps on one phone. 
There may be some seconds in between they report GPS fix (like the sanity filter in RunnerUp), but the apps should use the same APIs, result should be the same.

**Comment by gerhardol** [comment]
Closing this as question
