### ISSUE TITLE
Interval rest periods marked as active periods in runalyze

### ISSUE THREAD

**Issue by jluttine** [jonasoreland/runnerup#579]
I did an interval training and uploaded it to Runalyze. However, the rest periods were marked as 0km / 2min active periods. I had to manually change them to rest periods. They should be uploaded as rest periods in the first place.

**Comment by gerhardol** [comment]
Not something I use (workouts or RunAlyze), took a look at it:
RunnerUp uses active/rest/warmup/cooldown, so mapping must be done.
It seems like the author of the module has commented out the intensity, so may there were some problems syncing.

**Comment by gerhardol** [comment]
@rickyepoderi 
Another change would be to add the external id as in #609

**Comment by rickyepoderi** [comment]
Hi,

Remember that current implementation of the Runalyze synchronizer is just temporary waiting to a proper rest interface in the server. Nevertheless if it's easy I don't have a problem in trying to incorporate it.

1) @gerhardol The type is [the INTENSITY in the LAP table](https://github.com/jonasoreland/runnerup/blob/master/common/src/main/java/org/runnerup/common/util/Constants.java#L90), the complete lap is ACTIVE, RESTING, WARNUP or whatever, isn't it?

2) @mipapo In order to indicate that to runalyze I just need to set "splits[active][]=0" instead of 1 for that split/lap. Am I right? In this case it's only 1 or 0 (no warup or cooldown, just active or inactive).
  Or is it related to the "pauses" attribute? (This one is completely empty in the synch).

3) @gerhardol I don't know what you mean with external id, what is that?

Thanks.

**Comment by mipapo** [comment]
@rickyepoderi  I think that it's correct

**Comment by gerhardol** [comment]
With #609 the RunKeeper reference is stored in RU, so the DetailActivity view has a link to the activity that opens in the app if installed (not very useful) or the web browser.
For Runalyze it makes more sense to get a good mobile browser view of the activity.

interface INTENSITY {
            int ACTIVE = 0;
            int RESTING = 1;
            int WARMUP = 2;
            int COOLDOWN = 3;
            int REPEAT = 4;
            int RECOVERY = 5;
        }

**Comment by rickyepoderi** [comment]
@jluttine When you say resting periods you are talking about this part:

![laps](https://user-images.githubusercontent.com/1576140/29241369-799c2552-7f78-11e7-8c1c-9b3ce44c388c.png)

Here you want the lap to be "resting".  Ok?

I'm mapping everything to active (ACTIVE, COOLDOWN, RECOVERY, REPEAT and WARMUP) except RESTING. In runnerup there are a lot of values and in runalyze just active and resting.

Does everybody agree?

**Comment by rickyepoderi** [comment]
@gerhardol With the last version I see that I upload an activity and it's not removed from the list although The upload method returns OK in the synchronizer. Is this normal?

**Comment by gerhardol** [comment]
@rickyepoderi 
I suggest mapping ACTIVE to ACTIVE and RESTING to all others (REPEAT is not really a type though...)

Upload in Configure activity?
It seems like the upload status is not set. Will have to look in to that.
It is like this also in 1.58, next release (there are quite a lot of changes in master).

**Comment by gerhardol** [comment]
@rickyepoderi Fixed the upload issue in #618 Upload was OK but status was not updated

**Comment by rickyepoderi** [comment]
Ok, PR #620 should send "splits[active][]" to 1 or 0 depending the values of the intensity in the lap.

@mipapo I don't know how to go directly to an activity in runalyze. It seems that now runnerup can link to external provider and open a browser to the activity information. But as runalyze uses javascript a lot I don't find a way to go directly to an activity using a URL. If you know how to do it please just tell me and I will file another issue for external id in runalyze synchronizer.

Thanks.

**Comment by mipapo** [comment]
@rickyepoderi  You need to open Runalyze and execute the js "Runalyze.Training.load(<activity_id>, false, event)" 
But I don't know how you will find out hte id of the newly created activity

**Comment by gerhardol** [comment]
Merged. Not includedin the upcoming 1.58, should be in next (if Jonas accepts the changes done).

@mipapo Using an id to open the activity should be considered for the official API.
Just making sure the activity day is visible in th GUI is a good help for the user.

**Comment by rickyepoderi** [comment]
In version 4.0 the url "http://localhost/runalyze/dashboard?id=24" works for me, it shows the activity with id=24. But as @mipapo says it's difficult to know the id of an activity. The upload methods doesn't return it and the only way of looking up activities is using "call/call.DataBrowser.display.php?start=<starttime>&end=<endtime>", which is not very accurate. So if it's not necessary I prefer to not implement this feature for the moment. 

Thanks.

**Comment by gerhardol** [comment]
Closing the issue as the suggestion is merged.
(My follow up suggestion could have been discussed in a separate issue.)
