### ISSUE TITLE
Activity type is not set when upload in Strava

### ISSUE THREAD

**Issue by filin2009** [jonasoreland/runnerup#582]
[RunnerUp_0079.zip](https://github.com/jonasoreland/runnerup/files/1165577/RunnerUp_0079.zip)

In RunnerUp - Running , in Strava - Cycling 
Example https://www.strava.com/activities/1094302547
OK:
RunKeeper https://runkeeper.com/user/filin/activity/1022197656
Endomondo https://www.endomondo.com/users/12006801/workouts/967224361

**Comment by gerhardol** [comment]
The type is not changed, it is just not set. Strava will use the athlete's default activity type.
The type could be set as done for Endomondo and RunKeeper.
https://github.com/jonasoreland/runnerup/blob/master/app/src/org/runnerup/export/StravaSynchronizer.java#L213
https://strava.github.io/api/v3/uploads/

**Comment by filin2009** [comment]
True. But could you please update
runnerup/blob/master/app/src/org/runnerup/export/StravaSynchronizer.java
and set parameter "activity_type" correspondently
to activity type in RunnerUp while uploading to Strava?
I am running and cycling sometimes, 
so changing activity type in Strava all the times is unconfortable.

https://strava.github.io/api/v3/uploads/
activity_type: 	string optional, case insensitive
possible values: ride, run, swim, workout, hike, walk, nordicski, alpineski, backcountryski, iceskate, inlineskate, kitesurf, rollerski, windsurf, workout, snowboard, snowshoe, ebikeride, virtualride
Type detected from file overrides, uses athlete’s default type if not specified

**Comment by gerhardol** [comment]
Included in upcoming v1.58
