### ISSUE TITLE
Activity stopped or paused randomly

### ISSUE THREAD

**Issue by davidedelvento** [jonasoreland/runnerup#598]
At first, I dismissed this as a phone or GPS issue, not RunnerUp issue. However *on some days* (and only on some days) it gets very infuriating. I am convinced it's RU, not phone or GPS issue alone (even though phone and satellites probably have a role), for the reason it would be clear in a moment.

When starting a "Basic" or "Interval" run on such "bad" days, what happens is either of the following:

* In about 5 seconds the voice announces "Activity Stopped" and of course it does. Manually restarting it, lead to the same outcome over and over again.
*or*
* In about 5 seconds the voice announces "Activity Paused" and of course it does. In about 5 seconds the voice announces "Activity Resumed" and of course it does. The loop continues forever. More usable than the previous, but too verbose and almost useless anyway.

At first I thought it was operator error (e.g. not locking the phone, or inadvertently push the "stop" or "pause" buttons before locking, hypothesizing the buttons might have been a little unresponsive at the beginning of the run, having the event triggered later on, or maybe dirt on the screen, or wrong commands from the headsets). So I've been very careful to rule all these options out. To no results, same problem occurring forever. 

By accident I discovered that the "Advanced" run does not have this problem. I purposefully created an advanced setting with a json file which does nothing other than one single activity "until push". That works fine. On "bad" days, I run the basic thing and it loops as described above. I switch to this advanced run and it works. I switch back to the basic thing and it loops again. Totally restarting RU does not help. I did not try restarting the phone, since it takes too long and I'm out for a run, not to mess up with software (plus, the described workaround works just fine for me).

Reporting just to make the experience better for new users, as I said, for me the workaround works just fine 

PS: as a side note, especially for @cmmata: I think having just the "advanced" setting and getting rid of "basic" and "intervals" would make the UI better. By default there must be a "basic" and a "inteval" json files which would do what the other tabs do now, and at the first launch "basic" should be selected.

**Comment by cmmata** [comment]
I always use advanced run, so didn't notice that problem. I'll try and see if I get the same problem.

Anyway, I agree that the main view should be simpler. The basic mode at first view and maybe a dropdown to select if you want to enable interval or advanced mode.

**Comment by gerhardol** [comment]
Main view, my view:
A floating "+" button. Short press, start basic, longpress select basic/workout/ (simple/advanced)/manual. Same alternatives in sidebar.
(not sure what should be the default background, maybe history)

Auto-pause: Activity paused
I doubt that is related to Advanced Workout or not. (It is possible that auto-pause is disabled for Advanced, I have not checked, just do not see why).
The auto-pause is unreliable, it is a little to "aggressive" by default with 3s. Not sure what pace value is used, maybe raw pace.

Personally, auto-pause is the first I deactivate. 
My suggestion for this issue is to deactivate auto-pause by default as well as increase default pause time to 7s (or so).
A longer term improvement would of corse be to improve distance calculations, then pace filtering, then auto-pause detection.

Activity stopped:
Something different I cannot explain. Can you get a logcat?

**Comment by davidedelvento** [comment]
Re GUI, see e.g. https://github.com/davidedelvento/runnerup/issues/22

Auto-pause is a good guess. I did not think to change that. There is nothing in the GUI suggesting that it is not applied for the advanced workouts, but maybe that's the thing.

Re: logcat -- I see that to use it I need to have the phone in dev mode etc. But it's not clear to me if I can get the logs for the app I installed from the app store and the event that happened in that day, or if I should reinstall the app via USB to do that and do something special to keep the logs "available" in the phone to be later analyzed (sorry for the dumb question....)

**Comment by gerhardol** [comment]
logcat:
The log is not covering a long time, dependent on the configuration of course. You do not need to reinstall to get the log, it is always there.

So with USB you probably need to connect with adb in some minutes to find what happened
If the phone is rooted, you can an app like catlog to get the log too.

**Comment by gerhardol** [comment]
logcat:
You can control the size in developer options
https://stackoverflow.com/questions/6321555/what-is-the-size-limit-for-logcat-and-how-to-change-its-capacity

**Comment by davidedelvento** [comment]
Thanks for the information. For the moment, I'll keep this on hold, we have bigger fish to fry, don't we?

**Comment by gerhardol** [comment]
Changing the defaults for auto-pause is a candidate for simple improvements.

In addition to use a project, we should add some tags for issues with "partial" improvements. No new issue for now.

**Comment by gerhardol** [comment]
Enhancement: Change defaults for auto-pause, increase parameters too
The auto-pause functionality is related to pace stability, see #465

**Comment by cinke** [comment]
Autopause issue is killing me. I run in a city - and traffic, red lights etc., I need it.
What I realized is that the stop - is start cycle is actually the time set for autopause. Set it for the default 3 seconds - after 3 seconds it stops. Set it for 30 seconds, it won't stop for 30 seconds.
It seems autopause is not counting the time elapsed without movement, but simply time elapsed.

**Comment by cinke** [comment]
Autopause does not work in advanced mode.

**Comment by gerhardol** [comment]
AutoPause is much better in master. Current pace is much more stable and some tweaks to the algorithm too. The current release just require two samples with at least delay time (like 3s) in between to kick in, not requiring all samples to be below cutoff pace.

The experience will depend on the GPS quality and the environment, but for me auto-pause kicks in just occasionally when running slow trail runs now. Further improvements can be done with better current speed filtering.

Auto-pause for intervals should be set per workout. You normally do not want auto pause in an interval session, the countdown should normally not stop in a rest interval. But this is a bigger change.

**Comment by cinke** [comment]
I tested it a couple of times and it for sure does right now what I wrote.
Leave it at 3 seconds - it will autopause at 3 seconds.
Set it for 300 seconds - it will stop at 300 seconds.
No matter whether I run or stop.
Strange.

**Comment by gerhardol** [comment]
Closing, improved in the beta builds
