### ISSUE TITLE
Git LFS usage

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#601]
I would like to use LFS for the ANT+ lib as well as the "Samsung BLE lib" (that will be removed in NG though). 
ANT+ FIT should be added the same way (the lib in the ANT+ submodule is old).

The require Git 1.8.2 or later (files can be handled manually too).
https://github.com/git-lfs/git-lfs/wiki/Installation
https://git-lfs.github.com/
For Windows, Git for Windows 2.12 and later includes LFS (you still need to run "git lfs install" once.)

Binary files should not be stored in Git but the file is not updated much and I would have been OK with storing the .jar in Git too, but Jonas did not want that. LFS is much easier in this aspect. (I have setup a system with extensively use of submodules at work where submodules mke sense (I still believe submodules are cumbersome), but here LFS makes better sense.)

A reason for LFS is to avoid Lint warnings for ANT+ projects as well as simplify searches outside Android Studio.

**Comment by davidedelvento** [comment]
@gerhardol so what is this issue about? Talking if we're ok using LFS? I would prefer submodules for dependencies, but if you **really** want to use LFS, go for it. FWIW, I don't care about git for windows, since I run Linux on my laptop.

**Comment by gerhardol** [comment]
@davidedelvento Yes this was added to get comments.
I know you use Linux, but do not know if you are OK with LFS (distro support).
git-lfs just need to be included in the path.

I will probably submit separate PRs for Samsung and ANT+.
@jonasoreland ?

**Comment by davidedelvento** [comment]
Thanks for the clarification. LFS works fine on Linux, so I can use it if necessary

**Comment by jonasoreland** [comment]
no opinion,
never used git lfs

make sure to update docs on how to install/compile.
