### ISSUE TITLE
Export activities in .fit format

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#605]
Most sites support .fit in addition to .gpx and .tcx. 
.fit files are smaller and should be faster to generate and transfer than .tcx/.gpx as well as supporting more data (barometer pressure, accuracy data for instance). .fit can be used by many upload services like Strava. 
(Current export can take 20s for a 3h run). Most of the time seem to be related to writing the file, indicated from some initial tests.

The first hurdle is if it is possible to use ant+ FIT SDK. The license does not allow redistributing and store the .jar in Git should break that. The latest version is 20.41, downloadable from
https://www.thisisant.com/resources/fit
However, the license does not allow redistribution.
I am trying to clarify the license.

There may be other options like a sepatate .fit implementation, that can have other license implications. (Could be the same with using ANT+ at all.)

The implementation in itself is similar to the .tcx implementation.

**Comment by gerhardol** [comment]
Conclusion after some communication with Dynastream: Stay away from everything ANT+ or .fit, it is not possible to deal with Dynastream.

It will not be possible to use the FIT library in an open source application, the lib cannot be redistributed and then it will not be possible to build. (Letting developers download manually is not a good solution, it will also not be possible to build in Travis.)
In communication with Dynastream they indicated that implementing code is distributing their specifications, which breaks the license. I cannot make that interpretation from the license text.
While the protocol cannot be trademarked it is not allowed to reverse engineer the protocol with Dynastream information. An implementation without that information is impossible.

A related matter is that ANT+ is trademarked and require certification and license. The license agreement only mentions the ANT+ logo though.

**Comment by jonasoreland** [comment]
i think there are open source libs for .fit encoding...

/Jonas

**Comment by gerhardol** [comment]
It should be possible to use the fit.sdk to implement a separate lib or app that can be combined with RU
The separate app can be open source, but evry user have to download the fit sdk manually.

**Comment by davidedelvento** [comment]
Disclaimer: IANAL and I have not read anything about FIT (so, not even its license).

That said, I think I can still raise this question: if the FIT.SDK does not allow redistribution, how does a separate app help? The separate app cannot be distributed either.

To me this sounds a lot of legalese work, usually not worth the hassle, plus the user experience will be poor with separate installs. I too hate the long waits for exporting to .gpx and .tcx however we can try to do something different and easier to implement (e.g. writing the file in a separate thread, leaving the app responsive instead of hang).

**Comment by gerhardol** [comment]
>That said, I think I can still raise this question: if the FIT.SDK does not allow redistribution, how does a separate app help? The separate app cannot be distributed either.

You are free to redistribute applications using the FIT SDK, just not the jar and the source examples themselves. Dynastream believes the retains their rights better that way.
So it should be OK to make a companion app or maybe even a a lib wrapping the jar. 
But I do not want to do that. I would rather erase anything from Dynastream from my horizon completely and call them bad names.

Since I put some hours investigate this, looking at the SDK etc I just wanted to share my findings. Someone else may want to waste time on Dynastream.

It is too bad, .fit could be the solution to the slow export (and thereby upload) in RU. I have tried optimizing the .tcx export, writing a 4MB file takes time. I did not see any obvious way to optimize the handling.

**Comment by davidedelvento** [comment]
@gerhardol You don't have to make it "optimized" or "faster". Using a separate thread will make it. Alternative, using another formal, possibly invented by us, or using the extensions in a smarter way, e.g. not repeating them so many times, can reduce the size of the file, and therefore the wait.

That said, I think we have many more higher priority issues than this (which is a just nuisance)

**Comment by gerhardol** [comment]
Closing, this will not happen, Dynastream are impossible to work with. Use of ant+ is questionable in RU if examining their user agreement, only included due to they are breaking the agreement themselves first.
