### ISSUE TITLE
Move documentation files to Wiki

### ISSUE THREAD

**Issue by cmmata** [jonasoreland/runnerup#613]
In #586, @gerhardol talked about moving all documentation in text files / code comments to the Wiki, like:
- CONTRIBUTING
- SYNCHRONIZERS
- TODO
- Documentation

I think we cannot move CONTRIBUTING.md file to wiki, because when you open a new issue there's a link to that file. In [Github help](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) I don't see any other way to do that without that file.

I have moved the TODO list to [the wiki](https://github.com/jonasoreland/runnerup/wiki/TODO-list), but looking at it I see a lot of open TODO's that doesn't seem to relate to any issue, so I don't know if they are still pending or can be deleted.

And by the way, should I submit a PR with the deleted files, or @jonasoreland / @gerhardol will delete them directly on the repo? I have already moved documentation folder and TODO list, I'll move Synchronizers too.

**Comment by gerhardol** [comment]
I can take a look at the changes and create&merge a PR
The TODO needs to be cleaned up. It is still relevant but priorities may have changed. I still believe we need something in the wiki for the overview, in addition to issues.

**Comment by gerhardol** [comment]
#617 
Did some updates too
