### ISSUE TITLE
Heart rate zones not displayed correctly

### ISSUE THREAD

**Issue by Marx2** [jonasoreland/runnerup#614]
From some time zones didn't display properly on first tab of workout. It displays that whole training is done in first zone.
I was using 1.56, so I was supposed it was broken in this version. But, accidentally, one of my last trainings displayed it properly. Then next one again displayed it wrong. I've just switched to 1.58 beta, nothing has changed. Even if I recalculate training.
Graph of HRM is displayed ok.

I don't know what happens. Is it working for you?

**Comment by gerhardol** [comment]
I can reproduce it and believe I have a fix for it (the time for the first point is not set correctly so first point last an infinity). Submitted a PR
