### ISSUE TITLE
Default values review

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#621]
There are a number of default values in RU that possibly should be changed.
The settings creates question from users, it may be better to disable some functionality by the default and let users enable them from the myriad of settings (in my opinion a good thing).
(There are hardcoded settings that could be made visible and changed too.)

I listed a few issues with discussions to these, there are more

Auto pause (currently On, suggest Off)
The setting should not ba a problem but the pace smoothing is not optimal and will occasionally give a lot of pauses.
#598 

GPS sampling (Currently 0.5s, 0m; suggest 2s, 10m)
GPS is unreliable and will measure longer distances the worse the GPS is. For me, I get 5-15% longer than my running watches (a trusted Garmin Forerunner and a Suunto Ambit 3). Newer Garmins have mediocre GPS but often make a good job in the software to measure distances. A good filter that uses accelerometer etc is very hard, but using minimum 2s and 10m gives decent result in my limited tests. Other apps that seem to use such filtering is Runkeeper and Ghostracer that both are more consistent than RU default and for instance Strava.
#598 #464 #257 

Auto start GPS (currently On, suggest off)
To explicitly start the GPS gives more intuitive functionality than to keep GPS on when the app is in the foreground.
#255 

Step sensor for cadence (Currently off, suggest On)
Was not enabled when I added support, probably a good thing
(Keep Temperature and Barometer off?)

Enable Live
Hide the setting (unless avanced is ticked?), no working server?
#351

**Comment by davidedelvento** [comment]
I'm fine with these proposed defaults, besides the GPS sampling.

I still struggle to see how a 10m GPS samples can make things "better", 10m seems like quite a "long" distance for someone running. Does it mean that the resolution also goes down to 10m? Let me know if we should have this conversation in any of the issues you linked as opposed to here.

**Comment by gerhardol** [comment]
For GPS default, take it separately. There are more discussions in #464 regarding the current defaults (but it is closed) where #257 is regarding "some other filter".
