### ISSUE TITLE
Hiking Activity

### ISSUE THREAD

**Issue by beli3ver** [jonasoreland/runnerup#623]
Hi,

I want to ask if it is possible to add hiking as a activity?
Thanks

Malte

**Comment by gerhardol** [comment]
If someone makes a patch, it may be accepted, but no direct plans.
Note: The current solution requires that all translations are updated too.

It would be nice to add activities by the user, but this need to be integrated with the synchronizers too.

**Comment by davidedelvento** [comment]
Other than the name, how this would be different from walking?

**Comment by beli3ver** [comment]
I was hiking this weekend, with the option walking. But everytime I go slow because of my kids oder take a second break to wait for my kids, the activity stoped and start again.

**Comment by davidedelvento** [comment]
That is likely related with the autopause which always seem to cause troubles see e.g. #598 Either disable it completely, or put a longer wait, such as 10s or more. Even running, the default 3s is too short. See also #621
