### ISSUE TITLE
German cues off?

### ISSUE THREAD

**Issue by oylenshpeegul** [jonasoreland/runnerup#627]
I'm pretty sure she says "fünfzig Minuten" at 40 minutes (should be vierzig) and "fünfundfünfzig Minuten" at 45 minutes (should be fünfundvierzig). I can't find where the numbers come from. I was hoping to find "fünfzig" written twice in [app/res/values-de/cues.xml](https://github.com/jonasoreland/runnerup/blob/master/app/res/values-de/cues.xml) or something, so I could just fix it and send a PR, but no such luck.

**Comment by gerhardol** [comment]
For numbers, the text-to-speech does the output, see cue_minuten in the cues file
I seriously doubt the tts engine is wrong here, no explanation to what you see.

**Comment by davidedelvento** [comment]
Not sure if it's applicable here, but often the cues are off not because are cues, but because the measurements are off, or the software is not making the right assumptions/approximations.

For example, I often get a cue saying that my pace is 4 quadrillions (and blah trillions, and blah billions, and yadda yadda -- it take a minute to say the whole number and it's quite annoying) minutes per mile.

**Comment by gerhardol** [comment]
Sidenote: there should be a cut off for pace, at least cues. Slower than 15 min per km is too slow for gps anyway. I do not use current place myself  
What to replace with? No place?

**Comment by gerhardol** [comment]
Note: Corrections to pace done in #690 
All outputs should be rounded, for instance km/mi with two decimals
Close?

**Comment by davidedelvento** [comment]
Two decimals of what? Even that could be too many IMHO, i.e. 1% accuracy or less. I'd strive for shorter, more effective messages, e.g. you are going at 7' 30" per km/mi. Even 7' 32" per km/mi is more accurate than the GPS measurement and I find it too confusing to listen when running: the brain tend to remembers the last number, i.e. "2"  in this example, and forget the most important first number, i.e. "7" in this example. After hearing these messages I am often left wondering <<was it 7' 22"? Or 6' 32"? or 8' 42"? Or what?????>>

**Comment by Marx2** [comment]
I agree. I know how pace is measured. Don't need to listen to "kilometers
per hour" every time.

wt., 14.08.2018, 16:43 użytkownik Davide <notifications@github.com> napisał:

**Comment by gerhardol** [comment]
In #730:
 * Cues for pace below 20 min/km is stopped
 * Units in audio cues are configurable
 * Distance is limited to three digits, i.e. 9.98 and 10.1

Please test
