### ISSUE TITLE
Android Studio 3

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#630]
AS3.0 should be released quite soon, beta5 right now.
I have been using AS3 to some extent since the alphas.
AS3 improves build speeds some, some better profiling and better constrain layout support (that is an option for a new interface).
Of course, you will get prompted constantly if you do not update after release (the opposite of Android on devices...)
Anyone against updating when officially released?

**Comment by davidedelvento** [comment]
Fine with me
