### ISSUE TITLE
Wear app dissapeared RunnerUp v1.58 & Wear 2.0

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#631]
Hi,

I recently got a new phone and of course started to download RunnerUp from play-store.
Using that version it seems like the Wear app has disappeared.

This is RunnerUp v1.58 and I have a LG Watch Urbane with Android Wear 2.0.0.alongnumber

I can help fixing this too...(but if someone has any pointers it would be helpful).

**Comment by Marx2** [comment]
I use the same version and have no problems on LG watch r with aw2. You can
always try alternate store Fdroid

**Comment by gerhardol** [comment]
The Wear app is still included in the ru apk. Google has changed recommendations to how this should be implemented and not include the wear apk in the phone apk, see #628. (A link to a private branch separating too.)
From what I can make out of the documentation the current solution should still work, also after Jan 18 2018, but after that RU will not qualify for the "Enhanced for Android Wear" badge or be eligible to appear in the Android Wear top charts.

**Comment by gerhardol** [comment]
Seem to be resolved

Note that the Wear companion app is embedded to the phone app, which is discouraged by Google. A standalone app does not make sense right now.
