### ISSUE TITLE
Strava connect is broken

### ISSUE THREAD

**Issue by truenicoco** [jonasoreland/runnerup#635]
Using RunnerUp v1.57 on LineageOS 14.1-20171018, I can't connect to my Strava account. If I go to settings→account→strava→connect, I'm prompted to enter my login and password. Once logged in, I can browse the Strava website but somehow RunnerUp doesn't use the session.
I have no idea whether it's related or not, but I'm using Firefox as default browser and Strava seems to use Chrome to display pages inside the app.

**Comment by gerhardol** [comment]
Works for me with the same version (on an SGS2).

Strava (and mother sites that use oath2 to authencicate) use WebView to connect. That is not really Chrome even if they are based on the same source.
After logging in you should come back to Accounts after connecting, not see Strava site.

**Comment by truenicoco** [comment]
I don't know anything about Android or Java, but let me know if I can help (further tests, logs or anything). I don't mind too much not using Strava, I ended up using Endomondo which looks fine too.

**Comment by gerhardol** [comment]
Do you have Play installed?
What version of WebView?

**Comment by truenicoco** [comment]
Ni google apps/play installed. I'm not sure where to look for webview version.

**Comment by gerhardol** [comment]
Default seem to be AOSP Web-view
https://forum.xda-developers.com/lineage/help/android-web-view-included-t3545350

This is what I use, that worked for me
I do not know how to continue either. I may play around with my phone

**Comment by truenicoco** [comment]
I tried again today out of curiosity and I managed to login and authorized the app. I guess there was something wrong with Strava back then. However, cycling activities are recognized as running activities there so it is a bit annoying. Should I open another ticket for this?

**Comment by gerhardol** [comment]
The type would be a separate issue. There is code for this at least (activity_type in http header is set to ride).
Will close this issue.
