### ISSUE TITLE
Swedish translation. Remove Swedish (sv) from Transifex.

### ISSUE THREAD

**Issue by jony0008** [jonasoreland/runnerup#637]
I started to work on the Swedish translation (Swedish (sv)) without knowing it was already finished (Swedish (Swedish (Sweden) (sv_SE)). Please remove Swedish (sv) to make sure nobody else makes the same mistake and rename Swedish (Swedish (Sweden) (sv_SE) to Swedish (sv) because Swedish is the same in Finland.

**Comment by gerhardol** [comment]
I do not have the background why it is like it is in Transifex, I also see "sv" as the one to use. If there are differences in sv_FI.
(In RU itself "sv" is used.)

Was the sv translation completely empty before you started, is the translation adding anything to the history?
What about reviewing the existing translation?

I see no way to rename a language in Transifex. It should be possible to remove and upload existing strings as"new", but then the history is lost.

**Comment by jony0008** [comment]
There are no differences in Swedish written in Finland and Sweden. 
Yes, the sv translation was completely empty before I started so you can remove it and I can review the existing translation.
Maybe you can ask Transifex support about renaming a language?

**Comment by gerhardol** [comment]
Removed in Transifex.
@jony0008 I set you as a reviewer too
