### ISSUE TITLE
Save activity button is remains disabled after entering all details of workout.

### ISSUE THREAD

**Issue by iamank1t** [jonasoreland/runnerup#640]
#### Expected behavior
After entering details about my workout(like duration, distance and pace), the save activity button needs to be in enabled state so that i can save my activity.

#### Actual behavior
I tried to save  workout in app. After filling all details(sport, duration, distance, pace) the save activity button remains in enabled state for 1 or 2 second and then again become disabled. 

#### How to reproduce
Download RunnerUp application from Android playstore. Open app, go to manual tab(last tab in your right side) under Start tab. Now do the following steps -
- Choose any "Sport".
- Don't choose any "Date", keep it as it is.
- Don't choose "Start Hour", keep it as it is.
- Set a "Duration".
- Set a "Distance".
- Set a "Pace".
- Add workout note if you want or keep it as it is.
Now after following this steps you will see the button remain green(enabled) for some second and become inactive again after 1 or 2 sec. 
 <pre>
<code>
* Device:  Samsung J7 Prime
* Operating system: Android 7.0 Nougatt
* App Version: v1.58
</code>
</pre>

#### Recording Of The Bug
https://www.youtube.com/watch?v=AIR4q4gnFrU
    
While playing video keep eye on the save activity button at bottom.

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@iamankit/save-activity-button-is-remains-disabled-after-entering-all-details-of-workout">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by gerhardol** [comment]
Closed with #677
