### ISSUE TITLE
Google fit connection

### ISSUE THREAD

**Issue by mindi-ef** [jonasoreland/runnerup#641]
Can not establish the connection to Google fit because of the embedded browser.

**Comment by gerhardol** [comment]
The plugin uses the WebView browser, updated from Play if available, with AOSP the AOSP WebView. So you need to be using a version up to date with Google requirements.
From what I now, the app uses the recommended way of connecting to Google Fit

**Comment by mindi-ef** [comment]
I use Oreo on a Xperia XZ1 and get every time the same result. Everything is updated.

**Comment by davethayer** [comment]
Here's the text of the error copied from my ZTE axon 7 (nougat):
> 403. That’s an error.
> 
> Error: disallowed_useragent
> 
> This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.
> 
> [Learn more](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html?m=1)
> 
> Request Details
> That’s all we know.

Looks like it might be a policy change at Google

**Comment by gerhardol** [comment]
In that case, Google Fit will not work

**Comment by 12people** [comment]
@gerhardol But it could be made to work. Google has a Fit API for Android: https://developers.google.com/fit/android/get-api-key

**Comment by gerhardol** [comment]
Yes,  it will require a rewrite of the authentication, maybe upload too. 
Hopefully the setup is similar to other plugins, but it is still a rewrite.

**Comment by ideefixe1** [comment]
I was able to workaround login by changing user agent string in OAuth2Activity's onCreate:
`wv.getSettings().setUserAgentString("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36");
`
so that login proceeds fine.

However, I get the following error during activity upload:

> 06-09 16:59:16.544 20948 23398 I org.runnerup.export.format.GoogleFitData: Creating new dataSource: derived:com.google.location.sample:973756715091:runnerup_activity_location
> 06-09 16:59:16.770 20948 23398 I GoogleFit: {"error":{"errors":[{"domain":"global","reason":"invalidArgument","message":"Expected dataStreamId to be: derived:com.google.location.sample:runnerup_activity_location"}],"code":400,"message":"Expected dataStreamId to be: derived:com.google.location.sample:runnerup_activity_location"}}

Does anyone know if export to fit was ever working?

**Comment by ideefixe1** [comment]
Thanks for info - I'm motivated to get google fit integration working; if noone else is working on this I will take deeper look.

**Comment by gerhardol** [comment]
Closed in #683, not officially supporting the account until someone fixes it
