### ISSUE TITLE
RunnerUp is using internal sdcard default

### ISSUE THREAD

**Issue by dracorp** [jonasoreland/runnerup#646]
Hi
While importing on fresh phone*, with Android 6.0 and RunnerUp 1.58:
![](https://lh3.googleusercontent.com/YUf2Km4X81I8dPaBPENaGst-FzevFqnYAamHDRtGCy32dUb8ebobogiz89crqirhH-K5qyk0OJVOveBQ38bvCC3nmfj-JukUKO9frmW897VQ20W9zQ1dfdiDGkJOXZ01ErBf3FrGlDbej6ydPXcJ8awGql9GhBBf42Xexx0lnrrQg-ssR3Yfv-X5zNATcZ57Q-r6O79k5Pl8TftWACDPZx68vv6vvQlrYyap-oWik5J7WL-PiPMo4AzxvgN2w1bG5caYj12LbBGV-ZYiAN5qKzakm0OyuPVbufWljQnlP8QO8jHN9w73zGLYLaXDFYXS5kIB4fGN2Lxuvk0S5Pb2YEdoPz-qNfMgvxBbmuFCTiRjptuvn_ArGMX4PKii8K-JuaO1r0m3yHYWTYhZ9QIXvUmdtENQasI8eV54Pb4rmA36_XwVZKIrpy7uNBqY2JvMZetsVo6o4XDTg8b7ahkSrIv047C6GUqp4NBIGOZ-jQ5WNUAHf747T26Jvfa5VemACR6sHjNSPYdMO0eR-XMnVinA_2qvV--XczxbNhymk1a_XUhwxZcOi-wsMvAziz76NvcPh2jJdcqajpHqBEF3KA85_FbUnxKXk95tuDWm=w300-h260-no)
RunnerUp use internal sdcard instead of external.  
*) myPhone Hammer Axe M LTE, OTA 1.0.14

**Comment by gerhardol** [comment]
As expected. This is what RunnerUp has access to.

**Comment by dracorp** [comment]
Is there an option to change it?

**Comment by gerhardol** [comment]
No, that would require a selection dialog and logic to request permissions.

**Comment by dracorp** [comment]
So I understand you don't want to many request permissions in app? I'm asking because I forgot about it twice after exporting and reset the phone.

**Comment by gerhardol** [comment]
The effort to change this is quite high, so I do not want to change the behavior

**Comment by dracorp** [comment]
Ok, thank you for explanation.

**Comment by ajhepple** [comment]
If I understand this issue correctly, it means that I can't move my RunnerUp history from an old phone, to a new phone, by exporting the database to the _external_ SD card.

However, can I put the `runnerup.db.export` database dumb onto the _internal_ SD card of the new phone somehow, making it available for import by RunnerUp?

**Comment by gerhardol** [comment]
@ajhepple 
Correct
