### ISSUE TITLE
Current pace totally broken

### ISSUE THREAD

**Issue by davidedelvento** [jonasoreland/runnerup#659]
For me the current pace is just a random number in the range half the activity pace to twice the activity pace. Others I've spoke with report similar problem, or even current pace not being reported at all (looking at the source code, it's obvious why and is related to the hardware).

I have a patch which calculates the current pace from last distance and last time, instead of relying on the inaccurate (or unavailable) GPS-based speed. Field tests performed so far show it's much more accurate, and (obviously) available for any device. Would you like a PR?

**Comment by gerhardol** [comment]
If you have a proposal, a pr is always easier to discuss. If it is work in progress, just write that in the PR (for instance wip in the title). 

I do not use current place at all myself but can see problems in the emulator (pause detection is useless partly due to pace).

**Comment by gerhardol** [comment]
I get notifications but I have no computer at the moment - replaced parts but the new was malfunctioning so it is at the shop.

**Comment by gerhardol** [comment]
See #722, #730 for smoothed pace.

**Comment by gerhardol** [comment]
Please try RunnerUp Alpha for the improvements to current pace
