### ISSUE TITLE
ANT+ sdk license/sources

### ISSUE THREAD

**Issue by Bubu** [jonasoreland/runnerup#662]
Trying to update this for f-droid: https://gitlab.com/fdroid/fdroiddata/issues/1192#note_71985493

I couldn't find any sources for the `ANT-Android-SDKs/ANT+_Android_SDK/API/antpluginlib_3-6-0.jar` and just deleting it breaks the build.

I fear this is actually not open source software and in turn can not be included in f-droid, right? Can this be made optional so that f-droid can build and distribute a stripped down version with support for this protocol removed?

**Comment by gerhardol** [comment]
ANT+ is not open source. Compare this to the Samsung BLE 4.2 lib that was optionally disabled by ricky from F-Droid.

**Comment by Bubu** [comment]
@gerhardol thanks for clarifying. In that case we need to indeed remove all existing versions from f-droid as they never should have been included in the first place.

I just pushed the removal, will take effect in about a day.

I'm happy to introduce this back into f-droid when someone comes up with a solution that makes using the ANT+ SDK optional for the f-droid build.

**Comment by gerhardol** [comment]
Keeping this open

**Comment by docloy** [comment]
Are there any news. Will there be a version available which can be distributed through F-Droid store?
Or maybe you could offer a built APK within the github  repo?
I did reinstall my mobile and can't find an APK. I'm not using any google services. Therefore I can't use the Playstore version.

Would be awesome if you can help me. Thanks in advance!

**Comment by gerhardol** [comment]
No one has done the change in the source to optionally exclude ANT+ so no F-Droid yet.

There will be a beta in some time, but the GUI is still being changed, not stable yet

**Comment by gerhardol** [comment]
PR to reenable F-Droid: https://gitlab.com/fdroid/fdroiddata/merge_requests/5102
