### ISSUE TITLE
Runtastic connection seems broken

### ISSUE THREAD

**Issue by 12people** [jonasoreland/runnerup#678]
After logging in with a Runtastic account, the Runtastic dialog keeps reappearing and no connection seems to be established.

I've checked that the email and password are correct.

**Comment by gerhardol** [comment]
This is "resolved" by disabling the account for now. 
There are more accounts being disabled than being active right now, it takes some effort to maintain them. 

Workaround is to export to file and upload.

**Comment by Marx2** [comment]
I think they should be in form of plugins

czw., 5.07.2018, 07:17 użytkownik Gerhard Olsson <notifications@github.com>
napisał:

**Comment by 12people** [comment]
@gerhardol 
Given that one can enable and disable services himself, it's not clear which services work and which ones don't.

I've disabled and enabled some manually (while developing) and have no clue which ones were disabled initially.

Could we simply eliminate the non-working ones from the overview and show a message on first use that they've been eliminated?

<img width="361" alt="image" src="https://user-images.githubusercontent.com/7361228/42316507-4d7d3758-804a-11e8-9caf-eb13a7542af1.png">

That way, we'd avoid any confusion.

And if we could, could you please send me a list of the services that no longer work?

**Comment by gerhardol** [comment]
The account status is much more dynamic than releases can ever be. Plugins would add flexibility but is a major OH to projects like this. I rather put effort on frequent releases (automating).

Current status is in Git (I tested a few days ago).
This currently runs at every startup.

https://github.com/jonasoreland/runnerup/blob/6af7685b64531ccd72e857381ba2ec4c14be17b1/app/src/org/runnerup/db/DBHelper.java#L455

**Comment by gerhardol** [comment]
Also, there is a page in the wiki:
https://github.com/jonasoreland/runnerup/wiki/Synchronization-with-external-providers

A popup should probably be pointing at that page. (It was not update, I just updated it, should have been done together with the code.)

Longer term, time is probably better spent syncing with Tapiriik. Maybe a direct connection, maybe using one of the other services like DropBox.
I guess Strava and RunKeeper should be priotized too (if they would fail). Some of the other have been hacks it seems. (Tapiriik currently supports 19 services, but not Runtastic.)

**Comment by 12people** [comment]
@gerhardol What do you think about eliminating the services from the overview, but keeping the code there in case anyone wants to upgrade it?

**Comment by 12people** [comment]
@gerhardol Alright. What if we removed the option to set services as disabled manually? The problem is that, after long-pressing on some services, you can no longer tell which were disabled initially and which ones weren't.

**Comment by gerhardol** [comment]
The idea with being able to disable was to be able to hide services no longer working (and a defensive approach if something starts to work again). If understanding is better to not do this dynamically, then the dynamic handling can be removed.

**Comment by Marx2** [comment]
It should be three states: enabled, disabled, not working. You can try
enable not working, but warning message should tell you, that it probably
will not work.

As for plugins, maybe they should be written in scripting language. That
way it would be possible to upload text file with script in settings,
without compiling. Seeing how long we usually wait for new version, it
could be useful. But it's just idea.

czw., 5.07.2018, 23:55 użytkownik Gerhard Olsson <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
Getting Tapiriik working will decrease maintenance a lot.

Three states is not enough, it is not even clear what is not working...

**Comment by gerhardol** [comment]
Closed in #683, not officially supporting the account
