### ISSUE TITLE
Wrong encoding during upload to jogg.se

### ISSUE THREAD

**Issue by nebmo** [jonasoreland/runnerup#7]
"Gps brÃ¥kade." in description

**Comment by jtolkanowicz** [comment]
I have successly uploaded gpx or tcx files to with special characters and normal ones in description field to:
- jogg.se
- garmin connect (mobile app)
I don't see them being populated.   @nebmo can you do it once more or maybe we can close this issue ?

**Comment by gerhardol** [comment]
jogg.se and Garmin are no longer supported as accounts with direct uploads as the interfaces are changed. (Garmin requires $5000 and jogg.se changes are not public I believe.)
So unfortunately this have to be closed.
