### ISSUE TITLE
RunnerUp 2.0 alpha 1

### ISSUE THREAD

**Issue by gerhardol** [jonasoreland/runnerup#724]
First alpha release for RunnerUp 2.0
Changes described here:
https://github.com/jonasoreland/runnerup/blob/master/app/assets/changes.html

This release identifies as org.runnerup.alpha and can be used i parallel to the Play release.
No apk release right now, I expect the first testing should be done with private builds anyway.
I will try to setup signed builds for Travis together with Jonas - maybe even push to Play eventually.

**Comment by gerhardol** [comment]
@djibux RunAlyze (and Dropbox) requires a separate key, not shared in the repo (similar should have been done for the existing services).

@mipapo How do you want to handle this, separate keys for all developers?

In some time, we should setup autosigned builds in Travis.

**Comment by mipapo** [comment]
@gerhardol I could setup a testing instance for interested developers

**Comment by djibux** [comment]
@gerhardol, my bad, I did read about it somewhere.

There seems to be another issue: the heartrate is recorded but no longer displayed (on both the phone and my Pebble).

**Comment by gerhardol** [comment]
@djibux 
#727 Will enable testing.runalyze.com, @mipapo setup a test key

For HR during a run, I fixed #758

**Comment by rickyepoderi** [comment]
Hi,

I updated my runalyze env to 4.3.0 and synch is broken (very different). But checking the current code in runnerup it seems that now there is an api (or it's going to be). @mipapo when is the api going to be present? In a future version? Should I better go back to 4.2.0 and wait until runnerup and runalyze both have a new version?

Thanks!

**Comment by mipapo** [comment]
@rickyepoderi  The API is present at runalyze.com - There are no more open source version of RUNALYZE anymore

**Comment by gerhardol** [comment]
master in RunnerUp syncs to runalyze.com API (version is reported as 4.3.35).
But you need a private runalyze key to sync. I will publish binary builds with support later, I am waiting for Jonas to decide how he wants to handle builds. (I do not have a Play verified key, so users will have to change settings to install if I publish builds.)

**Comment by rickyepoderi** [comment]
@mipapo Very sad to hear that, but I suppose you have your reasons. Thanks for sharing it all this time.
@gerhardol Sorry but I'm not going to upload my data (heart-rate inclusive) to any public site. I had installed runalyze locally in my desktop.

I have to think again what to do with my activities. Indeed I just wanted a backup, not all the magic that runalyze does.

**Comment by 12people** [comment]
@rickyepoderi You could sync to a file and keep that file backed up using NextCloud.

**Comment by rickyepoderi** [comment]
@12people Yep, that's a possibility, I also have nextcloud in my desktop. Thanks!

**Comment by gerhardol** [comment]
The alpha also adds Dropbox synchronizer (you will have to add a key here too) or use FileSync and any local synch+cloud.

**Comment by 12people** [comment]
@gerhardol Any update on this? Still waiting for keys from @jonasoreland ?

**Comment by gerhardol** [comment]
Time to send another reminder. 
I could release with my keys, but they are not play store verified and most will have to change settings. Or someone else takes over.

**Comment by 12people** [comment]
@gerhardol 
I'm guessing no luck getting the keys so far? Given that it's taking more than 4 months to get the keys, perhaps the best thing to do would really be to release under your own keys. (Though I'm not sure what exactly that means for end users.)

It's the 2.0 release, so hopefully people will be more forgiving.

**Comment by mipapo** [comment]
Which keys are missing? Runalyze? I didn't got any mail

**Comment by moobyfr** [comment]
Hi, if it's only a Key problem, don't stop your work only for a signature /
name problem, the feature are more important

**Comment by Marx2** [comment]
I think there's communication problem with original author of runnerup. I
also think there's no sense to wait longer and release different way

pon., 31 gru 2018, 22:57 użytkownik Blindauer Emmanuel <
notifications@github.com> napisał:

**Comment by gerhardol** [comment]
I have got the key (a couple of weeks ago), but do not have the key alias, so hopefully not so long time now....

But re-releasing should not be a problem, but then the existing user base will not follow.
If someone is interested in being the maintainer, go ahead. I am not the most active user and thereby the best maintainer but I am sure interested in seeing the app flourish. (Two weeks of these two months is due to me not testing keys immediately, I should also have asked for the key earlier than to try setting up automated builds etc.)

Anyone can make a build and publish the .apk, but you need a play approved key (which I do not have) to not require users to tamper with settings.
As the current version identifies as a separate application, it should not be an issue.
(There is a small cost with getting a key, I have not taken that route as I do not have had any intention to fork.)

Especially thanks to the @12people for the nice work done, it should be visible for normal users.

Happy new year everybody!

**Comment by 12people** [comment]
Awesome, can't wait for the release then! :)

Happy new year everyone!

**Comment by gerhardol** [comment]
https://github.com/jonasoreland/runnerup/releases/tag/v2.0.0.2

Jonas had been away for some weeks, now all is cleared
Separate announcement later

**Comment by gerhardol** [comment]
Closing, alpha 2 and 3 released
