### ISSUE TITLE
Crashes on every single launch, on Android 9.0, Pie.

### ISSUE THREAD

**Issue by cadeanwvu** [jonasoreland/runnerup#733]
I am using an Essential Ph-1 phone with near-stock Android 9. Installed from Play Store(1.58). Each time I try to run the app, I see it for a split second, and then it disappears and shows the home screen, but a notification remains in the notification pane. The notification says "Searching for GPS". If I try to tap the notification, I get a pop-up that says "RunnerUp keeps stopping" with choices for viewing app info, closing the app, or sending feedback. I've sent feedback with logs several times. 

If I choose the "Close app" choice, the notificaiton for "seeking GPS" remains until I reboot or force close the app from Settings. Other apps get a GPS fix very quickly.

**Comment by gerhardol** [comment]
I do not have access to the logs so I cannot help there.
The logcat could help though, or if you debug.

However, a new version of RunnerUp is on its way, when we have solved build keys etc there will be a public alpha.
That version has a new user interface, many internal changes and is at least adopted to Android Oreo - that is what I can test with.

**Comment by gerhardol** [comment]
Can you please try the latest alpha for 2.0?
https://github.com/jonasoreland/runnerup/releases/

**Comment by gerhardol** [comment]
Close due to inactivity
