### ISSUE TITLE
Alpha 2.0 release - text in app overlaps in dutch

### ISSUE THREAD

**Issue by maxvisser** [jonasoreland/runnerup#746]
Awesome! Nice alpha release of 2.0

See these two attached screenshot on different devices, text and icon show overlap when set to Dutch.

![](https://i.imgur.com/sWXWD9i.jpg)

![](https://i.imgur.com/69XJXIN.jpg)

Some willing to fix it? An option to switch in-app to english would also work :)

**Comment by gerhardol** [comment]
It is similar in Swedish. Me and @12people had some discussion about it.
What about removing the text on the tabs?

**Comment by 12people** [comment]
@gerhardol I guess that'd be the best option for now. For later releases, if the minSDK is increased, we can use the native navigation bar element that only shows the current page's title.

**Comment by maxvisser** [comment]
I tried fixing it by changing 'Geschiedenis' to 'Historie'. 
https://github.com/jonasoreland/runnerup/pull/747

**Comment by gerhardol** [comment]
Thanks, I assume it was you that updated on Transifex, including the other updates
