### ISSUE TITLE
Alpha 3 reporting an inaccurate historic duration/pace

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#754]
I'm not sure if this is where we log any potential issues for the new Alpha release.  I'm using v2.0.0.3 and I did an activity that lasted 1:03:31.  When I went into the activity within the app afterwards it is showed the duration as 0:54:13.  I edited to enable Recalculation and hit that button a few times but nothing appeared to change.  However, afterwards I noticed that this had actually changed to 1:08:57.  Subsequent recalculations do not seem to make any difference.  The pace for the run is correctly calculated based on the historical distance and duration but as this is wrong then the pace is wrong too.

There were no pauses during this run and there is only one <trkseg> in the gpx file.  The map shows no missing points or jumps.  The exported GPX file from RunnerUp confirms the correct start/end time and Strava can correctly calculate the right values.  This is not happening on any other workouts but I can't remember when I switched to beta 3 so there is a possibility that this is the first one.

I'm attaching a screenshot along with the .gpx for reference but I don't think it tells you very much apart from the fact that I am a slow runner...   :)
![screenshot_20190121-175133](https://user-images.githubusercontent.com/10944929/51491194-78806300-1da5-11e9-85e0-dc847bcc7b36.png)

[RunnerUp_0007.gpx.txt](https://github.com/jonasoreland/runnerup/files/2779999/RunnerUp_0007.gpx.txt)

**Comment by Cagier** [comment]
Sure.  Here you go...

[RunnerUp_0007.tcx.txt](https://github.com/jonasoreland/runnerup/files/2780380/RunnerUp_0007.tcx.txt)

**Comment by gerhardol** [comment]
The tcx/gpx includes the trackpoints and is 1:03.
The tcx header has the total time adding the differences for all trackpoints - if there are pauses there will be a difference. 

I will have to look into if there are rounding, maybe log just pauses to minimize precision.
There is a difference for distance too, only one meter though. The total distance has no reference calculation (stoptime-starttime though)

Recalculate does not really do anything

**Comment by gerhardol** [comment]
Recompute is not working properly. At least it will mess up HR averages.
When recalculating, less accurate data is used than in the live calculation too.
(I see some strange effects too, investigating.)

The important is the initial calculation. I cannot see any reason.
What phone and Android version?
Is the time in the phone in sync with the GPS time?

**Comment by Cagier** [comment]
I think when I was running it was accurate but before I did any recompile
the history showed up as incorrect. A subsequent run since then was OK. The
time is good on the phone as it is synced automatically with the network.
There should be no HR data in the file I submitted as I was not wearing a
monitor.

**Comment by gerhardol** [comment]
> time is good on the phone as it is synced automatically with the network.

Network time can differ minutes to the GPS time. The GPS time is not trusted in the app either (that was probably an old Android bug, but it is risky to remove those too...) The internal sensors like cadence is also affected by this problem, the sync is done regardless.

**Comment by gerhardol** [comment]
Submitted a PR with a fix and some improvements.
Press save quickly after stop to avoid the problem until then.
