### ISSUE TITLE
Alpha 3 audio cues stop after first message

### ISSUE THREAD

**Issue by SFL01** [jonasoreland/runnerup#757]
As in the title, audio cues are not working after the first message with information on the session ( ie not the session's start one ). I' ve setted time triggered cues ( every 60 seconds ). Stock android 5.1, older runnerup database imported.

**Comment by Cagier** [comment]
I meant to log this as well as I noticed the same problem. It only gives the first cue when I set a distance-triggered auto-cue (e.g. every 1000m). My workaround had been to use lap-triggered cues and auto-lap the required distance. Interval cues are fine.

**Comment by gerhardol** [comment]
Confirmed, not found the issue yet

**Comment by gerhardol** [comment]
Closed in #762
