### ISSUE TITLE
Not recording since new android upgrade to pie

### ISSUE THREAD

**Issue by thermalization** [jonasoreland/runnerup#760]
Both the beta 2.0.3 and the previous Runnerup no longer work on Nokia 7+ with it's Android upgrade in mid October 2018: All recording start but don't stay active unless you directly watch the screen, which doesn't happen if you put your phone in a pocket. Google Play shows similar comments of Runnerup no longer recording the track.

**Comment by gerhardol** [comment]
This seem to be similar to this:
https://github.com/jonasoreland/runnerup/issues/668#issuecomment-464370305
Nokia link:
https://dontkillmyapp.com/nokia

Have you tried the workarounds described in the link?
Is it possible to debug or create a logcat when the problem occurs?

RU (both 1.x and 2.0) works fine on my Moto X4 with Motorola Pie (quite vanilla Android). 
I have tried to follow the Google recommendations for background apps (and it is OK in my phone). 
If we know what Nokia is doing, there could be a workaround.
The only one found at dontkillmyapp is to keep the screen on all the time.

(I have a limited view of comments on Play and no access to logs or stats there.)

**Comment by thermalization** [comment]
Force closed that Nokia Power Saver app, but as soon as screen is closed its stops logging position. It definitely was working before October 2018. I'll look to get that log.

**Comment by JTailor** [comment]
Have the same problem with Nokia 8 and Android pie even with Nokia Power Saver app closed.
Other track&trace app's don't have a problem. Also not a problem with the screen always on.

**Comment by gerhardol** [comment]
Recording in Pie work fine with my phone, so it is not a general problem.
dontkillmyapp.com mentions pecularities with foregroundService too, maybe that is the special with Noxia.
Can someone provide a logcat for when the recording stops, it would be of help.

**Comment by JTailor** [comment]
[logs-2019-04-18-13-53-58.zip](https://github.com/jonasoreland/runnerup/files/3094608/logs-2019-04-18-13-53-58.zip)



[logs-2019-04-18-13-53-58.zip](https://github.com/jonasoreland/runnerup/files/3094611/logs-2019-04-18-13-53-58.zip)



[logs-2019-04-18-13-53-58.zip](https://github.com/jonasoreland/runnerup/files/3094612/logs-2019-04-18-13-53-58.zip)

**Comment by JTailor** [comment]
My first try with android 'debug' 
Attached you have two files from runnerup and a third from MATLOG.
If you need other info don't hesitate to ask. Looking out for version 2.0 working on my NOKIA 8

**Comment by gerhardol** [comment]
@JTailor 
I cannot find anything about RU in the logs. I would like to get information why Nokia kills the app. A logcat when starting RU could give info, but likely information when the app is killed will be required too.
What is different in the Nokia compared to my quite stanard Moto X4?
Any other devices with the problem?

**Comment by gerhardol** [comment]
@JTailor 
Thanks for the confirmation

It seems like Nokia/HMD/FoxConn has softened the powersaver policy lately:
https://github.com/urbandroid-team/dont-kill-my-app/issues/57

It would still be good to find if there is another way to handle the powersaver.

**Comment by gerhardol** [comment]
Latest version has a check if GPS is allowed in the background (Android 10) and if an app is battery optimized. I have not found a general way for non standard power saving.
Do not believe much more can be done.
