### ISSUE TITLE
Always goes in pause since gps rollover

### ISSUE THREAD

**Issue by kroeckx** [jonasoreland/runnerup#767]
Since the GPS rollover last weekend, it's goes into pause every 5 seconds. I have one application that shows the GPS date now being in 1999. I assume that it looks at different time sources and gets confused.

**Comment by gerhardol** [comment]
Try deactivating AutoPause (some other bugs with that in the Play version)
Autopause probably uses the GPS speed to evaluate auto pause, so if that broke at the rollover, auto pause will be broken in Play version.
The Alpha version can use the GPS point/time to evaluate auto pause.

**Comment by gerhardol** [comment]
No recent problems reported about this.
There has been users that have deactivated GPS prompted by Google, there are now checks when starting GPS.
Closing
