### ISSUE TITLE
Endomondo cadence

### ISSUE THREAD

**Issue by sergentum** [jonasoreland/runnerup#774]
Hi guys, it's not an issue and i'm talking not about that particular app, but more about endomondo POST info. I see in the code:
```
// # timestamp;
// # type (2=start, 3=end, 0=pause, 1=resume);
// # latitude;
// # longitude;
// #;
// #;
// # alt;
// # hr;
```
And here what i see in debug:
```
2019-04-24 05:18:56 UTC;;55.03490402;82.9214087;0.005799526220187545;;184.55382921676835;;
2019-04-24 05:18:57 UTC;;55.03490388;82.92140797;0.005848734693601728;;184.55383027650828;;
```

I have question - don't you know where to put cadence? It should be there, but i don't know how to figure it out other than bruteforce.

**Comment by sergentum** [comment]
i found that 5th is a distance and 6th is a speed.

**Comment by gerhardol** [comment]
> i found that 5th is a distance and 6th is a speed.

Distance is normally derived from GPS and ignored, not sure about Endomondo.
Similar for speed, derived from time/distance.

RU could provide those of course, not sure if the values were recorded earlier.

There should be an official description of Endomondo format. It may be removed, like Runkeeper has done of course.

**Comment by sergentum** [comment]
> There should be an official description of Endomondo format.
That would be great but i can't find any mentions. Probably I'll try to find someone who have cadence tracker and ask him to record endomondo traffic, because i can't imagine any other way

**Comment by sergentum** [comment]
Ok, guys i disassembled last version of endomondo and found the code how they do it:
// # timestamp;
// # type (2=start, 3=end, 0=pause, 1=resume);
// # latitude;
// # longitude;
// # distance;
// # speed;
// # alt;
// # hr;
// # cadence;
// # power;

as far as i can see none of them are mandatory but it's better to have all semicolons in input, even if it's empty. So for now it's 10 semicolons should be. In previous endomondo version there wasn't power, but cadence was and it' didn't appeared when i used only 9 semicolons.

Thanks for all, hope my info will be usefull for anybody

**Comment by gerhardol** [comment]
Added cadence to the app too

**Comment by gerhardol** [comment]
@sergentum 
Thanks for your investigation, it was simple to dd to RU
