### ISSUE TITLE
V2.0.0.4 Material Design

### ISSUE THREAD

**Issue by lowtower** [jonasoreland/runnerup#781]
Hello @gerhardol,

the new design in v2.0.0.4 is a step forward compared to v1.58, but still not very fancy.

@12people has already worked on the design (#295), which really looks nice.

Is there any chance that the design is improved even more in the direction of @12people ?
Or asked differently: what was the reason not to  use his design?

ping @12people: Your [git account](https://camo.githubusercontent.com/8bb8f74f36cae15616731ab8e01b4b5401f74911/68747470733a2f2f73746f726167652e6a756d7073686172652e636f6d2f707265766965772f726963684276794f75334a69626d546e3379635f5a4f61596a31455a5f723342394f395174575a6645494a52354c556849713949646556653334595650476d41374767756f655a48514f626c505649416c4435364a743049712d5f5a4d49776c4a4e717375367334624f3046316b5233644d556a656471433136754255753835) is not available anymore.

Thanks in advance,
LT.

**Comment by 12people** [comment]
@lowtower What does that mean?

As for my design, there isn't a consistent concept ready — it would take some time to finish that up. 

Much of what you see in v2.0.0.4 was done by me, and though it might not look like it, it was a bunch of work — there's a lot of legacy code to get oriented in, and the drop-down menu was a custom widget where I had to separate the view and the model.

I don't really have the time to devote to this project right now (finishing up my Master's right now). Besides, until version 2 hits the Play Store and F-Droid, I don't really see reason to work on this further. 

Getting the current work out to users should be of utmost priority now.

**Comment by lowtower** [comment]
@12people 

I mean the link to [https://camo.githubusercontent.com](https://camo.githubusercontent.com/8bb8f74f36cae15616731ab8e01b4b5401f74911/68747470733a2f2f73746f726167652e6a756d7073686172652e636f6d2f707265766965772f726963684276794f75334a69626d546e3379635f5a4f61596a31455a5f723342394f395174575a6645494a52354c556849713949646556653334595650476d41374767756f655a48514f626c505649416c4435364a743049712d5f5a4d49776c4a4e717375367334624f3046316b5233644d556a656471433136754255753835), where as, I understood, were located the changes of Your branch!
Maybe, I misunderstood!

**Comment by lowtower** [comment]
I am sure, it was a lot of work.
Didn't want to offend anyone, Sorry, if You felt like that!

I just saw the huge difference to the images [You provided](https://www.figma.com/file/SlPQaT56OztqaLmFZAeM0y/RunnerUp) and asked myself, why it wasn't implemented!

I just start looking at this project and don't know what happened in the past.

**Comment by 12people** [comment]
I wasn't offended.

I just wanted to make clear that it takes a lot of work to make seemingly small changes. There are things like sliding to switch tabs or color-coded headerbars that need to wait for some serious code refactoring to be done (esp. switching from Activities to Fragments for tab content).

What would be needed here is more development power to make these necessary changes. As it is, things are progressing slowly (for reference, Alpha 1 was released on Aug 11, 2018, around 9 months ago).

**Comment by lowtower** [comment]
> What would be needed here is more development power to make these necessary changes

That's why I opened this issue.
I am new to this project and willing to help but not a android or java developer (yet).
I try to find out if this project is worth it to start learning the basics.

**Comment by gerhardol** [comment]
RunnerUp needs a new maintainer
I am not using RU enough myself right now and someone with more interest will drive this forward in a better way. My primary use for RU is as a logger where I can get all available data on my phone and I want an open source alternative

(I still spend hours every week in average, but are users interested in e.g. why RunningAHEAD no longer works?)

**Comment by lowtower** [comment]
@gerhardol, I understood You were taken over the lead from Jonas and maintain this project.
If not, I suspect, it's dead :-(
