### ISSUE TITLE
Some texts are not translated

### ISSUE THREAD

**Issue by Marx2** [jonasoreland/runnerup#788]
I see that translation english -> polish is done for some text as long as 2 years ago, but latest beta doesn't see it.
For example untranslated are: Step sensor, Lock activity button, Temparature sensor, Pressure sensor and much more.
Is it because nobody reviewed translation?

**Comment by gerhardol** [comment]
I believe it can be setup to require reviews, but I do not find any such setting.
Anyway, the PL texts are updated now and will be included in next release.
(I await feedback for 2.0.0.5/the play release, none so far).
