### ISSUE TITLE
Audio Cues sometimes finish with the extra word "Current" (Alpha 2.0.0.6)

### ISSUE THREAD

**Issue by Cagier** [jonasoreland/runnerup#795]
If I have distance-triggered audio cues on but only have triggers for activity and/or lap related cues then the word "Current" is included at the end of the announcement.  If there are cues for the current scope then these will work correctly.  I suspect this may have been introduced by the previous pull request for "Audio cue for current cadence" and, if so, then probably relates to the code marked "TO DO".

**Comment by gerhardol** [comment]
If you have Current Cadence selected, Current will be included also if there is no Cadence. So untick that.

**Comment by Cagier** [comment]
I don't have it ticked.  I just have Distance Triggered audio cue / End of lap audio cue / Lap Start / Include Unit in audio cue / 
Total Distance /Total Time  / Lap Time
Test Audio Cue works fine but when I actually run then it adds the extra word "CURRENT" at the end.

**Comment by gerhardol** [comment]
I cannot reproduce with the settings you describe.
Cannot see how this could occur. 
Just have to ask: No chance you select a profile with Current?

**Comment by Cagier** [comment]
OK. Sorry for your wasted efforts!  I cannot replicate this myself any more.
I was running on the previous alpha and I had the Current Cadence ticked.  I always had this issue but never bothered to switch it off.  I am 99% sure that I tried it both on and off and still had the error (with the current apha) but I cannot get it to do this any more.  I know this should say "Current x revolutions" but as my stepometer is broken in that phone it may explain why it just said "Current..." instead.

It was made a bit more confusing as it did not say "Current" with the Test Audio Cue button but does when you are moving.  I'm not sure if you can tick this option if your phone does not have a built-in stepometer at all.  I just moved to a new phone in the meantime and cannot replicate at all as it says 0 revolutions (even if not moving).  The old phone still just says "Current.." but as I said that is with no stepometer.

I'm still convinced I had nothing Current ticked at some point when testing this but I've tried switching things off and on a few times and cannot get it to happen again so no problem and again sorry to waste your time!
