### ISSUE TITLE
GPS filtering

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#81]
Edit: renamed issue, as these comments mostly deal with GPS filtering.

~~I've done some preliminary looking into runtastic imports (manually uploading an exported tcx and gpx), and the tcx data successfully imported pauses, while the gpx file didn't.~~ (see issue #89)

There seems to be an issue with elevation; a 5 minute entry on mostly flat ground is reporting 360-390 foot elevation gain/drop...

**Comment by gerhardol** [comment]
See #257
