### ISSUE TITLE
Spinner shows double down arrow

### ISSUE THREAD

**Issue by december-soul** [jonasoreland/runnerup#831]
On my Samsung Galaxy S8+ all Spinners shows double arrow

![Screenshot_20190807-151109_RunnerUp](https://user-images.githubusercontent.com/5879639/62625611-d9c4e980-b925-11e9-9a09-b0dfdfde4dc6.jpg)

I have changed the following code to fix it on my device.

```
diff --git a/app/res/layout/title_spinner.xml b/app/res/layout/title_spinner.xml
index 5f50f212..7db24ee8 100644
--- a/app/res/layout/title_spinner.xml
+++ b/app/res/layout/title_spinner.xml
@@ -21,7 +21,6 @@
     android:layout_height="fill_parent"
     android:layout_marginBottom="4dp"
     android:layout_marginTop="4dp"
-    android:background="@drawable/title_spinner"
     android:clickable="true"
     android:focusable="true"
     android:gravity="center_vertical"
@@ -53,7 +52,7 @@
 
     <Spinner
         android:id="@+id/spinner"
-        android:layout_width="0dp"
+        android:layout_width="10dp"
         android:layout_height="0dp"
         tools:ignore="UnusedAttribute"
         android:spinnerMode="dialog" />
```

![Screenshot_20190807-150943_RunnerUp](https://user-images.githubusercontent.com/5879639/62625610-d9c4e980-b925-11e9-8b61-98b01059f678.jpg)

**Comment by gerhardol** [comment]
If you submit a PR you will get the credit too...
(will look at this)
I plan to make a 2.0.2 release soon.

**Comment by gerhardol** [comment]
The visual change is in Pie, so the change need to put in layout-v28

Tried quickly to find what that causes this, but did not find the reason

As I hopefully will make a release today, I will make the PR myself (to make sure the PRs are merged in order, my bigger changes after this).
