### ISSUE TITLE
Feature request: use buttons for start/pause and mark a new lap

### ISSUE THREAD

**Issue by koylio** [jonasoreland/runnerup#847]
Thanks for writing this great app, very happy with the 2.0.2.1 version. I'm using it to replace my dying Forerunner 405. I'm used to running my repetition drills on a level road using terrain as distance markers, and pushing new lap button on end of each active and resting phase. Doing this with touch screen is quite difficult. Would it be trivial to add option to use device hardware volume or other buttons to start/stop activity and mark a new lap? Another way would be using headset button as new lap and start/pause on double click or long press, or even an option to use headset button to mark a new lap instead start/pause. I'd guess track runners would like this feature too.

**Comment by gerhardol** [comment]
I would like this too, but the app need to be a media app playing a sound to have button control since android 4.4. So you have to give up on music. 

It may be possible to use voice commands later, but not with a lockscreen. 

The notification has quick actions to kind of simplify this.

**Comment by gerhardol** [comment]
Closing, as there is no possibility to do this
