### ISSUE TITLE
RunnerUp Can't connect to Strava

### ISSUE THREAD

**Issue by dgeenens** [jonasoreland/runnerup#851]
Since 15 october 2019 I am no longer able to share an activity to Strava. I tried reconnecting in the runnerup app, but get an invalid request message after entering my strava credentials.

**Comment by gerhardol** [comment]
Hello

Strava is changed in the 2.x version. I have asked Jonas to release it in the standard Play update, not yet done.
Join the beta program or install directly from GitHub, the binary is the same.

**Comment by moobyfr** [comment]
I'm also facing this issue, and I'm running 2.0.0.4 (apk from gihtub)
The json returned when trying to login:
{"message": "Bad Request",
"errors": [{"resource": "Authorize"},{"field":"scope"},{"code":"invalid"}]
}
I'm also unable to upload to strava since several

**Comment by gerhardol** [comment]
You need at least 2.0.2.0 for Strava (some functionality from 2.0.0.5).

**Comment by moobyfr** [comment]
I confirm, upgrading to the latest version solves the problem to upload to Strava
