### ISSUE TITLE
Incorrect speed calc

### ISSUE THREAD

**Issue by GormCh** [jonasoreland/runnerup#852]
The total average time isn't right.
Gorm
![Screenshot_20191123-094911](https://user-images.githubusercontent.com/27847008/69477061-fe17d980-0de1-11ea-86be-716ad0aea3a5.png)

**Comment by gerhardol** [comment]
The average pace is calculated from time and distance and is calculated correctly.
Maybe autopause (there has been corrections in those calculations in 2.0).

What version are you using?
Can you share the tcx?

**Comment by GormCh** [comment]
Hallo.
Version 2.0.2.1

Gorm



Den 23 november 2019 20:39:04 skrev Gerhard Olsson <notifications@github.com>:

**Comment by GormCh** [comment]
Hi.
Should have added that updates to my Runkeeper account doesn't work. It say 
it's updating but nothing is seen on Runkeeper. It's not a big thing but it 
did work before.

Gorm

Den 23 november 2019 20:39:04 skrev Gerhard Olsson <notifications@github.com>:

**Comment by gerhardol** [comment]
Runkeeper works for me (also remove/add the account) but expect it to stop working as rk has removed official support of the api. 

The tcx is required to investigate.

**Comment by GormCh** [comment]
[RunnerUp_0098.zip](https://github.com/jonasoreland/runnerup/files/3883767/RunnerUp_0098.zip)

**Comment by GormCh** [comment]
Hi!
I replied via email on 23rd and attached the file. Tried to to it directly here on Github and got a message that the file type is not accepted.  I sent a zip instead.

Gorm

**Comment by gerhardol** [comment]
Created a PR
You can fix the total time by Edit->Recalculate too

**Comment by GormCh** [comment]
Yeah, that worked.
Issue closed.
Gorm

**Comment by gerhardol** [comment]
The change is merged to master
