### ISSUE TITLE
Export to tcx files limited to 100

### ISSUE THREAD

**Issue by Git-GT** [jonasoreland/runnerup#853]
Hi, 
I'm trying to export all my activities to a standard file format like tcx.
The available backup feature allows only to create a sqLite file that can't be used by other applications/portals (I can't upload it to Strava, Runkeeper etc) .
If I go to accounts -> edit accounts -> File I can export many activities to tcx files at once but it is limited to the last 100 and I have many more. 
Could you remove this limit please?

**Comment by gerhardol** [comment]
The sqLite export is to backup the app, but could be manipulated in some tool to crete exports (not sure if e.g. Excel->tcx exists).

Max 100 uploads (UploadActivity.java:186) limit is probably set to not flood a provider with uploads and not slow down the app. Maybe it is OK to increase this limit. I do not have data to play with though.

**Comment by Git-GT** [comment]
Hi gerhardol, 
Yep probably the limit is set to not flood the provider but in any case the limit itself is not a big deal, the "wrong" behavior here is  that the app allows to choose  only among the LAST 100 activities. For example if I have more than 100 activities and I want to upload only the first 10 I can't because I can't select them. Otherwise it would be ok to export let's say 400 activities in 4 groups of 100.

**Comment by gerhardol** [comment]
I changed so all activities are shown but all are not selected (except for file).
Will merge some other changes first

**Comment by Git-GT** [comment]
Thank you very much! :)

**Comment by davidedelvento** [comment]
@gerhardol yes, thanks for finding the issue and fixing it quickly. Now we are waiting for being able to do this.... 
Is is available yet in a released version? Perhaps in the beta? I really need it....

Thanks a lot and have a great weekend

**Comment by gerhardol** [comment]
No, not available yet
I would have preferred to get 2.0.2.1 released in Play before starting a new beta release, but the release is stuck on someone else...
I maybe do this soon anyway, together with a few other changes

**Comment by davidedelvento** [comment]
I see that this has been merged, but any ETA on when this will be pushed to the App store? I'm really waiting for this to be available...
Thanks!

**Comment by gerhardol** [comment]
I finally got access to Play, a beta is uploaded
