### ISSUE TITLE
Incorrect pace display since 2.0.3.0 in history

### ISSUE THREAD

**Issue by moobyfr** [jonasoreland/runnerup#866]
Hello
I noticed that the graphs are using incorrect values when viewing an run in the history, if the selection is on 'pace'. the values are ok for 'speed'

![Screenshot_20191226-072733-2](https://user-images.githubusercontent.com/628573/71462009-38461380-27b2-11ea-9077-2e4e88b874b1.png)

**Comment by gerhardol** [comment]
Created PR, also limiting y-axis to give better scaling when there are slow points
