### ISSUE TITLE
Distance discrepancy

### ISSUE THREAD

**Issue by GormCh** [jonasoreland/runnerup#867]
Hi folks!
My morning walk goes along the same route, 4,36 km. A couple a days ago the same route was suddenly registered as 4,92 km. I enclose one of the normal ones the one with a distance error.

Mobile is a Google Pixel 2.

Gorm
![map_2019-12-20](https://user-images.githubusercontent.com/27847008/71623385-7ab98700-2bdc-11ea-8aeb-53bd98f9eab0.jpg)
![map_2019-12-29](https://user-images.githubusercontent.com/27847008/71623407-a2a8ea80-2bdc-11ea-8683-6ce72c695405.jpg)
[txc-files.zip](https://github.com/jonasoreland/runnerup/files/4012786/txc-files.zip)

**Comment by gerhardol** [comment]
First, it is not the same route, Tegnersgatan on the shorter route.
Most of the problem is a bad GPS, adding bad points.

![image](https://user-images.githubusercontent.com/6248932/71629185-7309da80-2bfc-11ea-940a-959e14d07a93.png)

**Comment by GormCh** [comment]
Hi and thanks for your comment.
You are absolutely right about the GPS! Looking closely on the tracking one would think I was drunk!

Can something be done to get better GPS-tracking? My phone is a Google Pixel 2. It's not the most simple sort of phone.

Gorm

![photo_2020-01-04_21-02-13](https://user-images.githubusercontent.com/27847008/71771103-327cca80-2f36-11ea-9b3c-ec587adc8a52.png)

**Comment by gerhardol** [comment]
> Can something be done to get better GPS-tracking? My phone is a Google Pixel 2. It's not the most simple sort of phone.

What you basically can do is to make sure the accuracy is good before starting. (Expand the lower bar to see the details.)

But there is no possibility to get a better position by magic. The GPS is not better than that. GPS will get btter eventually with L5/E5 signals, but few phones support that yet (Pixel 4 did not support at launch for instance, Xiaomi has supported some longer).
GPS is the only I benefit with glass backsides vs metal back (but I want plastic phones back, in a larger number).

There is a discussion in https://github.com/jonasoreland/runnerup/issues/682#issuecomment-568247935, I doubt much can be done. In the example, the GPS path will be simplified to an arch, still far from the activity.

**Comment by gerhardol** [comment]
Try 2.0.4 that has an option to simplify the track by smoothing it.
Not sure if it helps here though, probably too much.

**Comment by GormCh** [comment]
Hi there.
It certainly did smooth the graph. The gps-tracking was awful but the smoothing works well, considering the poor tracking very good. The distance was origianally calculated to 4,92 km, in reality about 4,4 km. With the simplified track the distance is now calculated to 4.52 km - close to about a hundred metres. Well done!

I was not aware that it made any difference waiting to start until the gps status is GOOD. It really makes all the difference.

Thank you very much!
Gorm
