### ISSUE TITLE
Export to DropBox as GPX

### ISSUE THREAD

**Issue by opoto** [jonasoreland/runnerup#874]
Hi
Suggested enhancement:
Today DropBox export is always in TCX format. It would be nice to have the option to choose the GPX format, as it is done for the "File" export.
Thanks for the great work on this app!

**Comment by gerhardol** [comment]
Curious: Why do you want gpx for fitness data?
(I have an intention to process the extra data logged in the .gpx, but that is done so seldom that it not a problem to copy manually.)

It should be possible to achieve this with FileSynchronizer and DropSync app.
This is unfortunately not as trivial to add a checkbox, this is shared with other synchers.

I also await getting 50 users, there are 34 right now. When that is reached will DropBox block adding more users and approve/disapprove the application (cannot apply earlier...).

**Comment by opoto** [comment]
This would help to open files in "trails" apps, not specific to fitness, such as https://www.visorando.com or https://opoto.github.io/wtracks/ (ok, I'm particularly interested in this one ;)
I realized it might be tricky to add just for the Dropbox syncher. I thought maybe it could be a global "preferred file export format" setting, that could apply to both File and Dropbox syncher.
However I admit there are other ways to achieve it, such as using a 3rd party converter. But this is more cumbersome.
Your comment about Dropbox approval is more worrisome, I hope the app will be accepted.

**Comment by gerhardol** [comment]
> However I admit there are other ways to achieve it, such as using a 3rd party converter. But this is more cumbersome.

Agree, not committing

> Your comment about Dropbox approval is more worrisome, I hope the app will be accepted.

This is blocking adding new accounts, not reverting those that have 
I believe the DropBox rules are followed, I am not so worried.
But authentication may have to be changed, which will make F-Droid a little complicated.

**Comment by opoto** [comment]
I'll try to propose a PR

**Comment by opoto** [comment]
Done in #879
