### ISSUE TITLE
Segment simplification: GPX segments lost

### ISSUE THREAD

**Issue by opoto** [jonasoreland/runnerup#884]
Path simplification is a great new feature in v2.0.5.1. However I noticed a weird behavior when exporting to GPX. This is similar to what @dratasich reported [here](https://github.com/jonasoreland/runnerup/pull/871#discussion_r363344319) for laps. I have a recording with (too) many pauses:
![Screenshot_20200127-145054_RunnerUp](https://user-images.githubusercontent.com/1472722/73198206-f1419a00-4132-11ea-8734-d47ba7cf53af.jpg)
I think I tapped the pause button inadvertently... When zooming in some additional pauses can be seen.

When I export to GPX without simplification, RunnerUp creates multiple segments, which is ok. Here is how it looks like in a GPX viewer:
![before](https://user-images.githubusercontent.com/1472722/73198231-fbfc2f00-4132-11ea-9777-6266b518e27f.png)

When I activate simplification on GPX export, runner up still creates segments (unlike what I thought was implemented [here](https://github.com/jonasoreland/runnerup/pull/871/commits/2c4daeede32f2deab157faead059b32bf563df61)), and some of them are either empty (\<trkseg>\</trkseg>) or have a single \<trkpt>, so not visible in GPX viewers:
![after](https://user-images.githubusercontent.com/1472722/73198260-0c140e80-4133-11ea-8dcb-f08436d6822a.png)

I don't think this is correct. It is good to use GPX segments to split track when there are pauses. But simplification should then only happen *per segment*, and each segment should at least keep its first and last points, to properly keep the beginning and end of the segment.

**Comment by gerhardol** [comment]
> runner up still creates segments (unlike what I thought was implemented here), and some of them are either empty

Segments should be created for pauses only, will look at it

> I don't think this is correct. It is good to use GPX segments to split track when there are pauses. But simplification should then only happen per segment, and each segment should at least keep its first and last points, to properly keep the beginning and end of the segment.

Simplification without pauses (i.e. start-stop/pause) is an enhancement, not on my plan right now. Autopause may give problems, at least empty and single point segments should not be closed.
Patches are accepted for a complete implementation...

**Comment by gerhardol** [comment]
An attempt to avoid the empty trkseg, mostly untested.

**Comment by opoto** [comment]
Maybe I misunderstood how it is supposed to work. My expectation is that when i press pause, the part I just finished is recorded as a segment, and no recording happens during the pause. When i press resume a new segment is started and recording resumes. Is this correct?

**Comment by gerhardol** [comment]
> Maybe I misunderstood how it is supposed to work. My expectation is that when i press pause, the part I just finished is recorded as a segment, and no recording happens during the pause. When i press resume a new segment is started and recording resumes. Is this correct?

Correct, but rendered on the map and GPX trkseg only if "accuracy additions" at time of export (not when actually recorded - this is a hack).
But trkseg is not consistently handled.

Pauses in TCX though.

**Comment by opoto** [comment]
Do you think modifying path simplifier to work on segments is worth a PR? 
I would split the activity locations into segments, by looking for TYPE_PAUSE and TYPE_RESUME locations, and apply simplifications on each segment.

**Comment by gerhardol** [comment]
> Do you think modifying path simplifier to work on segments is worth a PR?

It is up to you, this is quite low in my plans, but if you make a high quality PR as your last, of course it will be accepted.

I would personally rather see a filter applied in activities. @dratasich pointed too a Kalman filter that could be used for live usage. But that is more work...

> I would split the activity locations into segments, by looking for TYPE_PAUSE and TYPE_RESUME locations, and apply simplifications on each segment.

Yes, something like that
