### ISSUE TITLE
runtastic import

### ISSUE THREAD

**Issue by dhiltonp** [jonasoreland/runnerup#89]
I've done some preliminary looking into runtastic imports (manually uploading an exported tcx and gpx), and the tcx data successfully imported pauses, while the gpx file didn't.

After authentication, the file is uploaded here: https://www.runtastic.com/import/upload_session (I get {"error":"Uploading failed"} when accessing the url directly)

**Comment by fourlightyears** [comment]
I tried to export an activity from Runnerup running on my old phone (using share/export or something) and then import it in my new phone (by using 'open with Runnerup from the file manager), in both gpx and tcx file formats, but in both cases the app said 'failed to import'. Is this related to the issue here? 

I am using v2.6.0.2, which is the latest version.

I remember I was able to do it once before in what is probably an older version. Has something broken in the new version, or am I simply doing it wrong?

**Comment by gerhardol** [comment]
There has been very minimal changes to .tcx and no changes I can think of for .gpx the last two years or so.
So it is likely something on the Runtastic side.

Compare to #1161 where Strava requires their own format to support importing cadence.

**Comment by gerhardol** [comment]
And the built-in uploader to Runtastic was removed some years ago, Runtastic removed support.

**Comment by fourlightyears** [comment]
Okay, sorry, I didn't even know what runtastic until now, I should have googled it before posting. I thought it might have been the old name for Runnerup.

I'm not using any third party apps. My problem is exporting from Runnerup and importing back to Runnerup. It's giving import failed regardless of whether it's done on the same phone or a different one.

**Comment by gerhardol** [comment]
Maintenance 
Export and import database 

RU can import workouts, not activities

**Comment by fourlightyears** [comment]
I already tried export and import database, but how do I copy the sqlite file into my other phone? It stores into an area that cannot be accessed i.e /Android/data/* , at least not without root.

**Comment by gerhardol** [comment]
Android have scooped storage, so this is what normal apps can access.
A file manager like Solid or Amaze has such privileges. adb should work too.

**Comment by fourlightyears** [comment]
Thanks, I got Amaze from F-droid, and I can access the database.

I'm wondering if it's possible to do a sync with WebDAV connection as well? I logged into my Nextcloud with Runnerup on both phones, and didn't see anything getting synced in history. 

PS: I had a look at the wiki, and saw upload 'OK' and Download blank for WebDAV, so assume it won't work ( https://github.com/jonasoreland/runnerup/wiki/Synchronization-with-external-providers ). Is this a feature that is planned at all?

**Comment by gerhardol** [comment]
> I'm wondering if it's possible to do a sync with WebDAV connection as well? I logged into my Nextcloud with Runnerup on both phones, and didn't see anything getting synced in history.

You can upload gpx/tcx to WebDAV
(sync can be done automatically or on request per activity).

> PS: I had a look at the wiki, and saw upload 'OK' and Download blank for WebDAV, so assume it won't work ( https://github.com/jonasoreland/runnerup/wiki/Synchronization-with-external-providers ). Is this a feature that is planned at all?

Download is not planned (by me, but someone else may contribute it).
Download would require parsing of activities as well which there is no support for. There were some previous formats that had implemented this, but here it would be tcx/gpx which is quite generic and it will be a lot of work to support expected formats..
