### ISSUE TITLE
Discontinued upload servers

### ISSUE THREAD

**Issue by opoto** [jonasoreland/runnerup#897]
Runner Up still offers to upload recorded tracks to servers/accounts which are not working anymore:

- Digifit: https://www.digifit.com
- FunBeat: https://www.funbeat.se
- Google Plus: https://plus.google.com
- Nike plus: https://nikeplus.nike.com
- RunnerUp LIVE: https://weide.devsparkles.se/Demo/Map
- RunningFreeOnline: https://www.runningfreeonline.com

They should be removed from Runner Up in order to simplify account preference UI, avoid user clicking on it and being stalled or get an error, reduce app size, and reduce source code to maintain.

**Comment by gerhardol** [comment]
I have not removed services that are not working as someone may use the template for a modified site and fix it. RU is not owned by me either.
So I have disabled but not removed services that are not working.
For these, LIVE may be revived if you setup that webserver (I have not tried it), the others are safe to remove (there are more candidates).

So please go ahead (maybe leave LIVE).
Garmin, Facebook will very likely never work (with the current APIs).
Runtastic and MapMyRun are unknown
GoogleFit, jogg.se should be fixable what I know

RunningAhead need to be investigated too (site still exists, so just disabling for now if not working).
RunKeeper API is deprecated and a PR to disable already exists.

Too bad that Tapiiriik.com is not fully working, that is what I added Dropbox for...

**Comment by opoto** [comment]
Fixed by #898
