### ISSUE TITLE
Linking with Strava not working

### ISSUE THREAD

**Issue by vojtechhuser** [jonasoreland/runnerup#911]
if a user logs in to strava via `Login using Google` (not email and psw) - the app gives error that such authentication is not allowed

Error 403: Disallowed_useragent   (text refers you to use browser), but that seems not an option (like open in browser) (since it opens within app browser like interface)

**Comment by gerhardol** [comment]
Duplicate of #791 

Some rewriting needed to support Login with Google, but there is a workaround
