### ISSUE TITLE
Window Leak in AccountListActivity

### ISSUE THREAD

**Issue by seg-ha** [jonasoreland/runnerup#913]
E/WindowManager( 4459): 
E/WindowManager( 4459): android.view.WindowLeaked: Activity org.runnerup.view.AccountListActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{527ec1f0 V.E..... R......D 0,0-729,192} that was originally added here
E/WindowManager( 4459): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager( 4459): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager( 4459): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager( 4459): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager( 4459): 	at org.runnerup.export.SyncManager.connect(SyncManager.java:267)
E/WindowManager( 4459): 	at org.runnerup.view.AccountListActivity$2.onItemClick(AccountListActivity.java:291)
E/WindowManager( 4459): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/WindowManager( 4459): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/WindowManager( 4459): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/WindowManager( 4459): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/WindowManager( 4459): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager( 4459): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager( 4459): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager( 4459): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager( 4459): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager( 4459): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager( 4459): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager( 4459): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager( 4459): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by gerhardol** [comment]
See #914
