### ISSUE TITLE
Unable to find explicit activity class

### ISSUE THREAD

**Issue by seg-ha** [jonasoreland/runnerup#914]
E/AndroidRuntime( 5502): FATAL EXCEPTION: main
E/AndroidRuntime( 5502): Process: org.runnerup, PID: 5502
E/AndroidRuntime( 5502): android.content.ActivityNotFoundException: Unable to find explicit activity class {org.runnerup.alpha/org.runnerup.view.ManageWorkoutsActivity}; have you declared this activity in your AndroidManifest.xml?
E/AndroidRuntime( 5502): 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
E/AndroidRuntime( 5502): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivityFromChild(Activity.java:3906)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivityFromChild(Activity.java:3882)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivityForResult(Activity.java:3455)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivityForResult(Activity.java:3385)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivity(Activity.java:3627)
E/AndroidRuntime( 5502): 	at android.app.Activity.startActivity(Activity.java:3595)
E/AndroidRuntime( 5502): 	at android.preference.Preference.performClick(Preference.java:970)
E/AndroidRuntime( 5502): 	at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:215)
E/AndroidRuntime( 5502): 	at android.widget.AdapterView.performItemClick(AdapterView.java:299)
E/AndroidRuntime( 5502): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1113)
E/AndroidRuntime( 5502): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:2911)
E/AndroidRuntime( 5502): 	at android.widget.AbsListView$3.run(AbsListView.java:3645)
E/AndroidRuntime( 5502): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 5502): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 5502): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5502): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 5502): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 5502): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 5502): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 5502): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 5502): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by gerhardol** [comment]
What app version? 
What is done to get the exception? 

The stack trace indicates that an "alpha" build was used, that was discontinued a year ago. 
This may be opening workouts from settings, that works for me.
