### ISSUE TITLE
F-Droid fails to build

### ISSUE THREAD

**Issue by licaon-kter** [jonasoreland/runnerup#916]
Please remove Windows CR/LF from endlines: https://github.com/jonasoreland/runnerup/blob/master/gradle/wrapper/gradle-wrapper.properties

/LE: Retag 2.0.6.0 after

**Comment by gerhardol** [comment]
Not the first time AS changed the endings on the file, set in .gitattributes

Where can I see the build logs, I was to open issue about the missing build?

**Comment by licaon-kter** [comment]
Buildserver output almost realtime: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=30&from=&hidebots=0&hideanons=1&hideliu=1&limit=500

Your app: https://f-droid.org/wiki/page/org.runnerup.free/lastbuild
