### ISSUE TITLE
Samsung android 10

### ISSUE THREAD

**Issue by nebmo** [jonasoreland/runnerup#922]
Anyone using Samsung galaxy an Android 10? I can't get it to register positions when screen is off.
Runnerup is set to track location always and i have tried to set it so Samsung shouldnt optimize battery usage for it.

**Comment by Marx2** [comment]
It made 3 runs to fix it but I've managed to do that on Samsung s20 ultra.
You need to disable battery optimization here and there.
The tricky part is you see by default unoptimized apps, you need to switch
to all, then switch off optimization.
Of course you shouldn't use any energy saving mode.

pon., 1 cze 2020, 16:41 użytkownik Niklas Weidemann <
notifications@github.com> napisał:

**Comment by nebmo** [comment]
Maybe problem is that i have phone on Medium Power saving. Not sure how to disable it? Set it to "Optimized" instead?

**Comment by gerhardol** [comment]
https://dontkillmyapp.com/samsung
No mention of Android Q though. 
Do Samsung whitelist common apps by default or the same problem for all?
(My S2 is not being updated to Q, so I have nothing to test with...)

**Comment by Marx2** [comment]
I'll translate, so try to find options in your language:
-Take care about phone-lightbulb-sleeping app
-Take care about phone-the dots-advanced- optimize settings-off
-Take care about phone - battery -optimized
-apps-three dots-special access-optimize battery usage -all
apps-RunnerUp-not optimize

pon., 1 cze 2020, 23:46 użytkownik Gerhard Olsson <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
#948 targets Android 10 and checks that location is allowed also in the background, not just "when in use". Was that the problem?
Plan to merge #948 quite soon.

**Comment by nebmo** [comment]
Problem was the Battery optimizations on the Samsung. After changing power saving to Optimized and then whitelist runnerup it works.
