### ISSUE TITLE
[Feature Request] Set Export File Name Pattern

### ISSUE THREAD

**Issue by srwareham** [jonasoreland/runnerup#924]
Sharing GPX files currently creates files named RunnerUp_0040.gpx etc. It would be great to allow some sort of rule/pattern for setting the file name. This would help for managing exports on a desktop or home server. 

Even without supporting more complex and dynamic patterns, perhaps the "name" record already present in the GPX files themselves would be a nice alternative (e.g.,  RunnerUp-Biking-2020-06-14T22:38:25Z.gpx).

**Comment by gerhardol** [comment]
Activity type is included in some exports, like the "File" export (as well as Dropbox, but Dropbox is closed for new users as it requires a rewrite to comply with Dropbox rules).

**Comment by srwareham** [comment]
Any guidance on how hard it would be to include date rather than a sequential number? I think that would be the main goal for my particular use case.

I think I might have also incidentally discovered a bug. I can go to Accounts, add "File" and leave the default file:///storage/emulated/0/Documents/RunnerUp. If I then click upload and select any number of files, then upload once again, no files are written to disk. I needed to disable auto upload, then go into the individual file to be able to "upload" it to a local file one at a time. This is version 2.0.6.1 on Android 10 on a pixel 3. This is with location and storage permissions enabled.

**Comment by gerhardol** [comment]
> Any guidance on how hard it would be to include date rather than a sequential number? I think that would be the main goal for my particular use case.

There are a number of decisions like to use ISO format but in local or UTC?, start time in minutes or seconds etc, but otherwise not so difficult
All exports should be changed (inconsistent right now)

> I think I might have also incidentally discovered a bug. I can go to Accounts, add "File" and leave the default file:///storage/emulated/0/Documents/RunnerUp. If I then click upload and select any number of files, then upload once again, no files are written to disk. I needed to disable auto upload, then go into the individual file to be able to "upload" it to a local file one at a time. This is version 2.0.6.1 on Android 10 on a pixel 3. This is with location and storage permissions enabled.

If an activity has been exported once for a provider, you have to clear the status to export again. (For online services, it is harder to check than for File.)
I see this as a feature for File to, if you have moved away the files they are not reexported

**Comment by srwareham** [comment]
@gerhardol I should have some time to work on this for a bit. I've poked around was hoping you might be able to point me in the right direction. I am testing by going to an activity, clicking "Share activity" -> "gpx" -> [Select file manager app of choice]. This produces a file name RunnerUp_0075.gpx, for example. I've been testing by building master.

It seems like the file write of RunnerUp_0075.gpx occurs at: 

https://github.com/jonasoreland/runnerup/blob/f253ad760ab3ac4051f1db04ff8ccfd052e921a5/app/src/main/org/runnerup/content/ActivityProvider.java#L167

However, I can't seem to figure out where the file name is actually set. At first, I thought it was here. However, when I debug using Android Studio ti doesn't seem like this code is hit.
https://github.com/jonasoreland/runnerup/blob/f253ad760ab3ac4051f1db04ff8ccfd052e921a5/app/src/main/org/runnerup/export/FileSynchronizer.java#L174

The last segment of the URI referenced at the following seems to contain the name. Would you know where this value is being set?
https://github.com/jonasoreland/runnerup/blob/f253ad760ab3ac4051f1db04ff8ccfd052e921a5/app/src/main/org/runnerup/content/ActivityProvider.java#L129

Perhaps relatedly, I did find where a cache file has it's name set, but I couldn't find analogous code for the shared/exported activity.

https://github.com/jonasoreland/runnerup/blob/f253ad760ab3ac4051f1db04ff8ccfd052e921a5/app/src/main/org/runnerup/content/ActivityProvider.java#L115

Thank you!

**Comment by gerhardol** [comment]
See https://github.com/jonasoreland/runnerup/blob/f253ad760ab3ac4051f1db04ff8ccfd052e921a5/app/src/main/org/runnerup/view/DetailActivity.java#L955
(I had to look up the ContentProvider too, a complex pattern...)

Name implemented for File in #938
DropBox, WebDAV missing too

All names should be formatted in the same way

**Comment by srwareham** [comment]
Thank you! Funny timing someone was also working on this just right now. I'd be happy to close this issue when #938 is merged.

**Comment by gerhardol** [comment]
Implemented in #938
