### ISSUE TITLE
Is there support for Garmin hrm2-ss?

### ISSUE THREAD

**Issue by openbrian** [jonasoreland/runnerup#925]
Default scanning uses only BLE evidently.

The scanner can not find it when using "Experimental HRM devices".

I read the wiki and made sure that i have the 2 system apps installed (ANT+ Plugins and ANT Radio Service).

**Comment by gerhardol** [comment]
> Default scanning uses only BLE evidently.

If ANT+ is detected in the phone, you can select to scan it.
Experimental is for really obscure protocols.

I am not sure what plugins that are actually needed for ANT+, but devices that only works in some apps are rare. Garmin should be standard compliant. 

ANT+ is not available in the F-Droid version (closed source).

**Comment by openbrian** [comment]
Indeed.  I'm using the version from F-Droid.  I'll check with Google Play soon.

**Comment by openbrian** [comment]
I uninstalled the Fdroid version.  The Google Play version doesn't install.  Is it just me?

**Comment by gerhardol** [comment]
> I uninstalled the Fdroid version. The Google Play version doesn't install. Is it just me?

The version in Play is old, only 1.x (old 2.x beta in the beta track).
The latest build is in GitHub:
https://github.com/jonasoreland/runnerup/releases

**Comment by openbrian** [comment]
I got the new release (2.0.6.0).  tapped Sensors, Heart rate monitor, SCAN, ANT+, OK.  Appears to have crashed.

Got an IllegalArgumentException, app icon exceeds maximum dimensions.  (25px x 25px) got (30px x 30px)

I'm using a Galaxy 9S+.   And I see 2.2 is out now.  I will install and try again.

**Comment by openbrian** [comment]
Connected this time.  Going out for a run.  Doing some GPS art with kids.

**Comment by openbrian** [comment]
I think it worked well.  First time using this app, but I do see my heart rate was in certain zones after my run.

OK to close.
