### ISSUE TITLE
Import without deleting?

### ISSUE THREAD

**Issue by regagain** [jonasoreland/runnerup#940]
Hi!

Is it possible to import without deleting the current database? Long story short, I have a couple of backups that I'd like to consolidate into a single database.

Thanks,

**Comment by gerhardol** [comment]
Not in the app itself.

It is not impossible to do it outside the app, but quite hard.
The database is SQLite, export/import basically copies the file to/from the storage.
There are some tools to manage SQLite databases, but I assume it will be hard to make sure that there are no conflicts when merging.
