### ISSUE TITLE
Feature Request:  "Indoors" or "Gym" activity mode

### ISSUE THREAD

**Issue by Angf** [jonasoreland/runnerup#96]
Hi there Jonas,
I'd like to make a feature request if possible - an "Indoors" or "Gym" mode, that allows the user to use RunnerUp without the GPS active.

It would allow users to use the app while indoors where a GPS signal is weak or non-existent, and users could still record an activity, with heart-rate data, use the timer interval modes, etc.

Keep up the great work!

**Comment by gerhardol** [comment]
Tracked in #533
