### ISSUE TITLE
cannot sign in runalyze

### ISSUE THREAD

**Issue by nicosmaris** [jonasoreland/runnerup#969]
Works from mobile chrome but not from runnerup

**Comment by gerhardol** [comment]
If this is F-Droid, only the testserver is supported in F-Droid, the service requires a private key that cannot be used with open source.
For the Play variant, direct login works but probably not Goggle/Facebook login

**Comment by nicosmaris** [comment]
Yes I am referring to Google SSO

**Comment by gerhardol** [comment]
Duplicate of #791
