### ISSUE TITLE
The start hour entered in the manual entry menu is increased by an hour when saved

### ISSUE THREAD

**Issue by opale95** [jonasoreland/runnerup#980]
Here i entered 15:30:
![Screenshot_20201022-160711](https://user-images.githubusercontent.com/70341161/97086248-5d99ed00-1622-11eb-82be-a43059f2a841.png)
In the history it shows 16:30:
![Screenshot_20201022-160718](https://user-images.githubusercontent.com/70341161/97086257-6b4f7280-1622-11eb-92c6-005104b26446.png)

**Comment by gerhardol** [comment]
This was supposed to be handled in #762, the interfaces haere are weird...

**Comment by opale95** [comment]
Could you try to reproduce the bug ? I noticed that when i go to the system settings and select UTC mode instead of Geographical Area mode, the bug does not occur.

**Comment by gerhardol** [comment]
> Could you try to reproduce the bug ? I noticed that when i go to the system settings and select UTC mode instead of Geographical Area mode, the bug does not occur.

Yes today, but probably not tomorrow (when summertime ends).
The handling is weird here, you have to convert back and forward to UTC.
