### ISSUE TITLE
Location permission won't stop

### ISSUE THREAD

**Issue by SpazMahTazz** [jonasoreland/runnerup#983]
I looked but couldn't see this already posted.

The DTEK for BlackBerry app I have on my KeyOne tells me when apps use permissions such as location, microphone, etc. It's pretty handy. According to DTEK, this app continues to access my location in the background even after force stopping and removing the location permission. I don't know if DTEK is playing up but it works quite well for other apps.

See the screenshots below.
1st one shows the notifications from DTEK say when RunnerUp is accessing my location
2nd one shows that RunnerUp is not granted location permission
3rd and 4th one are just the logs seen in DTEK.

I really like this app but if DTEK is not playing up then I don't like that RunnerUp keeps accessing my location.

<img src="https://user-images.githubusercontent.com/39617497/99012910-7b180200-25a3-11eb-8342-57752e80237c.png" width=40% height=40%> <img src="https://user-images.githubusercontent.com/39617497/99012917-7d7a5c00-25a3-11eb-878f-4e0dfa92518b.png" width=40% height=40%>
<img src="https://user-images.githubusercontent.com/39617497/99012919-7eab8900-25a3-11eb-9a6f-28ba91cf0ceb.png" width=40% height=40%> <img src="https://user-images.githubusercontent.com/39617497/99012922-7f441f80-25a3-11eb-9f14-52051da263af.png" width=40% height=40%>

**Comment by SpazMahTazz** [comment]
My current work around to make it stop is exporting the database, uninstalling the app, reinstalling it, then importing the database back.

**Comment by gerhardol** [comment]
RunnerUp is only using location when GPS is started in the app, there is no hidden access implemented...
Notification is present whenever location is accessed.
I am not aware of situations where the notification is lost somehow.

On my wife's Samsung tablet Android constantly warns about background location as well, also when the application has not been started, it warns about the permission. (There is an explicit check that background location is activated when starting GPS to make sure that the app works when the user is triggered to turn location off.)
The message here is slightly different, I cannot explain what is going on.
(Without background access there would not be much point in having a fitness tracker...)

**Comment by gerhardol** [comment]
https://developer.android.com/training/location/permissions#reminder-background-location-grant

This is a "feature" in Android 10. If you do not trust the app, just deactivate background location in Settings.
You cannot start a run without activating background location.
