### ISSUE TITLE
Heart rate zone target unexpected behavior

### ISSUE THREAD

**Issue by Chushuhuch** [jonasoreland/runnerup#991]
I'm creating custom workout with heart rate zone target. Each time I choose some target zone and press ok it is saved and shown correctly in the interface.
But after I enter editing the step again, the zone is different or not set at all.
Also it seems that during workout the zone was also wrong since I didn't get any message from the app that my pulse is too high. At least it worked for the pulse too low. So maybe this is broken as well.

**Comment by gerhardol** [comment]
It is only possible to edit the lower limit, the upper is set from previous lower.

The UI should not allow chaning the upper limit.

**Comment by Chushuhuch** [comment]
I'm not sure. Are you talking about HR zone limits set up?
I've meant workout creation feature. I believe setting HR zone limits is a different thing.
Do you mean that HR targets are lower bound only?

**Comment by gerhardol** [comment]
HR zones are created using lower zones only so that may be something different.

I can edit HR zones, not tried the limits.

**Comment by Chushuhuch** [comment]
Oh, indeed. I can edit the upper limit, but the change is not saved.
Still, at least in the UI any zone is a range. And in general if I'm setting the goal to run in zone 3, my personal goal is usually not to go to zone 4 accidentally. And probably for zones 4 and 5 it is opposite - not to go too low. So I personally would expect alerts both for having too high and too low HR.

Also just found that saved HR zone is +2 to the selected. If I choose zone 1, after closing and reopening it becomes zone 3. And zones 4 and 5 become empty.

**Comment by gerhardol** [comment]
Closed by #991
