### ISSUE TITLE
Current speed is not displayed

### ISSUE THREAD

**Issue by zarandya** [jonasoreland/runnerup#993]
The tracker is displaying my average and lap speed/pace correctly but it is displaying 0 for current speed or "--" for current pace. 

Looks like I am hitting this case in `Tracker.java`:
``` java
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN_MR1) {
            if ((SystemClock.elapsedRealtimeNanos() - mLastLocation.getElapsedRealtimeNanos()) >
                    MAX_HR_AGE * NANO_IN_MILLI) {
                return null;
            }
        }
```
My `SystemClock.elapsedRealtimeNanos() - mLastLocation.getElapsedRealtimeNanos()` is consistently between 3.3 and 3.9 seconds. My phone is apparently delaying location samples by about 3s. Rebooting my device fixes it temporarily, but I'd like it to work anytime while also using other apps. 

Could the threshold be increased? Why is it related to the maximum HR anyway?

**Comment by gerhardol** [comment]
I assume that this was added to not present out of date information, the same time for pace/speed and HR.

But the minimum time should be increased. 5s seem reasonable, so I suggest 10s.
